### ISSUE TITLE
Sequence Lock Contention on Apache Derby: FHIR Persistence failed on the examples

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#1038]
**Describe the bug**
FHIR Persistence failed on the examples test with Derby. 

```
May 06, 2020 6:50:04 PM com.ibm.fhir.persistence.jdbc.dao.impl.FHIRDbDAOImpl severe
SEVERE: SQLException encountered while inserting Resource.
java.sql.BatchUpdateException: A lock could not be obtained within the time requested
	at org.apache.derby.impl.jdbc.EmbedStatement.executeLargeBatch(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeBatch(Unknown Source)
	at com.ibm.fhir.persistence.jdbc.dao.impl.ParameterVisitorBatchDAO.close(ParameterVisitorBatchDAO.java:629)
```
Digging into the issue
```
java.sql.BatchUpdateException: A lock could not be obtained within the time requested
	at org.apache.derby.impl.jdbc.EmbedStatement.executeLargeBatch(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeBatch(Unknown Source)
	at com.ibm.fhir.persistence.jdbc.dao.impl.ParameterVisitorBatchDAO.close(ParameterVisitorBatchDAO.java:629)
	at com.ibm.fhir.persistence.jdbc.derby.DerbyResourceDAO.storeResource(DerbyResourceDAO.java:444)
	at com.ibm.fhir.persistence.jdbc.derby.DerbyResourceDAO.insert(DerbyResourceDAO.java:129)

 Caused by: ERROR 40XL1: A lock could not be obtained within the time requested
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.catalog.SequenceUpdater.tooMuchContentionException(Unknown Source)
	at org.apache.derby.impl.sql.catalog.SequenceUpdater.getCurrentValueAndAdvance(Unknown Source)

Caused by: java.sql.SQLTransactionRollbackException: A lock could not be obtained within the time requested
```

The sequence prefetches 1000 values in the sequence. Since it's using multiple threads, it's going go beyond that fetch size and drive contention in derby. that's where the contention comes from in certain circumstances exceed 1000.

```sql 
CREATE TABLE FHIRAPP.APPOINTMENT_STR_VALUES(MT_ID INT NOT NULL, ROW_ID BIGINT GENERATED BY DEFAULT AS IDENTITY, PARAMETER_NAME_ID INT NOT NULL, STR_VALUE VARCHAR(1024 OCTETS), STR_VALUE_LCASE VARCHAR(1024 OCTETS), LOGICAL_RESOURCE_ID BIGINT NOT NULL, CONSTRAINT PK_APPOINTMENT_STR_VALUES PRIMARY KEY (MT_ID, ROW_ID)) IN FHIR_TS PARTITION BY RANGE (MT_ID) (STARTING 0 INCLUSIVE    ENDING 0 INCLUSIVE );
```

**To Reproduce**
1. Rebuild with multiple threads

This is rare and occurs due to lock contention on the sequence generator when there is a large set of inflight transactions - specifically - here `ROW_ID BIGINT GENERATED BY DEFAULT AS IDENTITY`

**Expected behavior**
Build should pass

**Additional context**
* [Build](https://github.com/IBM/FHIR/runs/650573986?check_suite_focus=true)
* [#426](https://github.com/IBM/FHIR/issues/426)

**Comment by prb112** [comment]
[/DERBY-6975: ERROR 40XL1: A lock could not be obtained within the time requested](https://issues.apache.org/jira/browse/DERBY-6975)
Preallocation - https://db.apache.org/derby/docs/10.9/ref/rrefproperpreallocator.html

I've updated the code to work with this.

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/1059
