### ISSUE TITLE
US Core 3.1.0 StructureDefinition-us-core-careplan.json has a constraint with unescaped `div`.

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#1041]
**Describe the bug**
US Core 3.1.0 StructureDefinition-us-core-careplan.json has a constraint with unescaped `div`.

**To Reproduce**
1. Download https://github.com/inferno-community/uscore-data-sets/blob/update/large_population_bundle-03-09-2020.zip
2. Extract ./large_population_bundle-03-09-2020/Cody889_Koss676_342e5ea8-983e-486d-a828-2ebd224f9724.json
3. Add the US Core Library to the classpath
4. Execute this code snippet to load the file
```
try (InputStream in = Files.newInputStream(Paths.get(f.toURI()))) {
            Resource resource = FHIRParser.parser(Format.JSON).parse(in);
            List<Issue> issues = FHIRValidator.validator().validate(resource, true);
            List<Issue> warnings =
                    issues.stream().filter(issue -> issue.getSeverity().equals(IssueSeverity.WARNING))
                            .collect(Collectors.toList());
            List<Issue> others =
                    issues.stream().filter(issue -> !issue.getSeverity().equals(IssueSeverity.WARNING))
                            .collect(Collectors.toList());
```
5. The code snippet 
```
[TESTING] 
line 1:14 mismatched input 'div' expecting {'is', 'as', 'in', 'contains', '$this', '$index', '$total', IDENTIFIER, DELIMITEDIDENTIFIER}
line 1:17 mismatched input '<EOF>' expecting {'+', '-', 'is', 'as', 'in', 'contains', '(', '{', 'true', 'false', '%', '$this', '$index', '$total', DATE, DATETIME, TIME, IDENTIFIER, DELIMITEDIDENTIFIER, STRING, NUMBER}
Exception in thread "main" com.ibm.fhir.validation.exception.FHIRValidationException: An error occurred during validation
	at com.ibm.fhir.validation.FHIRValidator.validate(FHIRValidator.java:169)
	at com.ibm.fhir.validation.FHIRValidator.validate(FHIRValidator.java:100)
	at com.ibm.fhir.validation.uscore.Main.main(Main.java:46)
Caused by: java.lang.RuntimeException: An error occurred while validating constraint: txt-1 with location: CarePlan.text.div and expression: htmlChecks() at path: Bundle.entry[7].resource
	at com.ibm.fhir.validation.FHIRValidator$ValidatingNodeVisitor.validate(FHIRValidator.java:344)
	at com.ibm.fhir.validation.FHIRValidator$ValidatingNodeVisitor.validate(FHIRValidator.java:295)
	at com.ibm.fhir.validation.FHIRValidator$ValidatingNodeVisitor.validate(FHIRValidator.java:276)
	at com.ibm.fhir.validation.FHIRValidator$ValidatingNodeVisitor.doVisit(FHIRValidator.java:256)
	at com.ibm.fhir.path.visitor.FHIRPathDefaultNodeVisitor.visit(FHIRPathDefaultNodeVisitor.java:81)
	at com.ibm.fhir.path.FHIRPathResourceNode.accept(FHIRPathResourceNode.java:176)
	at com.ibm.fhir.path.visitor.FHIRPathDefaultNodeVisitor.visitChildren(FHIRPathDefaultNodeVisitor.java:34)
	at com.ibm.fhir.path.visitor.FHIRPathDefaultNodeVisitor.visit(FHIRPathDefaultNodeVisitor.java:61)
	at com.ibm.fhir.path.FHIRPathElementNode.accept(FHIRPathElementNode.java:241)
	at com.ibm.fhir.path.visitor.FHIRPathDefaultNodeVisitor.visitChildren(FHIRPathDefaultNodeVisitor.java:34)
	at com.ibm.fhir.path.visitor.FHIRPathDefaultNodeVisitor.visit(FHIRPathDefaultNodeVisitor.java:82)
	at com.ibm.fhir.path.FHIRPathResourceNode.accept(FHIRPathResourceNode.java:176)
	at com.ibm.fhir.validation.FHIRValidator$ValidatingNodeVisitor.validate(FHIRValidator.java:241)
	at com.ibm.fhir.validation.FHIRValidator$ValidatingNodeVisitor.access$100(FHIRValidator.java:226)
	at com.ibm.fhir.validation.FHIRValidator.validate(FHIRValidator.java:166)
	... 2 more
Caused by: com.ibm.fhir.path.exception.FHIRPathException: java.lang.NullPointerException  [probeId=ac-13-0-2-76141266-ce29-4103-b08f-ca065b27e402]
	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator.evaluate(FHIRPathEvaluator.java:258)
	at com.ibm.fhir.validation.FHIRValidator$ValidatingNodeVisitor.validate(FHIRValidator.java:312)
	... 16 more
Caused by: java.lang.NullPointerException
	at com.ibm.fhir.path.util.FHIRPathUtil.isSingleton(FHIRPathUtil.java:492)
	at com.ibm.fhir.path.util.FHIRPathUtil.hasSystemValue(FHIRPathUtil.java:196)
```
5. The cause is the unescaped `.div` in the path
```
{
			"id": "CarePlan.text.div",
			"path": "CarePlan.text.div",
			"short": "Limited xhtml content",
			"definition": "The actual narrative content, a stripped down version of XHTML.",
			"comment": "The contents of the html element are an XHTML fragment containing only the basic html formatting elements described in chapters 7-11 and 15 of the HTML 4.0 standard, <a> elements (either name or href), images and internally contained stylesheets. The XHTML content SHALL NOT contain a head, a body, external stylesheet references, scripts, forms, base/link/xlink, frames, iframes and objects.",
			"min": 1,
			"max": "1",
			"base": {
				"path": "Narrative.div",
				"min": 1,
				"max": "1"
			},
			"type": [{
				"code": "xhtml"
			}],
			"constraint": [{
				"key": "ele-1",
				"severity": "error",
				"human": "All FHIR elements must have a @value or children",
				"expression": "hasValue() or (children().count() > id.count())",
				"xpath": "@value|f:*|h:div",
				"source": "http://hl7.org/fhir/StructureDefinition/Element"
			},
			{
				"key": "txt-1",
				"severity": "error",
				"human": "The narrative SHALL contain only the basic html formatting elements and attributes described in chapters 7-11 (except section 4 of chapter 9) and 15 of the HTML 4.0 standard, <a> elements (either name or href), images and internally contained style attributes",
				"expression": "htmlChecks()",
				"xpath": "not(descendant-or-self::*[not(local-name(.)=('a', 'abbr', 'acronym', 'b', 'big', 'blockquote', 'br', 'caption', 'cite', 'code', 'col', 'colgroup', 'dd', 'dfn', 'div', 'dl', 'dt', 'em', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'i', 'img', 'li', 'ol', 'p', 'pre', 'q', 'samp', 'small', 'span', 'strong', 'sub', 'sup', 'table', 'tbody', 'td', 'tfoot', 'th', 'thead', 'tr', 'tt', 'ul', 'var'))]) and not(descendant-or-self::*/@*[not(name(.)=('abbr', 'accesskey', 'align', 'alt', 'axis', 'bgcolor', 'border', 'cellhalign', 'cellpadding', 'cellspacing', 'cellvalign', 'char', 'charoff', 'charset', 'cite', 'class', 'colspan', 'compact', 'coords', 'dir', 'frame', 'headers', 'height', 'href', 'hreflang', 'hspace', 'id', 'lang', 'longdesc', 'name', 'nowrap', 'rel', 'rev', 'rowspan', 'rules', 'scope', 'shape', 'span', 'src', 'start', 'style', 'summary', 'tabindex', 'title', 'type', 'valign', 'value', 'vspace', 'width'))])"
			},
			{
				"key": "txt-2",
				"severity": "error",
				"human": "The narrative SHALL have some non-whitespace content",
				"expression": "htmlChecks()",
				"xpath": "descendant::text()[normalize-space(.)!=''] or descendant::h:img[@src]"
			}],
			"isModifier": false,
			"isSummary": false,
			"mapping": [{
				"identity": "rim",
				"map": "N/A"
			}]
		}
```

**Expected behavior**
The code should defend against this issue. 

**Additional context**
A previous HL7 FHIR Tracker item on `div` usage in FHIRPath expressions was opened, and some defenses were created for protecting against this with SearchParameters. 

Related https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-careplan.html

**Comment by prb112** [comment]
John merged the code.

**Comment by prb112** [comment]
And I confirm it works in my workspace.
