### ISSUE TITLE
failed to import to newly created postgresql database 

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#1064]
Create a new postgresql database fhirdb2;
Create fhirdata schema using the schema tool.
update schema using the schema tool.
import resource and failed.

(Note: Import works well with existing fhirdb postgresql database).

Got unexpected following exception:
[5/11/20 16:07:03:099 UTC] [step1 partition0] com.ibm.fhir.persistence.jdbc.dao.impl.ResourceDAOImpl         Failure storing Resource type name id: name=Encounter
                                 org.postgresql.util.PSQLException: ERROR: fhirdata.add_resource_type(character varying) is not a procedure
  Hint: To call a function, use SELECT.
  Position: 6
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2533)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2268)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:313)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159)
	at org.postgresql.jdbc.PgCallableStatement.executeWithFlags(PgCallableStatement.java:77)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.postgresql.ds.PGPooledConnection$StatementHandler.invoke(PGPooledConnection.java:428)
	at com.sun.proxy.$Proxy128.execute(Unknown Source)
	at com.ibm.ws.rsadapter.jdbc.WSJdbcPreparedStatement.execute(WSJdbcPreparedStatement.java:390)
	at com.ibm.fhir.persistence.jdbc.dao.impl.ResourceDAOImpl.readResourceTypeId(ResourceDAOImpl.java:368)
	at com.ibm.fhir.persistence.jdbc.dao.impl.ResourceDAOImpl.insert(ResourceDAOImpl.java:498)
	at com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl.update(FHIRPersistenceJDBCImpl.java:389)
	at com.ibm.fhir.bulkimport.ChunkWriter.writeItems(ChunkWriter.java:198)

Need to investigate/change: 
(1) change the schema tool to pre-populate fhir resource types.
(2) figure out why the default db2 ResourceDao implementation is called instead of the postgresql fhirdao.

**Comment by prb112** [comment]
@albertwang-ibm I tested the prepopulation of the FHIR Resource Types on postgresql did this not work for you?

**Comment by prb112** [comment]
Worked with Albert on https://github.com/IBM/FHIR/pull/1066 (added two guards)

**Comment by albertwang-ibm** [comment]
The first issue about pre-population is fixed with #1066.

**Comment by albertwang-ibm** [comment]
Found the root cause of the exception is caused by the database name, because there is "db2" in the database name, so it was mis-interpreted to a DB2 data source instead of postgresql. the fix is to make FhirDBDAOFactory more robust/accurate to db types.
