### ISSUE TITLE
Upon Second Schema deployment, VersionHistoryService reports error and the update-schema is stopped. 

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#1065]
**Describe the bug**
Upon Second Schema deployment, VersionHistoryService reports error and the update-schema is stopped. 

```
com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-601, SQLSTATE=42710, SQLERRMC=FHIR_OAUTH.OAUTH20CONSENTCACHE;TABLE, DRIVER=4.26.14
com.ibm.fhir.database.utils.api.DuplicateNameException: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-601, SQLSTATE=42710, SQLERRMC=FHIR_OAUTH.OAUTH20CONSENTCACHE;TABLE, DRIVER=4.26.14
	at com.ibm.fhir.database.utils.db2.Db2Translator.translate(Db2Translator.java:106)
	at com.ibm.fhir.database.utils.common.CommonDatabaseAdapter.runStatement(CommonDatabaseAdapter.java:218)
```

Version History shows OAUTH

```
[db2inst1@4dda34a66a99 ~]$ db2 "SELECT * FROM FHIR_ADMIN.VERSION_HISTORY" | grep -i oauth
FHIR_OAUTH                                                       TABLE            OAUTH20CACHE                                                               1 2020-05-11-15.39.59.440780
FHIR_OAUTH                                                       TABLE            OAUTH20CONSENTCACHE                                                        1 2020-05-11-15.39.59.537413
FHIR_OAUTH                                                       TABLE            OAUTH20CLIENTCONFIG                                                        1 2020-05-11-15.39.59.583604
```

**To Reproduce**
1. Create Schema 1 - dev1
```--prop-file db2.properties
--pool-size 2
--schema-name FHIR_DEV1
--update-schema```
1. Create Schema 1 - dev2
```--prop-file db2.properties
--pool-size 2
--schema-name FHIR_DEV2
--update-schema```
1. Error is shown, and it should not be displayed as the OAuth Tables successfully exist.

**Expected behavior**
The schema should successfully deploy.

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/1066
