### ISSUE TITLE
R4JDBCExamplesProcessor fails to correctly set tenant key for DB2

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1122]
**Describe the bug**
The R4JDBCExamplesProcessor test fails when configured to use DB2 and the multi-tenant schema:

**To Reproduce**
Run com.ibm.fhir.persistence.jdbc.test.spec.Main
--prop-file fhiruser.properties
--schema-name FHIRDATA
--tenant-name "TENANT_NAME_GOES_HERE"
--tenant-key "TENANT_KEY_GOES_HERE="

May 19, 2020 1:36:48 PM com.ibm.fhir.model.spec.test.R4ExamplesDriver processExample
SEVERE: processResource(json/spec/medicinalproductingredient-example.json) unexpected failure: 
com.ibm.fhir.persistence.jdbc.exception.FHIRPersistenceDataAccessException: Failure storing Resource type name id: name=MedicinalProductIngredient  [probeId=c0-a8-1-98-767afb44-86cc-42fd-aeef-dace58ffcbd3]
	at com.ibm.fhir.persistence.jdbc.dao.impl.ResourceDAOImpl.readResourceTypeId(ResourceDAOImpl.java:378)
	at com.ibm.fhir.persistence.jdbc.dao.impl.ResourceDAOImpl.insert(ResourceDAOImpl.java:498)
	at com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl.create(FHIRPersistenceJDBCImpl.java:264)
	at com.ibm.fhir.persistence.jdbc.test.spec.CreateOperation.process(CreateOperation.java:48)
	at com.ibm.fhir.persistence.jdbc.test.spec.R4JDBCExamplesProcessor.process(R4JDBCExamplesProcessor.java:158)
	at com.ibm.fhir.model.spec.test.R4ExamplesDriver.processExample(R4ExamplesDriver.java:378)
	at com.ibm.fhir.model.spec.test.R4ExamplesDriver.processExample(R4ExamplesDriver.java:274)
	at com.ibm.fhir.model.spec.test.R4ExamplesDriver$1.run(R4ExamplesDriver.java:206)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

.May 19, 2020 1:36:48 PM com.ibm.fhir.persistence.jdbc.dao.impl.FHIRDbDAOImpl severe
SEVERE: Failure storing Resource type name id: name=MedicinalProductInteraction
com.ibm.db2.jcc.am.SqlIntegrityConstraintViolationException: DB2 SQL Error: SQLCODE=-407, SQLSTATE=23502, SQLERRMC=TBSPACEID=-6, TABLEID=-32767, COLNO=0, DRIVER=4.26.14
	at com.ibm.db2.jcc.am.b7.a(b7.java:806)
	at com.ibm.db2.jcc.am.b7.a(b7.java:66)
	at com.ibm.db2.jcc.am.b7.a(b7.java:140)
	at com.ibm.db2.jcc.am.k4.b(k4.java:2471)
	at com.ibm.db2.jcc.am.k4.c(k4.java:2452)
	at com.ibm.db2.jcc.t4.ab.n(ab.java:914)
	at com.ibm.db2.jcc.t4.ab.f(ab.java:156)
	at com.ibm.db2.jcc.t4.p.e(p.java:81)
	at com.ibm.db2.jcc.t4.av.k(av.java:175)
	at com.ibm.db2.jcc.am.k4.ao(k4.java:2413)
	at com.ibm.db2.jcc.am.k5.a(k5.java:4686)
	at com.ibm.db2.jcc.am.CallableStatement.b(CallableStatement.java:134)
	at com.ibm.db2.jcc.am.CallableStatement.a(CallableStatement.java:103)
	at com.ibm.db2.jcc.am.CallableStatement.execute(CallableStatement.java:93)
	at com.ibm.fhir.persistence.jdbc.dao.impl.ResourceDAOImpl.readResourceTypeId(ResourceDAOImpl.java:368)
	at com.ibm.fhir.persistence.jdbc.dao.impl.ResourceDAOImpl.insert(ResourceDAOImpl.java:498)
	at com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl.create(FHIRPersistenceJDBCImpl.java:264)
	at com.ibm.fhir.persistence.jdbc.test.spec.CreateOperation.process(CreateOperation.java:48)
	at com.ibm.fhir.persistence.jdbc.test.spec.R4JDBCExamplesProcessor.process(R4JDBCExamplesProcessor.java:158)
	at com.ibm.fhir.model.spec.test.R4ExamplesDriver.processExample(R4ExamplesDriver.java:378)
	at com.ibm.fhir.model.spec.test.R4ExamplesDriver.processExample(R4ExamplesDriver.java:274)
	at com.ibm.fhir.model.spec.test.R4ExamplesDriver$1.run(R4ExamplesDriver.java:206)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Expected behavior**
R4JDBCExamplesProcessor should complete successfully.

**Additional context**
The R4JDBCExamplesProcessor is still using FHIRRequestContext to pass the tenant configuration information to the JDBC persistence layer. This has been deprecated by an earlier change, so the examples processor needs to be updated to use the new mechanism (see FHIRDbDAOImpl).

The FHIRRequestContext should also be updated to remove the tenant configuration fields and methods which are no longer required.

**Comment by lmsurpre** [comment]
We decided to wait until after Sprint 12 / 4.2.2 to address this one.

**Comment by punktilious** [comment]
As a workaround, the tenantKey can be provided using the fhir-server-config mechanism. Create a file `<working-directory>/config/performance/fhir-server-config.json` where `performance` is the tenant name. The fhir-server-config.json file needs to contain the following:

```
{
    "__comment": "FHIR Server configuration",
    "fhirServer": {
        "persistence": {
            "datasources": {
                "default": {
                    "tenantKey": "REAL_TENANT_KEY_GOES_HERE=",
                    "type": "db2",
                    "multitenant": true
                }
            }
        }
    }
}
```

Note that `default` in the above configuration refers to the datasource id. The value for the tenantKey property must match the value provided with the command-line argument --tenant-key.
