### ISSUE TITLE
NullPointer in ImportJobListener.afterJob

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1361]
**Describe the bug**
On the 4.3.1 release, after successfully importing a bunch of AllergyIntolerance resources, it failed at the very end:
```
[7/27/20 4:24:01:962 UTC] com.ibm.ws.batch.JobLogger                                     CWWKY0020I: Step step1 ended with batch status COMPLETED and exit status COMPLETED for job instance 4 and job execution 4.
[7/27/20 4:24:02:096 UTC] com.ibm.ws.batch.JobLogger                                     CWWKY0034I: An exception occurred while running the final portion of the job.
com.ibm.jbatch.container.exception.BatchContainerRuntimeException: java.lang.NullPointerException
	at com.ibm.jbatch.container.artifact.proxy.JobListenerProxy.afterJob(JobListenerProxy.java:35)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.jobListenersAfterJob(WorkUnitThreadControllerImpl.java:450)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.endOfWorkUnit(WorkUnitThreadControllerImpl.java:259)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeWorkUnit(WorkUnitThreadControllerImpl.java:210)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl$AbstractControllerHelper.runExecutionOnThread(WorkUnitThreadControllerImpl.java:503)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.runExecutionOnThread(WorkUnitThreadControllerImpl.java:92)
	at com.ibm.jbatch.container.util.BatchWorkUnit.run(BatchWorkUnit.java:113)
	at com.ibm.ws.context.service.serializable.ContextualRunnable.run(ContextualRunnable.java:79)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:821)
Caused by: java.lang.NullPointerException
	at com.ibm.fhir.jbatch.bulkdata.load.ImportJobListener.afterJob(ImportJobListener.java:93)
	at com.ibm.jbatch.container.artifact.proxy.JobListenerProxy.afterJob(JobListenerProxy.java:33)
	... 13 more
```

**To Reproduce**
1. kickoff an import (AllergyIntolerance from IBM Cloud Object Store in my case) with a config like this:
```
    "bulkdata": {
      "bulkDataBatchJobIdEncryptionKey": "***",
      "applicationName": "fhir-bulkimportexport-webapp",
      "moduleName": "fhir-bulkimportexport.war",
      "jobParameters": {
        "cos.bucket.name": "syntheticmass",
        "cos.location": "us",
        "cos.endpointurl": "https://s3.private.us-east.cloud-object-storage.appdomain.cloud",
        "fhir.tenant": "default",
        "cos.credential.ibm": "Y",
        "cos.api.key": "***",
        "cos.srvinst.id": "crn:v1:bluemix:public:cloud-object-storage:global:a/***"
      },
      "implementation_type": "cos",
      "batch-uri": "https://localhost:9443/ibm/api/batch/jobinstances",
      "batch-user": "fhiruser",
      "batch-user-password": "***",
      "batch-truststore" : "resources/security/fhirTrustStore.p12",
      "useFhirServerTrustStore": "Y",
      "batch-truststore-password" : "change-password",
      "validBaseUrls": []
    }
```

**Expected behavior**
The job should succeed or fail without throwing an error like this.

**Additional context**
Looking at the line in question, I don't see how either `inputUrlSequenceMap` nor `partitionSummary` could be null:  https://github.com/IBM/FHIR/blob/4.3.1/fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/jbatch/bulkdata/load/ImportJobListener.java#L93
Maybe something inserted a null entry into the partitionSummaries list somehow?

**Comment by prb112** [comment]
Got to the root cause. Added Details in the commit log (abbreviated here)... 
Occasionally we don't set the importResourceType on the PartitionPlan.  I've added code to make sure this is set.

**Comment by lmsurpre** [comment]
I ran a number of imports in our connectathon environment and I never hit this issue.  I did hit a separate issue, #2077, but I think its unrelated.
