### ISSUE TITLE
investigate benign NPE in CI pipeline

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1370]
**Describe the bug**
Found this one in the build output:
```
2020-07-28T15:42:11.1174029Z Jul 28, 2020 3:42:11 PM com.ibm.fhir.operation.bulkdata.processor.BulkDataFactory getTenantInstance
2020-07-28T15:42:11.1174413Z WARNING: found no tenant specific bulkdata.json
2020-07-28T15:42:11.1174664Z java.lang.NullPointerException
2020-07-28T15:42:11.1174902Z 	at java.lang.String.compareTo(String.java:1155)
2020-07-28T15:42:11.1176227Z 	at com.ibm.fhir.operation.bulkdata.processor.BulkDataFactory.getTenantInstance(BulkDataFactory.java:41)
2020-07-28T15:42:11.1177446Z 	at com.ibm.fhir.operation.bulkdata.BulkdataOperationTest.testBulkDataFactory(BulkdataOperationTest.java:55)
2020-07-28T15:42:11.1178121Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-07-28T15:42:11.1179084Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-07-28T15:42:11.1180128Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-07-28T15:42:11.1180689Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2020-07-28T15:42:11.1181777Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
2020-07-28T15:42:11.1182416Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
2020-07-28T15:42:11.1183259Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
2020-07-28T15:42:11.1184064Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
2020-07-28T15:42:11.1184999Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
2020-07-28T15:42:11.1185815Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
2020-07-28T15:42:11.1186424Z 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
2020-07-28T15:42:11.1186983Z 	at org.testng.TestRunner.run(TestRunner.java:505)
2020-07-28T15:42:11.1187579Z 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
2020-07-28T15:42:11.1188490Z 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
2020-07-28T15:42:11.1189020Z 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
2020-07-28T15:42:11.1189988Z 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
2020-07-28T15:42:11.1190913Z 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
2020-07-28T15:42:11.1191790Z 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
2020-07-28T15:42:11.1192629Z 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
2020-07-28T15:42:11.1193746Z 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
2020-07-28T15:42:11.1194410Z 	at org.testng.TestNG.runSuites(TestNG.java:1049)
2020-07-28T15:42:11.1194849Z 	at org.testng.TestNG.run(TestNG.java:1017)
2020-07-28T15:42:11.1195995Z 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
2020-07-28T15:42:11.1197490Z 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
2020-07-28T15:42:11.1199566Z 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
2020-07-28T15:42:11.1200849Z 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
2020-07-28T15:42:11.1202542Z 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
2020-07-28T15:42:11.1204088Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
2020-07-28T15:42:11.1205009Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
2020-07-28T15:42:11.1206762Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

Definitely seems to be benign, but it doesn't seem like this code should through an NPE (even internally) for this case.  Just wanted to capture it as something to look at.

**To Reproduce**
Run the build (with tests) and check the output

**Expected behavior**
not sure yet

**Comment by lmsurpre** [comment]
found and fixed minor bug
