### ISSUE TITLE
Invalid SQL generated from missing modifier on a whole-system search parameter

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1415]
**Describe the bug**
Invalid SQL query generated by whole-system search with a "missing" modifier.
```
SEVERE: Failure retrieving count. SQL=SELECT SUM(CNT)  FROM ( SELECT COUNT(DISTINCT LR.LOGICAL_RESOURCE_ID) AS CNT  FROM (SELECT DISTINCT LR.LOGICAL_RESOURCE_ID, LR.LOGICAL_ID, LR.CURRENT_RESOURCE_ID FROM ( SELECT LOGICAL_ID, LOGICAL_RESOURCE_ID, CURRENT_RESOURCE_ID FROM Basic_LOGICAL_RESOURCES ILR WHERE ILR.LOGICAL_ID IN ( ? ))  LR  WHERE  EXISTS (SELECT 1 FROM Resource_STR_VALUES  WHERE (Resource_STR_VALUES .PARAMETER_NAME_ID=40004 AND Resource_STR_VALUES .LOGICAL_RESOURCE_ID = R.LOGICAL_RESOURCE_ID)) WHERE  EXISTS (SELECT 1 FROM Resource_TOKEN_VALUES  WHERE (Resource_TOKEN_VALUES .PARAMETER_NAME_ID=40002 AND Resource_TOKEN_VALUES .LOGICAL_RESOURCE_ID = R.LOGICAL_RESOURCE_ID))) AS LR  JOIN ( SELECT * FROM Basic_RESOURCES IR WHERE ((LAST_UPDATED = ?))) AS R  ON      R.LOGICAL_RESOURCE_ID = LR.LOGICAL_RESOURCE_ID  AND R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID  AND R.IS_DELETED <> 'Y' UNION ALL  SELECT COUNT(DISTINCT LR.LOGICAL_RESOURCE_ID) AS CNT  FROM (SELECT DISTINCT LR.LOGICAL_RESOURCE_ID, LR.LOGICAL_ID, LR.CURRENT_RESOURCE_ID FROM ( SELECT LOGICAL_ID, LOGICAL_RESOURCE_ID, CURRENT_RESOURCE_ID FROM Composition_LOGICAL_RESOURCES ILR WHERE ILR.LOGICAL_ID IN ( ? ))  LR  WHERE  EXISTS (SELECT 1 FROM Resource_STR_VALUES  WHERE (Resource_STR_VALUES .PARAMETER_NAME_ID=40004 AND Resource_STR_VALUES .LOGICAL_RESOURCE_ID = R.LOGICAL_RESOURCE_ID)) WHERE  EXISTS (SELECT 1 FROM Resource_TOKEN_VALUES  WHERE (Resource_TOKEN_VALUES .PARAMETER_NAME_ID=40002 AND Resource_TOKEN_VALUES .LOGICAL_RESOURCE_ID = R.LOGICAL_RESOURCE_ID))) AS LR  JOIN ( SELECT * FROM Composition_RESOURCES IR WHERE ((LAST_UPDATED = ?))) AS R  ON      R.LOGICAL_RESOURCE_ID = LR.LOGICAL_RESOURCE_ID  AND R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID  AND R.IS_DELETED <> 'Y') COMBINED_RESULTS
  searchArgs=[173ee5f86fd-411ada0a-437e-471a-993d-f7d0b15eddb5, 2020-08-14 15:08:27.059479, 173ee5f86fd-411ada0a-437e-471a-993d-f7d0b15eddb5, 2020-08-14 15:08:27.059479] [probeId=7f-0-0-1-ee897ed8-f01b-45c3-9b27-1d17e544df16]
java.sql.SQLSyntaxErrorException: Syntax error: Encountered "WHERE" at line 1, column 472.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at com.ibm.fhir.database.utils.pool.PooledConnection.prepareStatement(PooledConnection.java:413)
	at com.ibm.fhir.persistence.jdbc.dao.impl.FHIRDbDAOImpl.runCountQuery(FHIRDbDAOImpl.java:255)
	at com.ibm.fhir.persistence.jdbc.dao.impl.ResourceDAOImpl.searchCount(ResourceDAOImpl.java:307)
	at com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl.search(FHIRPersistenceJDBCImpl.java:550)
	at com.ibm.fhir.persistence.test.common.AbstractPersistenceTest.runQueryTest(AbstractPersistenceTest.java:175)
	at com.ibm.fhir.persistence.test.common.AbstractPersistenceTest.runQueryTest(AbstractPersistenceTest.java:146)
	at com.ibm.fhir.persistence.test.common.AbstractPersistenceTest.runQueryTest(AbstractPersistenceTest.java:142)
	at com.ibm.fhir.persistence.search.test.AbstractWholeSystemSearchTest.testSearchAllUsingIdAndLastUpdatedAndAnyTagOrProfile(AbstractWholeSystemSearchTest.java:284)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: ERROR 42X01: Syntax error: Encountered "WHERE" at line 1, column 472.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatementOrSearchCondition(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	... 38 more
```

**To Reproduce**
Add the following test to AbstractWholeSystemSearchTest:
```java
    @Test
    public void testSearchAllUsingIdAndLastUpdatedAndAnyTagOrProfile() throws Exception {
        Map<String, List<String>> queryParms = new HashMap<String, List<String>>();
        List<String> savedId = Collections.singletonList(savedResource.getId());

        String dateTime = savedResource.getMeta().getLastUpdated().getValue().toString();
        List<String> savedLastUpdated = Collections.singletonList(dateTime);
        List<String> falseString = Collections.singletonList("false");
        queryParms.put("_id", savedId);
        queryParms.put("_lastUpdated", savedLastUpdated);
        queryParms.put("_tag:missing", falseString);
        queryParms.put("_profile:missing", falseString);

        if (DEBUG) {
            generateOutput(savedResource);
        }

        List<Resource> resources = runQueryTest(Resource.class, queryParms);
        assertNotNull(resources);
        assertEquals(resources.size(), 1, "Number of resources returned");
        assertTrue(isResourceInResponse(savedResource, resources), "Expected resource not found in the response");
    }
```

**Expected behavior**
Either the seach returns successfully or we document that its not supported and get a good error back.

**Additional context**
See `QuerySegmentAggregator.buildSystemLevelQuery`

**Comment by lmsurpre** [comment]
I cleaned up the error response in https://github.com/IBM/FHIR/pull/1416, added the limitation to the docs, and added this to the scope of feature request #473

**Comment by kmbarton423** [comment]
Verified the following behavior on cloud tenant:
"version": "4.4.0",
"name": "IBM FHIR Server",
"status": "active",
"date": "2020-08-24T18:02:12.529Z",
"publisher": "IBM Corporation",
"description": "IBM FHIR Server version 4.4.0 build id development"

GET {{base}}{{contextRoot}}Resource?_id:missing=true

{
    "resourceType": "OperationOutcome",
    "id": "ac-1e-ce-12-bc069c79-e4fa-48fb-a650-f922507da4eb",
    "issue": [
        {
            "severity": "fatal",
            "code": "not-supported",
            "_code": {
                "extension": [
                    {
                        "url": "http://ibm.com/fhir/extension/not-supported-detail",
                        "valueCode": "interaction"
                    }
                ]
            },
            "details": {
                "text": "Modifier 'MISSING' is not yet supported for whole-system search [code=_id]"
            }
        }
    ]
}
