### ISSUE TITLE
Private Memory on Db2 results in -930 errors at load

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#1527]
**Describe the bug**
Private Memory on Db2 results in -930 errors at load

Further, the package cache and catalog cache runs out of space in a shared memory environment. 

**To Reproduce**
1. Go to create an instance of db2 in a shared environment such as IBM Cloud
2. Run a synthetic load with multiple bundles

```
[err] com.ibm.db2.jcc.am.SqlException: DB2 SQL Error: SQLCODE=-930, SQLSTATE=57011, SQLERRMC=null, DRIVER=4.26.14
[err] 	at com.ibm.db2.jcc.am.b7.a(b7.java:815)
[err] 	at com.ibm.db2.jcc.am.b7.a(b7.java:66)
[err] 	at com.ibm.db2.jcc.am.b7.a(b7.java:140)
[err] 	at com.ibm.db2.jcc.am.k4.b(k4.java:2471)
[err] 	at com.ibm.db2.jcc.am.k4.c(k4.java:2452)
[err] 	at com.ibm.db2.jcc.t4.ab.n(ab.java:914)
[err] 	at com.ibm.db2.jcc.t4.ab.f(ab.java:156)
[err] 	at com.ibm.db2.jcc.t4.p.e(p.java:81)
[err] 	at com.ibm.db2.jcc.t4.av.k(av.java:175)
[err] 	at com.ibm.db2.jcc.am.k4.ao(k4.java:2413)
[err] 	at com.ibm.db2.jcc.am.k5.a(k5.java:4686)
[err] 	at com.ibm.db2.jcc.am.CallableStatement.b(CallableStatement.java:134)
[err] 	at com.ibm.db2.jcc.am.CallableStatement.a(CallableStatement.java:103)
[err] 	at com.ibm.db2.jcc.am.CallableStatement.execute(CallableStatement.java:93)
[err] 	at com.ibm.ws.rsadapter.jdbc.WSJdbcPreparedStatement.execute(WSJdbcPreparedStatement.java:390)
[err] 	at com.ibm.fhir.persistence.jdbc.dao.impl.ResourceDAOImpl.insert(ResourceDAOImpl.java:528)
[err] 	at com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl.create(FHIRPersistenceJDBCImpl.java:332)
[err] 	at com.ibm.fhir.server.util.FHIRRestHelper.doCreate(FHIRRestHelper.java:218)
[err] 	at com.ibm.fhir.server.util.FHIRRestHelper.processEntriesForMethod(FHIRRestHelper.java:1781)
[err] 	at com.ibm.fhir.server.util.FHIRRestHelper.processBundleEntries(FHIRRestHelper.java:1475)
[err] 	at com.ibm.fhir.server.util.FHIRRestHelper.doBundle(FHIRRestHelper.java:1068)
[err] 	at com.ibm.fhir.server.resources.Batch.bundle(Batch.java:77)
[err] 	at com.ibm.fhir.server.resources.Batch$Proxy$_$$_WeldClientProxy.bundle(Unknown Source)
[err] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[err] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[err] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[err] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[err] 	at com.ibm.ws.jaxrs20.cdi.component.JaxRsFactoryImplicitBeanCDICustomizer.serviceInvoke(JaxRsFactoryImplicitBeanCDICustomizer.java:339)
[err] 	at [internal classes]
[err] 	at com.ibm.fhir.server.filter.rest.FHIRRestServletFilter.doFilter(FHIRRestServletFilter.java:139)
[err] 	at javax.servlet.http.HttpFilter.doFilter(HttpFilter.java:127)
[err] 	at [internal classes]
[err] 	at com.ibm.fhir.server.filter.rest.FHIRRestAuthorizationServletFilter.doFilter(FHIRRestAuthorizationServletFilter.java:86)
[err] 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
[err] 	at [internal classes]
[err] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[err] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[err] 	at java.base/java.lang.Thread.run(Thread.java:836)
[ERROR   ] SQLException encountered while inserting Resource.
DB2 SQL Error: SQLCODE=-930, SQLSTATE=57011, SQLERRMC=null, DRIVER=4.26.14
```

**Expected behavior**
Solution
- `SELECT * FROM SYSIBMADM.DBCFG WHERE NAME='pckcachesz';`
- `CALL SYSPROC.ADMIN_CMD ('update db cfg for bludb using pckcachesz 25000 AUTOMATIC');`
- `SELECT * FROM SYSIBMADM.DBCFG WHERE NAME='pckcachesz';`

- SELECT * FROM SYSIBMADM.DBCFG WHERE NAME='catalogcache_sz';
- CALL SYSPROC.ADMIN_CMD ('update db cfg for bludb using catalogcache_sz 3000');
- SELECT * FROM SYSIBMADM.DBCFG WHERE NAME='catalogcache_sz';

You must restart the appserver after the change.

**Additional context**
Debugged in IBM Cloud

**Comment by prb112** [comment]
Solution defined, need to review approach with Teammembers.

**Comment by lmsurpre** [comment]
Copying robin's proposal from the PR discussion:
> Proposed solution: Limit the stored procedure to 1MB (to keep the memory requirements low). If the data payload is small (<1MB) then pass it to the procedure. If the payload is large, pass NULL to the procedure, and simply execute an UPDATE to the resources right after. This way, we keep the benefit of fewer round-trips to the database for the majority of cases, but aren't limiting our payload size due to the stored proc memory restrictions.
