### ISSUE TITLE
Occasional crash on server startup

### ISSUE THREAD

**Issue by elsalant** [IBM/FHIR#157]
**Describe the bug**
Occasionally upon server startup the follow error is encountered.  It seems to go away if more time between server shutdown and startup is given:

[AUDIT   ] CWWKT0016I: Web application available (default_host): https://9f85390dd73a:9443/fhir-openapi/
[AUDIT   ] CWWKZ0001I: Application fhir-openapi started in 1.886 seconds.
[ERROR   ] CWWKZ0002E: An exception occurred while starting the application fhir-bulkimportexport-webapp. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DefinitionException: Exception List with 1 exceptions:
Exception 0 :
java.lang.RuntimeException: javax.naming.NameAlreadyBoundException: com
	at com.sun.jersey.server.impl.cdi.CDIExtension.initialize(CDIExtension.java:196)
	at com.sun.jersey.server.impl.cdi.CDIExtension.beforeBeanDiscovery(CDIExtension.java:297)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
	at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:187)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
	at org.jboss.weld.util.Observers.notify(Observers.java:166)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:171)
	at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53)
	at org.jboss.weld.bootstrap.events.AbstractDefinitionContainerEvent.fire(AbstractDefinitionContainerEvent.java:44)
	at org.jboss.weld.bootstrap.events.BeforeBeanDiscoveryImpl.fire(BeforeBeanDiscoveryImpl.java:54)
	at org.jboss.weld.bootstrap.WeldStartup.startInitialization(WeldStartup.java:407)
	at org.jboss.weld.bootstrap.WeldBootstrap.startInitialization(WeldBootstrap.java:79)
	at com.ibm.ws.cdi.impl.CDIContainerImpl$2.run(CDIContainerImpl.java:149)
	at com.ibm.ws.cdi.impl.CDIContainerImpl$2.run(CDIContainerImpl.java:146)
	at java.security.AccessController.doPrivileged(AccessController.java:678)
	at com.ibm.ws.cdi.impl.CDIContainerImpl.startInitialization(CDIContainerImpl.java:146)
	at com.ibm.ws.cdi.liberty.CDIRuntimeImpl.applicationStarting(CDIRuntimeImpl.java:448)
	at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStarting(ApplicationStateManager.java:51)
	at com.ibm.ws.container.service.state.internal.StateChangeServiceImpl.fireApplicationStarting(StateChangeServiceImpl.java:50)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.preDeployApp(SimpleDeployedAppInfoBase.java:550)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:511)
	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:347)
	at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
	at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:140)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1266)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:881)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:818)
Caused by: javax.naming.NameAlreadyBoundException: com
	at com.ibm.ws.jndi.internal.ContextNode.createSubcontext(ContextNode.java:136)
	at com.ibm.ws.jndi.internal.WSContext.createSubcontext(WSContext.java:245)
	at com.ibm.ws.jndi.WSContextBase.createSubcontext(WSContextBase.java:141)
	at org.apache.aries.jndi.DelegateContext.createSubcontext(DelegateContext.java:111)
	at javax.naming.InitialContext.createSubcontext(InitialContext.java:500)
	at com.sun.jersey.server.impl.cdi.CDIExtension$1.stepInto(CDIExtension.java:280)
	at com.sun.jersey.server.impl.cdi.CDIExtension.diveIntoJNDIContext(CDIExtension.java:267)
	at com.sun.jersey.server.impl.cdi.CDIExtension.createJerseyConfigJNDIContext(CDIExtension.java:273)
	at com.sun.jersey.server.impl.cdi.CDIExtension.initialize(CDIExtension.java:192)
	... 40 more

[AUDIT   ] CWWKT0016I: Web application available (default_host): https://9f85390dd73a:9443/fhir-server/api/v4/
[err] log4j:WARN No appenders could be found for logger (org.apache.cxf.common.logging.LogUtils).
[err] log4j:WARN Please initialize the log4j system properly.
[err] log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[WARNING ] [ONCE] Create tablespace not supported in Derby
[WARNING ] [ONCE] Derby does support not multi-tenancy: SUBSTANCENUCLEICACID_STR_VALUES
[ERROR   ] Encountered an exception while bootstrapping the FHIR database
java.sql.SQLException: Table/View 'SUBSTANCENUCLEICACID_STR_VALUES' already exists in Schema 'APP'.
[AUDIT   ] CWWKZ0001I: Application fhir-server-webapp started in 29.948 seconds.
[AUDIT   ] CWWKF0012I: The server installed the following features: [appSecurity-2.0, batch-1.0, batchManagement-1.0, cdi-2.0, distributedMap-1.0, el-3.0, federatedRegistry-1.0, jaxb-2.2, jaxrs-2.1, jaxrsClient-2.1, jdbc-4.1, jndi-1.0, jsf-2.3, json-1.0, jsonp-1.1, jsp-2.3, ldapRegistry-3.0, localConnector-1.0, mpConfig-1.2, mpOpenAPI-1.0, oauth-2.0, openidConnectServer-1.0, servlet-4.0, ssl-1.0, transportSecurity-1.0, websocket-1.1].

**To Reproduce**
Sporadic problem

**Expected behavior**

**Additional context**

**Comment by prb112** [comment]
@elsalant can you share your server.xml? Please note it has passwords, please remove those before putting / uploading.  you can also ping the server.xml to @lmsurpre  or pbastide@us.ibm.com.

**Comment by elsalant** [comment]
Nothing special here - I just replaced the default password for the user 
registry for user name fhiruser, and added an additional user, fhiruser1.
No other changes...

Regards, Eliot


===================================
Eliot Salant

IBM Haifa Research Labs
Haifa University, Mt. Carmel, Haifa, Israel
31905

Tel.    +972-48296-121
FAX:  +972-48296-113
====================================

**Comment by prb112** [comment]
HI @elsalant 

please add to your server.xml the trace specification for JNDI. (add a logging node or append to the traceSpecification). 
```
<logging traceSpecification="*=info:Naming=all:NamingService=all" traceFormat="BASIC"/>
```

When you notice this occurring again?  Please share the trace.log. 

Take care 

Paul

**Comment by elsalant** [comment]
Okay, I got this error again.  Here is the trace.log file
Regards, Eliot
[trace.log](https://github.com/IBM/FHIR/files/3695766/trace.log)

**Comment by elsalant** [comment]
Closed by mistake...

**Comment by prb112** [comment]
OK.  I see what's happening.  It doesn't fully make sense as to why.  What libraries are your custom persistence libraries injecting? 

`mvn dependency:tree -f <path-to-pom> `

it shouldn't be injecting `com/sun/jersey/config`

**Comment by elsalant** [comment]
I have a *lot* of persistence libraries...
Regarding jersey, these include:
jersey-client-1.9.jar
jersey-client-2.22.2.jar
jersey-common-2.22.2.jar
jersey-container-servlet-2.22.2.jar
jersey-container-servlet-core-2.22.2.jar
jersey-core-1.9.jar
jersey-guava-2.22.2.jar
jersey-guice-1.9.jar
jersey-json-1.9.jar
jersey-media-jaxb-2.22.2.jar
jersey-server-1.9.jar
jersey-server-2.22.2.jar

Thanks, Eliot

**Comment by elsalant** [comment]
Interestingly, this error is now consistently happening when I try running the server with my persistence libraries from a Docker container

**Comment by prb112** [comment]
can you provide the dependency tree? it'll help me tell you how to setup exclusions. You have three Jax-RS libraries competing and registering ( in particular your jersey libraries are conflicting).  This common happens with Hadoop / HBase dependencies as they are embedded in a Web Application. 

P.S. Feel free to ping me your pom.xml internally. 

> OK. I see what's happening. It doesn't fully make sense as to why. What libraries are your custom persistence libraries injecting?
> 
> `mvn dependency:tree -f <path-to-pom> `
> 
> it shouldn't be injecting `com/sun/jersey/config`

**Comment by prb112** [comment]
Eliot added `<cdi12 enableImplicitBeanArchives="false"></cdi12>` which seems to have gotten by the core issue (avoiding the multiple discovered jndi entries for Jaxrs)

**Comment by prb112** [comment]
Working with Eliot and Lee we've reached a few conclusions: 

**Problem**
1 - Hadoop and other libraries are known to package Jersey dependencies.  These dependencies introduce into the environment a Jersey framework. 
2 - The IBM FHIR Server webapp uses PARENT_FIRST as a class loader policy, as such, the Jersey framework in the Hadoop libraries in the userlib container (as bundled in a uber jar), contains Jersey. 
3 - The IBM FHIR Server uses a different implementation of JaxRS, the one that is bundled with the OpenLiberty projects as a feature. 
4 - CDI is automatically enabled in the J2EE profile in OpenLiberty, as such, the environment discovers Jersey's JNDI declarations are overrides the IBM FHIR Servers. 
5 - The CDI leaves the IBM FHIR Server in an inconsistent state and may result in a crash (depending on the discovery classpath). 

To solve this problem, add the `<cdi12 enableImplicitBeanArchives="false"></cdi12>` to the server.xml

**Comment by prb112** [comment]
Closing per agreement with Eliot
