### ISSUE TITLE
IllegalArgumentException while verifying download url for bulk export tests in CI

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1755]
**Describe the bug**
During our CI build, I hit the following exception:
```
2020-11-30T20:33:22.6818955Z [ERROR] testBaseExport(com.ibm.fhir.server.test.bulkdata.ExportOperationTest)  Time elapsed: 11.375 s  <<< FAILURE!
2020-11-30T20:33:22.6822050Z java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Illegal character in query at index 121: https://localhost:9000/minio/download/fhirbulkdata/5hMObzd+I9R_c__Ud91ihCqzdsNTyozrJeARYbDNTes=/Patient_1.ndjson?token=pc":"2.0
2020-11-30T20:33:22.6825579Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.verifyDownloadUrl(ExportOperationTest.java:208)
2020-11-30T20:33:22.6829065Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.checkExportStatus(ExportOperationTest.java:248)
2020-11-30T20:33:22.6832500Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.testBaseExport(ExportOperationTest.java:455)
2020-11-30T20:33:22.6835563Z Caused by: java.lang.IllegalArgumentException: Illegal character in query at index 121: https://localhost:9000/minio/download/fhirbulkdata/5hMObzd+I9R_c__Ud91ihCqzdsNTyozrJeARYbDNTes=/Patient_1.ndjson?token=pc":"2.0
2020-11-30T20:33:22.6838728Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.verifyDownloadUrl(ExportOperationTest.java:208)
2020-11-30T20:33:22.6842224Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.checkExportStatus(ExportOperationTest.java:248)
2020-11-30T20:33:22.6845682Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.testBaseExport(ExportOperationTest.java:455)
2020-11-30T20:33:22.6848633Z Caused by: java.net.URISyntaxException: Illegal character in query at index 121: https://localhost:9000/minio/download/fhirbulkdata/5hMObzd+I9R_c__Ud91ihCqzdsNTyozrJeARYbDNTes=/Patient_1.ndjson?token=pc":"2.0
2020-11-30T20:33:22.6851663Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.verifyDownloadUrl(ExportOperationTest.java:208)
2020-11-30T20:33:22.6855223Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.checkExportStatus(ExportOperationTest.java:248)
2020-11-30T20:33:22.6858651Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.testBaseExport(ExportOperationTest.java:455)
2020-11-30T20:33:22.6860377Z 
2020-11-30T20:33:22.6861701Z [ERROR] testGroupExport(com.ibm.fhir.server.test.bulkdata.ExportOperationTest)  Time elapsed: 14.546 s  <<< FAILURE!
2020-11-30T20:33:22.6864612Z java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Illegal character in query at index 125: https://localhost:9000/minio/download/fhirbulkdata/x7PFzn2pV_TnAJg0gMaiEoDqL1Ogoeii4d_sxRVFZO4=/Observation_1.ndjson?token=pc":"2.0
2020-11-30T20:33:22.6868067Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.verifyDownloadUrl(ExportOperationTest.java:208)
2020-11-30T20:33:22.6871754Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.checkGroupExportStatus(ExportOperationTest.java:637)
2020-11-30T20:33:22.6875386Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.testGroupExport(ExportOperationTest.java:561)
2020-11-30T20:33:22.6878480Z Caused by: java.lang.IllegalArgumentException: Illegal character in query at index 125: https://localhost:9000/minio/download/fhirbulkdata/x7PFzn2pV_TnAJg0gMaiEoDqL1Ogoeii4d_sxRVFZO4=/Observation_1.ndjson?token=pc":"2.0
2020-11-30T20:33:22.6881626Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.verifyDownloadUrl(ExportOperationTest.java:208)
2020-11-30T20:33:22.6885741Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.checkGroupExportStatus(ExportOperationTest.java:637)
2020-11-30T20:33:22.6889472Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.testGroupExport(ExportOperationTest.java:561)
2020-11-30T20:33:22.6892429Z Caused by: java.net.URISyntaxException: Illegal character in query at index 125: https://localhost:9000/minio/download/fhirbulkdata/x7PFzn2pV_TnAJg0gMaiEoDqL1Ogoeii4d_sxRVFZO4=/Observation_1.ndjson?token=pc":"2.0
2020-11-30T20:33:22.6895658Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.verifyDownloadUrl(ExportOperationTest.java:208)
2020-11-30T20:33:22.6899339Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.checkGroupExportStatus(ExportOperationTest.java:637)
2020-11-30T20:33:22.6902977Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.testGroupExport(ExportOperationTest.java:561)
2020-11-30T20:33:22.6904718Z 
2020-11-30T20:33:22.6906106Z [ERROR] testPatientExport(com.ibm.fhir.server.test.bulkdata.ExportOperationTest)  Time elapsed: 11.629 s  <<< FAILURE!
2020-11-30T20:33:22.6909310Z java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Illegal character in query at index 121: https://localhost:9000/minio/download/fhirbulkdata/bQlQlHxrOalIeHOca8UIYgY6yuKgSKCZ64OWzbW9rbE=/Patient_1.ndjson?token=pc":"2.0
2020-11-30T20:33:22.6913045Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.verifyDownloadUrl(ExportOperationTest.java:208)
2020-11-30T20:33:22.6916519Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.checkExportStatus(ExportOperationTest.java:248)
2020-11-30T20:33:22.6920039Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.testPatientExport(ExportOperationTest.java:515)
2020-11-30T20:33:22.6923454Z Caused by: java.lang.IllegalArgumentException: Illegal character in query at index 121: https://localhost:9000/minio/download/fhirbulkdata/bQlQlHxrOalIeHOca8UIYgY6yuKgSKCZ64OWzbW9rbE=/Patient_1.ndjson?token=pc":"2.0
2020-11-30T20:33:22.6926854Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.verifyDownloadUrl(ExportOperationTest.java:208)
2020-11-30T20:33:22.6930332Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.checkExportStatus(ExportOperationTest.java:248)
2020-11-30T20:33:22.6933840Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.testPatientExport(ExportOperationTest.java:515)
2020-11-30T20:33:22.6937197Z Caused by: java.net.URISyntaxException: Illegal character in query at index 121: https://localhost:9000/minio/download/fhirbulkdata/bQlQlHxrOalIeHOca8UIYgY6yuKgSKCZ64OWzbW9rbE=/Patient_1.ndjson?token=pc":"2.0
2020-11-30T20:33:22.6940474Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.verifyDownloadUrl(ExportOperationTest.java:208)
2020-11-30T20:33:22.6943965Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.checkExportStatus(ExportOperationTest.java:248)
2020-11-30T20:33:22.6947512Z 	at com.ibm.fhir.server.test.bulkdata.ExportOperationTest.testPatientExport(ExportOperationTest.java:515)
2020-11-30T20:33:22.6949338Z 
2020-11-30T20:33:22.6949668Z [INFO] 
2020-11-30T20:33:22.6950061Z [INFO] Results:
2020-11-30T20:33:22.6950436Z [INFO] 
2020-11-30T20:33:22.6950817Z [ERROR] Failures: 
2020-11-30T20:33:22.6952488Z [ERROR]   ExportOperationTest.testBaseExport:455->checkExportStatus:248->verifyDownloadUrl:208 » IllegalArgument
2020-11-30T20:33:22.6954738Z [ERROR]   ExportOperationTest.testGroupExport:561->checkGroupExportStatus:637->verifyDownloadUrl:208 » IllegalArgument
2020-11-30T20:33:22.6957053Z [ERROR]   ExportOperationTest.testPatientExport:515->checkExportStatus:248->verifyDownloadUrl:208 » IllegalArgument
2020-11-30T20:33:22.6958252Z [INFO] 
2020-11-30T20:33:22.6958768Z [ERROR] Tests run: 697, Failures: 3, Errors: 0, Skipped: 0
```

**To Reproduce**
1. Run the CI build many times until it fails

**Expected behavior**
It should never generate a downloadUrl which is not valid

**Additional context**
I thought we had logic to replace invalid chars like `/` that might be generated when we encode the job id for the object key...not sure if this one is similar or not...needs investigation.

**Comment by lmsurpre** [comment]
This might be related to https://github.com/IBM/FHIR/pull/1735 which was recently merged...but I'm not sure why it would have passed there and failed here...
