### ISSUE TITLE
Confusing error when request is targetted for an invalid tenant id

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#1792]
**Describe the bug**
Requests for an invalid tenant are coming back with a response like this:
```
{"resourceType":"OperationOutcome","id":"c0-a8-1-da-7c8d79ec-4bc3-4d6b-940b-d755e1bb4f24","issue":[{"severity":"fatal","code":"exception","details":{"text":"FHIRPersistenceException: fhirServer/persistence/factoryClassname is configured incorrectly"}}]}
```

**To Reproduce**
1. deploy the server with the default connfig
2. make a request with a header like `X-FHIR-TENANT-ID: dummy`

**Expected behavior**
The request should come back with a clear error message that states that the tenant wasn't valid

**Additional context**
In #639 we decided that all tenants should have their own datasources (and should never "fall back" to the default one).
Based on this, we should be able to check for the presence of a tenant up front (based on the existence of the corresponding tenant config directory).  Maybe we should put it right in the FHIRRestServletFilter?

**Comment by prb112** [comment]
> **Describe the bug**
> Requests for an invalid tenant are coming back with a response like this:
> 
> ```
> {"resourceType":"OperationOutcome","id":"c0-a8-1-da-7c8d79ec-4bc3-4d6b-940b-d755e1bb4f24","issue":[{"severity":"fatal","code":"exception","details":{"text":"FHIRPersistenceException: fhirServer/persistence/factoryClassname is configured incorrectly"}}]}
> ```
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. deploy the server with the default connfig
> 
>     2. make a request with a header like `X-FHIR-TENANT-ID: dummy`
> 
> 
> **Expected behavior**
> The request should come back with a clear error message that states that the tenant wasn't valid
> 
> **Additional context**
> In #639 we decided that all tenants should have their own datasources (and should never "fall back" to the default one).
> Based on this, we should be able to check for the presence of a tenant up front (based on the existence of the corresponding tenant config directory). Maybe we should put it right in the FHIRRestServletFilter?

I hit a similar issue with an old derby db in place

```
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
Caused by: com.ibm.fhir.persistence.exception.FHIRPersistenceException: Unexpected exception while creating JDBC persistence layer:   [probeId=c0-a8-56-14-550264d1-9a69-4f98-a7db-c1956d072bfe]
	at com.ibm.fhir.persistence.jdbc.FHIRPersistenceJDBCFactory.getInstance(FHIRPersistenceJDBCFactory.java:32)
	at com.ibm.fhir.persistence.helper.FHIRPersistenceHelper.getFHIRPersistenceImplementation(FHIRPersistenceHelper.java:86)
	... 64 more
Caused by: java.lang.IllegalStateException: createCache failed
	at com.ibm.fhir.persistence.jdbc.cache.FHIRPersistenceJDBCTenantCache.getCacheForTenantAndDatasource(FHIRPersistenceJDBCTenantCache.java:41)
	at com.ibm.fhir.persistence.jdbc.FHIRPersistenceJDBCFactory.getInstance(FHIRPersistenceJDBCFactory.java:29)
	... 65 more
```
