### ISSUE TITLE
Invalid SQL object name  `--pool-size` exception when running Docker `fhir-persistence-schema` on PostgreSQL

### ISSUE THREAD

**Issue by holger-stenzhorn** [IBM/FHIR#1797]
**Describe the bug**
When running the Docker `fhir-persistence-schema` on PostgreSQL one gets the exception about an invalid SQL object name  `--pool-size`.

**To Reproduce**
1. Run the following command:
    ```bash
    holger@homer:~$docker run ibmcom/ibm-fhir-schematool:4.5.2 --tool.behavior=onboard --db.type=postgresql --db.host=postgres --db.port=5432 --db.database=fhir --schema.name.fhir=fhirdata --user=fhir --password=change-password
    ```
2. The script runs as expected initially but then hits the following error:
    ```bash
    + /opt/java/openjdk/bin/java -jar /opt/schematool/fhir-persistence-schema-4.5.2-cli.jar --prop db.host=postgres --prop db.port=5432 --prop db.database=fhir --prop user=fhir --prop password=change-password --db-type postgresql --grant-to --pool-size 2
    2020-12-04 22:05:21.741 00000001  SEVERE   com.ibm.fhir.schema.app.Main bad argument
    
    Invalid SQL object name: --pool-size
    java.lang.IllegalArgumentException: Invalid SQL object name: --pool-size
    	at com.ibm.fhir.database.utils.common.DataDefinitionUtil.assertValidName(DataDefinitionUtil.java:152)
    	at com.ibm.fhir.schema.app.Main.parseArgs(Main.java:1137)
    	at com.ibm.fhir.schema.app.Main.main(Main.java:1512)
    Usage: 
    --prop-file path-to-property-file
     * loads the properties from a file
    --schema-name schema-name
     * uses the schema as specified, must be valid.
    --grant-to username
     * uses the user as specified, must be valid.
     * and grants permission to the username
    --add-tenant-key tenant-key
     * adds a tenant-key
    --update-proc
     * updates the stored procedure for a specific tenant
    --check-compatibility
     * checks feature compatibility 
    --drop-admin
     * drops the admin schema 
    --test-tenant tenantName
     * used to test with tenantName
    --tenant-key tenantKey
     * uses the tenant-key in the queries
    --tenant-key-file tenant-key-file-location
     * sets the tenant key file location
    --update-schema
     * deploy or update the schema set by '--schema-name'
    --create-schemas
     * create the database schemas for batch, oauth, and the fhir schema set by '--schema-name'
    --drop-schema-fhir
     * drop the schema set by '--schema-name'
    --drop-schema-batch
     * drop the db schema used by liberty's java-batch feature
    --drop-schema-oauth
     * drop the db schema used by liberty's oauth/openid connect features
    --pool-size poolSize
     * poolsize used with the database actions 
    --prop name=value
     * name=value that is passed in on the commandline  
    --confirm-drop
     * confirms the dropping of a schema
    --allocate-tenant
     * allocates a tenant
    --drop-tenant tenantName
     * (phase 1) drops the tenant given the tenantName
    --drop-detached tenantName
     * (phase 2) drops the detached tenant partition tables given the tenantName
    --delete-tenant-meta tenantName
     * deletes tenant metadata given the tenantName
    --list-tenants
     * fetches list of tenants and current status
    --dry-run 
     * simulates the actions of the actions that change the datastore
    2020-12-04 22:05:21.900 00000001  SEVERE   com.ibm.fhir.schema.app.Main SCHEMA CHANGE: BAD ARGS
    ```
**Expected behavior**
n/a

**Additional context**
n/a

**Comment by prb112** [comment]
You are missing your grant-to in the command

**Comment by prb112** [comment]
I added logic to not grant if the target user isn't specified.

**Comment by prb112** [comment]
Added a test case

**Comment by d0roppe** [comment]
Tested with the latest docker image, and ran the test as described in this issue.  Now the command works.
