### ISSUE TITLE
Do not log full stack trace for a simple 404 not found

### ISSUE THREAD

**Issue by punktilious** [IBM/FHIR#1844]
**Describe the bug**
When requesting a resource which doesn't exist, the FHIR server responds with a 404 not found, but it also logs an exception with a full stack trace. This is not necessary, because the code is behaving as expected.

**Expected behavior**
Return the 404 which is already logged. Do not log the exception/stack trace.

**Comment by prb112** [comment]
I cannot replicate this issue.

1 - Try Getting a Random Resource

```
curl --location --request GET 'https://localhost:9443/fhir-server/api/v4/Patient/AAAAAA' --header 'Authorization: Basic ZmhpcnVzZXI6Y2hhbmdlLXBhc3N3b3Jk' --data-raw '' -k
{"resourceType":"OperationOutcome","id":"c0-a8-56-16-e25f7d41-09a6-4bf1-9dd4-fa35eb2991ce","issue":[{"severity":"fatal","code":"not-found","details":{"text":"Resource 'Patient/AAAAAA' not found."},"expression":["<empty>"]}]}
```

If OK, we close. 

Else can provide more details on the request?

**Comment by prb112** [comment]
Oh - it only shows up in the trace.log

```
[2/8/21, 11:39:59:549 EST] 00000078 FHIRResource  I   Resource 'Patient/AAAAAA' not found.
                                 com.ibm.fhir.persistence.exception.FHIRPersistenceResourceNotFoundException: Resource 'Patient/AAAAAA' not found.  [probeId=c0-a8-56-16-0eef7803-bbfe-40ed-86c2-a1d1bdc6dc11]
	at com.ibm.fhir.server.util.FHIRRestHelper.doRead(FHIRRestHelper.java:766)
	at com.ibm.fhir.server.util.FHIRRestHelper.doRead(FHIRRestHelper.java:699)
	at com.ibm.fhir.server.resources.Read.read(Read.java:76)
	at com.ibm.fhir.server.resources.Read$Proxy$_$$_WeldClientProxy.read(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.ibm.ws.jaxrs20.cdi.component.JaxRsFactoryImplicitBeanCDICustomizer.serviceInvoke(JaxRsFactoryImplicitBeanCDICustomizer.java:339)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:641)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.performInvocation(LibertyJaxRsInvoker.java:160)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.invoke(LibertyJaxRsInvoker.java:273)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:210)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.invoke(LibertyJaxRsInvoker.java:444)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:112)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:61)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:99)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:316)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:123)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:273)
	at com.ibm.ws.jaxrs20.endpoint.AbstractJaxRsWebEndpoint.invoke(AbstractJaxRsWebEndpoint.java:136)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.handleRequest(IBMRestServlet.java:146)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.doGet(IBMRestServlet.java:112)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.service(IBMRestServlet.java:96)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:729)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:426)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:182)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)
	at com.ibm.fhir.server.filter.rest.FHIRRestServletFilter.doFilter(FHIRRestServletFilter.java:142)
	at javax.servlet.http.HttpFilter.doFilter(HttpFilter.java:127)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1001)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1139)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1010)
	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)
	at com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40.handleRequest(CacheServletWrapper40.java:83)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:938)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1134)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:415)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:374)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:546)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:480)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:345)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:316)
	at com.ibm.ws.http.channel.h2internal.H2HttpInboundLinkWrap.ready(H2HttpInboundLinkWrap.java:97)
	at com.ibm.ws.http.channel.h2internal.H2StreamProcessor$Http2Ready.run(H2StreamProcessor.java:1686)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
```

**Comment by punktilious** [comment]
Confirmed that the stack trace no longer appears when set to INFO level, but does when trace is enabled.

```[2/17/21, 14:23:21:517 EST] 00002ca1 com.ibm.fhir.server.filter.rest.FHIRRestServletFilter        I Received request: tenantId:[pgcloud] dsId:[default] user:[fhiruser] method:[GET] uri:[https://localhost:9443/fhir-server/api/v4/Patient/xxx177ac0be60c-03807b9c-6df0-47eb-bd76-668aa14643e0]
[2/17/21, 14:23:21:635 EST] 00002ca1 com.ibm.fhir.persistence.jdbc.impl.CacheTransactionSync      I Transaction failed - afterCompletion(status = 4)
[2/17/21, 14:23:21:636 EST] 00002ca1 com.ibm.fhir.server.resources.FHIRResource                   I Resource 'Patient/xxx177ac0be60c-03807b9c-6df0-47eb-bd76-668aa14643e0' not found.
[2/17/21, 14:23:21:642 EST] 00002ca1 com.ibm.fhir.server.filter.rest.FHIRRestServletFilter        I Completed request[0.125 secs]: tenantId:[pgcloud] dsId:[default] user:[fhiruser] method:[GET] uri:[https://localhost:9443/fhir-server/api/v4/Patient/xxx177ac0be60c-03807b9c-6df0-47eb-bd76-668aa14643e0] status:[404]
```
