### ISSUE TITLE
fhir-client swallows connection exceptions when the request payload is too large

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#193]
**Describe the bug**
FHIRClient errors are not helpful. Here is an example when you try creating a resource on an endpoint that doesn't exist:
```
Oct 04, 2019 1:25:10 PM com.ibm.fhir.provider.FHIRProvider writeTo
WARNING: an error occurred during resource serialization
com.ibm.fhir.model.generator.exception.FHIRGeneratorException: I/O error while writing in JsonGenerator  [probeId=c0-a8-1-4b-c5ab613c-8387-457b-987a-52dae784d4f0]
	at com.ibm.fhir.model.generator.FHIRJsonGenerator.generate(FHIRJsonGenerator.java:76)
	at com.ibm.fhir.provider.FHIRProvider.writeTo(FHIRProvider.java:90)
	at com.ibm.fhir.provider.FHIRProvider.writeTo(FHIRProvider.java:1)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.writeMessageBody(JAXRSUtils.java:1417)
	at org.apache.cxf.jaxrs.client.AbstractClient.writeBody(AbstractClient.java:488)
	at org.apache.cxf.jaxrs.client.WebClient$BodyWriter.doWriteBody(WebClient.java:1175)
	at org.apache.cxf.jaxrs.client.AbstractClient$AbstractBodyWriter.handleMessage(AbstractClient.java:1192)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:685)
	at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1038)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:894)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:862)
	at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:427)
	at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.method(WebClient.java:1566)
	at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.method(WebClient.java:1561)
	at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.post(WebClient.java:1501)
	at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.post(InvocationBuilderImpl.java:145)
	at com.ibm.fhir.client.impl.FHIRClientImpl._bundle(FHIRClientImpl.java:759)
	at com.ibm.fhir.client.impl.FHIRClientImpl.batch(FHIRClientImpl.java:550)
	at com.ibm.watsonhealth.fhir.client.uploader.Main.main(Main.java:51)
Caused by: javax.json.JsonException: I/O error while writing in JsonGenerator
	at org.glassfish.json.JsonGeneratorImpl.flushBuffer(JsonGeneratorImpl.java:635)
	at org.glassfish.json.JsonGeneratorImpl.writeChar(JsonGeneratorImpl.java:599)
	at org.glassfish.json.JsonGeneratorImpl.writeStartObject(JsonGeneratorImpl.java:140)
	at com.ibm.fhir.model.generator.FHIRJsonGenerator$JsonGeneratingVisitor.writeStartObject(FHIRJsonGenerator.java:407)
	at com.ibm.fhir.model.generator.FHIRJsonGenerator$JsonGeneratingVisitor.doVisitStart(FHIRJsonGenerator.java:376)
	at com.ibm.fhir.model.visitor.PathAwareAbstractVisitor.visitStart(PathAwareAbstractVisitor.java:70)
	at com.ibm.fhir.model.resource.Bundle$Entry$Request.accept(Bundle.java:1633)
	at com.ibm.fhir.model.visitor.AbstractVisitable.accept(AbstractVisitable.java:26)
	at com.ibm.fhir.model.resource.Bundle$Entry.accept(Bundle.java:948)
	at com.ibm.fhir.model.visitor.AbstractVisitable.accept(AbstractVisitable.java:36)
	at com.ibm.fhir.model.resource.Bundle.accept(Bundle.java:250)
	at com.ibm.fhir.model.visitor.Visitable.accept(Visitable.java:17)
	at com.ibm.fhir.model.generator.FHIRJsonGenerator.generate(FHIRJsonGenerator.java:73)
	... 19 more
	Suppressed: javax.json.stream.JsonGenerationException: Generating incomplete JSON
		at org.glassfish.json.JsonGeneratorImpl.close(JsonGeneratorImpl.java:511)
		at com.ibm.fhir.model.generator.FHIRJsonGenerator.generate(FHIRJsonGenerator.java:75)
		... 19 more
Caused by: java.io.InterruptedIOException: Output operation aborted
	at org.apache.cxf.transport.http.asyncclient.SharedOutputBuffer.flushContent(SharedOutputBuffer.java:317)
	at org.apache.cxf.transport.http.asyncclient.SharedOutputBuffer.write(SharedOutputBuffer.java:299)
	at org.apache.cxf.transport.http.asyncclient.AsyncHTTPConduit$AsyncWrappedOutputStream$1.write(AsyncHTTPConduit.java:434)
	at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:70)
	at org.apache.cxf.io.AbstractThresholdOutputStream.write(AbstractThresholdOutputStream.java:83)
	at org.apache.cxf.io.CacheAndWriteOutputStream.write(CacheAndWriteOutputStream.java:71)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:77)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:125)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
	at org.glassfish.json.JsonGeneratorImpl.flushBuffer(JsonGeneratorImpl.java:631)
	... 31 more
```

then
```
Oct 04, 2019 1:25:12 PM org.apache.cxf.jaxrs.utils.JAXRSUtils logMessageHandlerProblem
SEVERE: Problem with writing the data, class com.ibm.fhir.model.resource.Bundle, ContentType: application/fhir+json
Oct 04, 2019 1:25:12 PM org.apache.cxf.phase.PhaseInterceptorChain doDefaultLogging
WARNING: Interceptor for {https://127.0.0.1:9443/fhir-server/api/v4/}WebClient has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: Problem with writing the data, class com.ibm.fhir.model.resource.Bundle, ContentType: application/fhir+json
	at org.apache.cxf.jaxrs.client.WebClient$BodyWriter.doWriteBody(WebClient.java:1180)
	at org.apache.cxf.jaxrs.client.AbstractClient$AbstractBodyWriter.handleMessage(AbstractClient.java:1192)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:685)
	at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1038)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:894)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:862)
	at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:427)
	at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.method(WebClient.java:1566)
	at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.method(WebClient.java:1561)
	at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.post(WebClient.java:1501)
	at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.post(InvocationBuilderImpl.java:145)
	at com.ibm.fhir.client.impl.FHIRClientImpl._bundle(FHIRClientImpl.java:759)
	at com.ibm.fhir.client.impl.FHIRClientImpl.batch(FHIRClientImpl.java:550)
	at com.ibm.watsonhealth.fhir.client.uploader.Main.main(Main.java:51)
Caused by: javax.ws.rs.ProcessingException: Problem with writing the data, class com.ibm.fhir.model.resource.Bundle, ContentType: application/fhir+json
	at org.apache.cxf.jaxrs.client.AbstractClient.reportMessageHandlerProblem(AbstractClient.java:828)
	at org.apache.cxf.jaxrs.client.AbstractClient.writeBody(AbstractClient.java:502)
	at org.apache.cxf.jaxrs.client.WebClient$BodyWriter.doWriteBody(WebClient.java:1175)
	... 14 more
Caused by: javax.ws.rs.WebApplicationException: HTTP 400 Bad Request
	at com.ibm.fhir.provider.FHIRProvider.writeTo(FHIRProvider.java:96)
	at com.ibm.fhir.provider.FHIRProvider.writeTo(FHIRProvider.java:1)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.writeMessageBody(JAXRSUtils.java:1417)
	at org.apache.cxf.jaxrs.client.AbstractClient.writeBody(AbstractClient.java:488)
	... 15 more
```

and finally:
```
Exception in thread "main" javax.ws.rs.ProcessingException: Problem with writing the data, class com.ibm.fhir.model.resource.Bundle, ContentType: application/fhir+json
	at org.apache.cxf.jaxrs.client.AbstractClient.reportMessageHandlerProblem(AbstractClient.java:828)
	at org.apache.cxf.jaxrs.client.AbstractClient.writeBody(AbstractClient.java:502)
	at org.apache.cxf.jaxrs.client.WebClient$BodyWriter.doWriteBody(WebClient.java:1175)
	at org.apache.cxf.jaxrs.client.AbstractClient$AbstractBodyWriter.handleMessage(AbstractClient.java:1192)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:685)
	at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1038)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:894)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:862)
	at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:427)
	at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.method(WebClient.java:1566)
	at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.method(WebClient.java:1561)
	at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.post(WebClient.java:1501)
	at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.post(InvocationBuilderImpl.java:145)
	at com.ibm.fhir.client.impl.FHIRClientImpl._bundle(FHIRClientImpl.java:759)
	at com.ibm.fhir.client.impl.FHIRClientImpl.batch(FHIRClientImpl.java:550)
	at com.ibm.watsonhealth.fhir.client.uploader.Main.main(Main.java:51)
Caused by: javax.ws.rs.WebApplicationException: HTTP 400 Bad Request
	at com.ibm.fhir.provider.FHIRProvider.writeTo(FHIRProvider.java:96)
	at com.ibm.fhir.provider.FHIRProvider.writeTo(FHIRProvider.java:1)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.writeMessageBody(JAXRSUtils.java:1417)
	at org.apache.cxf.jaxrs.client.AbstractClient.writeBody(AbstractClient.java:488)
	... 15 more
```

**To Reproduce**
1. Misconfigure the http endpoint of the fhir-client (e.g. in client.properties)
2. Attempt a create or update interaction with a large payload (e.g. a bundle with 100 entries)

**Expected behavior**
The client gives a clear indication of the root cause.

**Additional context**
It looks like connection-level exceptions are being trapped in both `FHIRProvider.readFrom` and `FHIRProvider.writeTo`
Are we doing that on purpose for something on the server side?
From a client perspective, this is not working well.

**Comment by prb112** [comment]
Please consider using a custom Exception with a custom ExceptionMapper<> in JaxRS 
https://github.com/jersey/jersey/tree/master/examples/exception-mapping

This achieves a similar (but different) result

**Comment by lmsurpre** [comment]
sample test class to reproduce the issue:
```java
/*
 * (C) Copyright IBM Corp. 2019
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package com.ibm.watsonhealth.fhir.client.uploader;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Properties;
import java.util.stream.Collectors;

import com.ibm.fhir.client.FHIRClient;
import com.ibm.fhir.client.FHIRResponse;
import com.ibm.fhir.client.impl.FHIRClientImpl;
import com.ibm.fhir.model.format.Format;
import com.ibm.fhir.model.parser.FHIRParser;
import com.ibm.fhir.model.resource.Bundle;
import com.ibm.fhir.model.resource.Resource;

/**
 * simple main to illustrate issue #193
 */
public class Main {
    public static void main(String[] args) throws Exception {
        
        Path path = Paths.get("src/test/resources");
        final FHIRClient client = createClient();
        List<Path> files = Files.list(path)
                                .filter(p -> p.toString().endsWith(".json"))
                                .collect(Collectors.toList());
        for (Path file : files) {
            System.out.println("Processing " + file.getFileName().toString());
            BufferedReader reader = Files.newBufferedReader(file, StandardCharsets.UTF_8);
            Bundle bundle = FHIRParser.parser(Format.JSON).parse(reader);
            
            FHIRResponse response = client.batch(bundle);
            if (!response.isEmpty()) {
                System.out.println(response.getResource(Resource.class));
            }
        }
    }
    
    private static FHIRClient createClient() throws IOException, Exception {
        Properties props = new Properties();
        InputStream propStream = Uploader.class.getResourceAsStream("/client.properties");
        props.load(propStream);
        return new FHIRClientImpl(props);
    }
}
```

I ran this with test.properties pointing to localhost.  And I don't even have a server running there.

**Comment by lmsurpre** [comment]
with the merged changes, the test case stacktrace looks more like this:
```
SEVERE: Problem with writing the data, class com.ibm.fhir.model.resource.Bundle, ContentType: application/fhir+json
Oct 30, 2019 5:23:02 PM org.apache.cxf.phase.PhaseInterceptorChain doDefaultLogging
WARNING: Interceptor for {https://127.0.0.1:9443/fhir-server/api/v1/Bundle}WebClient has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: Problem with writing the data, class com.ibm.fhir.model.resource.Bundle, ContentType: application/fhir+json
	at org.apache.cxf.jaxrs.client.WebClient$BodyWriter.doWriteBody(WebClient.java:1198)
	at org.apache.cxf.jaxrs.client.AbstractClient$AbstractBodyWriter.handleMessage(AbstractClient.java:1241)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:709)
	at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1056)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:902)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:871)
	at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:431)
	at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:150)
	at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:145)
	at org.apache.cxf.jaxrs.client.SyncInvokerImpl.post(SyncInvokerImpl.java:85)
	at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.post(InvocationBuilderImpl.java:153)
	at com.ibm.fhir.client.impl.FHIRClientImpl._create(FHIRClientImpl.java:170)
	at com.ibm.fhir.client.impl.FHIRClientImpl.create(FHIRClientImpl.java:118)
	at com.ibm.watsonhealth.fhir.client.uploader.Main2.main(Main2.java:33)
Caused by: javax.ws.rs.ProcessingException: Problem with writing the data, class com.ibm.fhir.model.resource.Bundle, ContentType: application/fhir+json
	at org.apache.cxf.jaxrs.client.AbstractClient.reportMessageHandlerProblem(AbstractClient.java:852)
	at org.apache.cxf.jaxrs.client.AbstractClient.writeBody(AbstractClient.java:530)
	at org.apache.cxf.jaxrs.client.WebClient$BodyWriter.doWriteBody(WebClient.java:1193)
	... 14 more
Caused by: java.io.IOException: an error occurred during resource serialization
	at com.ibm.fhir.provider.FHIRProvider.writeTo(FHIRProvider.java:108)
	at com.ibm.fhir.provider.FHIRProvider.writeTo(FHIRProvider.java:1)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.writeMessageBody(JAXRSUtils.java:1448)
	at org.apache.cxf.jaxrs.client.AbstractClient.writeBody(AbstractClient.java:516)
	... 15 more
Caused by: com.ibm.fhir.model.generator.exception.FHIRGeneratorException: I/O error while writing in JsonGenerator [Bundle.entry[392].fullUrl]  [probeId=7f-0-0-1-f4c19d70-af76-49f3-8d88-30439b9b36c7]
	at com.ibm.fhir.model.generator.FHIRJsonGenerator.generate(FHIRJsonGenerator.java:76)
	at com.ibm.fhir.provider.FHIRProvider.writeTo(FHIRProvider.java:100)
	... 18 more
Caused by: javax.json.JsonException: I/O error while writing in JsonGenerator
	at org.glassfish.json.JsonGeneratorImpl.flushBuffer(JsonGeneratorImpl.java:635)
	at org.glassfish.json.JsonGeneratorImpl.writeString(JsonGeneratorImpl.java:588)
	at org.glassfish.json.JsonGeneratorImpl.writeEscapedString(JsonGeneratorImpl.java:547)
	at org.glassfish.json.JsonGeneratorImpl.write(JsonGeneratorImpl.java:160)
	at com.ibm.fhir.model.generator.FHIRJsonGenerator$JsonGeneratingVisitor.writeValue(FHIRJsonGenerator.java:434)
	at com.ibm.fhir.model.generator.FHIRJsonGenerator$JsonGeneratingVisitor.visit(FHIRJsonGenerator.java:308)
	at com.ibm.fhir.model.type.Uri.accept(Uri.java:69)
	at com.ibm.fhir.model.visitor.AbstractVisitable.accept(AbstractVisitable.java:26)
	at com.ibm.fhir.model.resource.Bundle$Entry.accept(Bundle.java:961)
	at com.ibm.fhir.model.visitor.AbstractVisitable.accept(AbstractVisitable.java:36)
	at com.ibm.fhir.model.resource.Bundle.accept(Bundle.java:258)
	at com.ibm.fhir.model.visitor.Visitable.accept(Visitable.java:64)
	at com.ibm.fhir.model.generator.FHIRJsonGenerator.generate(FHIRJsonGenerator.java:73)
	... 19 more
	Suppressed: javax.json.stream.JsonGenerationException: Generating incomplete JSON
		at org.glassfish.json.JsonGeneratorImpl.close(JsonGeneratorImpl.java:511)
		at com.ibm.fhir.model.generator.FHIRJsonGenerator.generate(FHIRJsonGenerator.java:75)
		... 19 more
Caused by: java.io.InterruptedIOException: Output operation aborted
	at org.apache.cxf.transport.http.asyncclient.SharedOutputBuffer.flushContent(SharedOutputBuffer.java:317)
	at org.apache.cxf.transport.http.asyncclient.SharedOutputBuffer.write(SharedOutputBuffer.java:299)
	at org.apache.cxf.transport.http.asyncclient.AsyncHTTPConduit$AsyncWrappedOutputStream$1.write(AsyncHTTPConduit.java:454)
	at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:70)
	at org.apache.cxf.io.AbstractThresholdOutputStream.write(AbstractThresholdOutputStream.java:83)
	at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:70)
	at org.apache.cxf.io.CacheAndWriteOutputStream.write(CacheAndWriteOutputStream.java:71)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:77)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:125)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
	at org.glassfish.json.JsonGeneratorImpl.flushBuffer(JsonGeneratorImpl.java:631)
	... 31 more

Oct 30, 2019 5:23:02 PM org.apache.cxf.interceptor.LoggingInInterceptor
INFO: Inbound Message
----------------------------
ID: 1
Address: https://127.0.0.1:9443/fhir-server/api/v1/Bundle
Http-Method: POST
Content-Type: application/fhir+json
Headers: {Accept=[application/fhir+json], Prefer=[return=minimal], Content-Type=[application/fhir+json], Authorization=[Basic ZmhpcnVzZXI6Y2hhbmdlLXBhc3N3b3Jk]}
--------------------------------------
Exception in thread "main" javax.ws.rs.ProcessingException: Problem with writing the data, class com.ibm.fhir.model.resource.Bundle, ContentType: application/fhir+json
	at org.apache.cxf.jaxrs.client.AbstractClient.reportMessageHandlerProblem(AbstractClient.java:852)
	at org.apache.cxf.jaxrs.client.AbstractClient.writeBody(AbstractClient.java:530)
	at org.apache.cxf.jaxrs.client.WebClient$BodyWriter.doWriteBody(WebClient.java:1193)
	at org.apache.cxf.jaxrs.client.AbstractClient$AbstractBodyWriter.handleMessage(AbstractClient.java:1241)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:709)
	at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1056)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:902)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:871)
	at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:431)
	at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:150)
	at org.apache.cxf.jaxrs.client.SyncInvokerImpl.method(SyncInvokerImpl.java:145)
	at org.apache.cxf.jaxrs.client.SyncInvokerImpl.post(SyncInvokerImpl.java:85)
	at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.post(InvocationBuilderImpl.java:153)
	at com.ibm.fhir.client.impl.FHIRClientImpl._create(FHIRClientImpl.java:170)
	at com.ibm.fhir.client.impl.FHIRClientImpl.create(FHIRClientImpl.java:118)
	at com.ibm.watsonhealth.fhir.client.uploader.Main2.main(Main2.java:33)
Caused by: java.io.IOException: an error occurred during resource serialization
	at com.ibm.fhir.provider.FHIRProvider.writeTo(FHIRProvider.java:108)
	at com.ibm.fhir.provider.FHIRProvider.writeTo(FHIRProvider.java:1)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.writeMessageBody(JAXRSUtils.java:1448)
	at org.apache.cxf.jaxrs.client.AbstractClient.writeBody(AbstractClient.java:516)
	... 15 more
Caused by: com.ibm.fhir.model.generator.exception.FHIRGeneratorException: I/O error while writing in JsonGenerator [Bundle.entry[392].fullUrl]  [probeId=7f-0-0-1-f4c19d70-af76-49f3-8d88-30439b9b36c7]
	at com.ibm.fhir.model.generator.FHIRJsonGenerator.generate(FHIRJsonGenerator.java:76)
	at com.ibm.fhir.provider.FHIRProvider.writeTo(FHIRProvider.java:100)
	... 18 more
Caused by: javax.json.JsonException: I/O error while writing in JsonGenerator
	at org.glassfish.json.JsonGeneratorImpl.flushBuffer(JsonGeneratorImpl.java:635)
	at org.glassfish.json.JsonGeneratorImpl.writeString(JsonGeneratorImpl.java:588)
	at org.glassfish.json.JsonGeneratorImpl.writeEscapedString(JsonGeneratorImpl.java:547)
	at org.glassfish.json.JsonGeneratorImpl.write(JsonGeneratorImpl.java:160)
	at com.ibm.fhir.model.generator.FHIRJsonGenerator$JsonGeneratingVisitor.writeValue(FHIRJsonGenerator.java:434)
	at com.ibm.fhir.model.generator.FHIRJsonGenerator$JsonGeneratingVisitor.visit(FHIRJsonGenerator.java:308)
	at com.ibm.fhir.model.type.Uri.accept(Uri.java:69)
	at com.ibm.fhir.model.visitor.AbstractVisitable.accept(AbstractVisitable.java:26)
	at com.ibm.fhir.model.resource.Bundle$Entry.accept(Bundle.java:961)
	at com.ibm.fhir.model.visitor.AbstractVisitable.accept(AbstractVisitable.java:36)
	at com.ibm.fhir.model.resource.Bundle.accept(Bundle.java:258)
	at com.ibm.fhir.model.visitor.Visitable.accept(Visitable.java:64)
	at com.ibm.fhir.model.generator.FHIRJsonGenerator.generate(FHIRJsonGenerator.java:73)
	... 19 more
	Suppressed: javax.json.stream.JsonGenerationException: Generating incomplete JSON
		at org.glassfish.json.JsonGeneratorImpl.close(JsonGeneratorImpl.java:511)
		at com.ibm.fhir.model.generator.FHIRJsonGenerator.generate(FHIRJsonGenerator.java:75)
		... 19 more
Caused by: java.io.InterruptedIOException: Output operation aborted
	at org.apache.cxf.transport.http.asyncclient.SharedOutputBuffer.flushContent(SharedOutputBuffer.java:317)
	at org.apache.cxf.transport.http.asyncclient.SharedOutputBuffer.write(SharedOutputBuffer.java:299)
	at org.apache.cxf.transport.http.asyncclient.AsyncHTTPConduit$AsyncWrappedOutputStream$1.write(AsyncHTTPConduit.java:454)
	at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:70)
	at org.apache.cxf.io.AbstractThresholdOutputStream.write(AbstractThresholdOutputStream.java:83)
	at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:70)
	at org.apache.cxf.io.CacheAndWriteOutputStream.write(CacheAndWriteOutputStream.java:71)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:77)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:125)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
	at org.glassfish.json.JsonGeneratorImpl.flushBuffer(JsonGeneratorImpl.java:631)
	... 31 more
```

**Comment by prb112** [comment]
Closing as the Commits were 26 days ago
