### ISSUE TITLE
Ambiguous dependencies when starting IBM FHIR Server 4.6.0

### ISSUE THREAD

**Issue by tbieste** [IBM/FHIR#1978]
**Describe the bug**
Exceptions about ambiguous dependencies when starting IBM FHIR Server (4.6.0-snapshot).

**To Reproduce**

1. Start Liberty Server (w/ fhir-bulkimportexport-webapp, fhir-openapi, fhir-server-webapp)

2. 14 exceptions similar to the following are shown in the Liberty Console:
```
[ERROR   ] CWWKZ0002E: An exception occurred while starting the application fhir-bulkimportexport-webapp. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DeploymentException: Exception List with 14 exceptions:
Exception 0 :
org.jboss.weld.exceptions.DeploymentException: WELD-001409: Ambiguous dependencies for type String with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject @BatchProperty com.ibm.fhir.jbatch.bulkdata.export.system.ChunkReader.incomingUrl
  at com.ibm.fhir.jbatch.bulkdata.export.system.ChunkReader.incomingUrl(ChunkReader.java:0)
  Possible dependencies: 
  - Producer Method [String] with qualifiers [@Any @Default] declared as [[UnbackedAnnotatedMethod] @Produces @Dependent @ManualTrace @Claim public com.ibm.ws.security.mp.jwt.cdi.ClaimProducer.getString(InjectionPoint)],
  - Producer Method [String] with qualifiers [@Any @Default] declared as [[UnbackedAnnotatedMethod] @Produces @BatchProperty @Dependent public com.ibm.ws.jbatch.cdi.BatchProducerBean.produceProperty(InjectionPoint)]

	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:386)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:290)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:143)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:164)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:526)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:64)
	at org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Expected behavior**
Not expecting to see the exceptions.

**Comment by prb112** [comment]
Refactored the treatment of StepCtx and JobCtx into an Adapter so the injection point conflicts don't occur.

**Comment by tbieste** [comment]
Verified I no longer see the exceptions.
