### ISSUE TITLE
FHIRParserException message should include the path

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#201]
While updating some DSTU2 resources to R4, I hit a few issues where the parser was rejecting the request.  Unfortunately, the error output from my test doesn't include the path that caused the issue:

```
com.ibm.fhir.model.parser.exception.FHIRParserException: Expected: JsonArray but found: STRING  [probeId=9-1b-78-d-0e9c3608-4821-43e8-aa6f-f0be5d04b65a]  [probeId=9-1b-78-d-f549dd93-96c6-4ef1-9185-d3f9fb6c4f3f]
    at com.ibm.fhir.model.parser.FHIRJsonParser.parseAndFilter(FHIRJsonParser.java:76)
    at com.ibm.fhir.model.parser.FHIRJsonParser.parse(FHIRJsonParser.java:68)
    at com.ibm.fhir.persistence.search.test.AbstractPLSearchTest.readResource(AbstractPLSearchTest.java:221)
    at com.ibm.fhir.persistence.search.test.AbstractSearchDateTest.testCreateBasicResource(AbstractSearchDateTest.java:21)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
    at org.testng.TestRunner.privateRun(TestRunner.java:782)
    at org.testng.TestRunner.run(TestRunner.java:632)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
    at org.testng.SuiteRunner.run(SuiteRunner.java:268)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
    at org.testng.TestNG.run(TestNG.java:1064)
    at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: com.ibm.fhir.model.parser.exception.FHIRParserException: Expected: JsonArray but found: STRING  [probeId=9-1b-78-d-0e9c3608-4821-43e8-aa6f-f0be5d04b65a]
    at com.ibm.fhir.model.parser.FHIRJsonParser.parseAndFilter(FHIRJsonParser.java:95)
    at com.ibm.fhir.model.parser.FHIRJsonParser.parseAndFilter(FHIRJsonParser.java:74)
    ... 27 more
Caused by: java.lang.IllegalArgumentException: Expected: JsonArray but found: STRING
    at com.ibm.fhir.model.util.JsonSupport.getJsonValue(JsonSupport.java:121)
    at com.ibm.fhir.model.util.JsonSupport.getJsonArray(JsonSupport.java:95)
    at com.ibm.fhir.model.parser.FHIRJsonParser.parseTimingRepeat(FHIRJsonParser.java:20466)
    at com.ibm.fhir.model.parser.FHIRJsonParser.parseTiming(FHIRJsonParser.java:20427)
    at com.ibm.fhir.model.parser.FHIRJsonParser.parseChoiceElement(FHIRJsonParser.java:21132)
    at com.ibm.fhir.model.parser.FHIRJsonParser.parseExtension(FHIRJsonParser.java:9023)
    at com.ibm.fhir.model.parser.FHIRJsonParser.parseDomainResource(FHIRJsonParser.java:6737)
    at com.ibm.fhir.model.parser.FHIRJsonParser.parseBasic(FHIRJsonParser.java:1238)
    at com.ibm.fhir.model.parser.FHIRJsonParser.parseResource(FHIRJsonParser.java:125)
    at com.ibm.fhir.model.parser.FHIRJsonParser.parseAndFilter(FHIRJsonParser.java:93)
    ... 28 more
```

By debugging, I found that the FHIRParserException *does* have the path, its just not printed out from toString.  Lets add the path to the message so that these errors are easier to find in resources being parsed.

**Comment by lmsurpre** [comment]
Additionally, notice that the probeId is getting appended twice (due to the outer FHIRParserException getting constructed with the message from the inner FHIRParserException that already had a probeId).
