### ISSUE TITLE
Support writing outcomes to file storageProvider and check for a valid outcome target in preflight

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#2083]
**Is your feature request related to a problem? Please describe.**
When I pass an invalid storageProvider via `X-FHIR-BULKDATA-OUTCOME`, it accepts the job and then fails with a confusing error in the joblogs like this:
```
[3/12/21 20:14:36:297 UTC] [step1 partition0] com.ibm.fhir.bulkdata.jbatch.load.ChunkWriter                  Import ChunkWriter.writeItems during job[2]
                                 java.lang.IllegalArgumentException: none
	at com.ibm.fhir.operation.bulkdata.model.type.StorageType.from(StorageType.java:32)
	at com.ibm.fhir.operation.bulkdata.config.impl.AbstractSystemConfigurationImpl.getStorageProviderStorageType(AbstractSystemConfigurationImpl.java:243)
	at com.ibm.fhir.bulkdata.jbatch.load.ChunkWriter.writeItems(ChunkWriter.java:164)
	at com.ibm.jbatch.container.artifact.proxy.ItemWriterProxy.writeItems(ItemWriterProxy.java:80)
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.writeChunk(ChunkStepControllerImpl.java:481)
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.invokeChunk(ChunkStepControllerImpl.java:636)
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.invokeCoreStep(ChunkStepControllerImpl.java:795)
	at com.ibm.jbatch.container.controller.impl.BaseStepControllerImpl.execute(BaseStepControllerImpl.java:295)
	at com.ibm.jbatch.container.controller.impl.ExecutionTransitioner.doExecutionLoop(ExecutionTransitioner.java:118)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeCoreTransitionLoop(WorkUnitThreadControllerImpl.java:96)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeWorkUnit(WorkUnitThreadControllerImpl.java:178)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl$AbstractControllerHelper.runExecutionOnThread(WorkUnitThreadControllerImpl.java:503)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.runExecutionOnThread(WorkUnitThreadControllerImpl.java:92)
	at com.ibm.jbatch.container.util.BatchWorkUnit.run(BatchWorkUnit.java:113)
	at com.ibm.ws.context.service.serializable.ContextualRunnable.run(ContextualRunnable.java:79)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Describe the solution you'd like**
1. Support storing outcomes to a file-based storageProvider
2. Check the requested outcome target is valid in preflight

**Describe alternatives you've considered**
Continue to only support writing OperationOutcomes to COS/S3.

**Acceptance Criteria**
1.  
   GIVEN [a precondition]
    AND [another precondition]
   WHEN [test step]
    AND [test step]
   THEN [verification step]
    AND [verification step]

**Additional context**

**Comment by lmsurpre** [comment]
One additional thing we could consider cleaning up.  Currently, when writing outcomes is disabled, our job-status endpoint response for a completed `$import` looks like this:
```
{
    "transactionTime": "2021-03-12T21:56:49.835Z",
    "request": "$import",
    "requiresAccessToken": false
}
```

The `requiresAccessToken` field doesn't make much sense when there's no outcomes to download.  Maybe we just omit it in this case?

**Comment by lmsurpre** [comment]
I'm not sure it warrants its own issue, but another thing we could check preflight (at least in the FileProvider case) is that the input files exist and are readable.  We should still execute the import if any 1 of the import urls are valid, but this way we can avoid passing invalid urls to the batch framework, and avoid the job altogether if there are none.

**Comment by lmsurpre** [comment]
Could be done together with #1161
