### ISSUE TITLE
Everything Operation doesn't respond correctly to deleted resources

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#2133]
**Describe the bug**

```
[err] com.ibm.fhir.persistence.exception.FHIRPersistenceResourceDeletedException: Resource 'Patient/1785fb0759b-1452d2e5-f568-442e-9841-3dc3940af5bc' is deleted.  [probeId=c0-a8-56-16-10c0cae7-6437-45fa-b414-835a9e0aba57]
[err] 	at com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl.read(FHIRPersistenceJDBCImpl.java:961)
[err] 	at com.ibm.fhir.server.util.FHIRRestHelper.doRead(FHIRRestHelper.java:778)
[err] 	at com.ibm.fhir.server.util.FHIRRestHelper.doRead(FHIRRestHelper.java:713)
[err] 	at com.ibm.fhir.server.util.FHIRRestHelper.doRead(FHIRRestHelper.java:706)
[err] 	at com.ibm.fhir.operation.everything.EverythingOperation.doInvoke(EverythingOperation.java:167)
[err] 	at com.ibm.fhir.server.operation.spi.AbstractOperation.invoke(AbstractOperation.java:59)
[err] 	at com.ibm.fhir.server.util.FHIRRestHelper.doInvoke(FHIRRestHelper.java:1119)
[err] 	at com.ibm.fhir.server.resources.Operation.invoke(Operation.java:326)
[err] 	at com.ibm.fhir.server.resources.Operation$Proxy$_$$_WeldClientProxy.invoke(Unknown Source)
[err] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[err] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[err] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[err] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[err] 	at com.ibm.ws.jaxrs20.cdi.component.JaxRsFactoryImplicitBeanCDICustomizer.serviceInvoke(JaxRsFactoryImplicitBeanCDICustomizer.java:342)
[err] 	at [internal classes]
[err] 	at com.ibm.fhir.server.filter.rest.FHIRRestServletFilter.doFilter(FHIRRestServletFilter.java:142)
[err] 	at javax.servlet.http.HttpFilter.doFilter(HttpFilter.java:127)
[err] 	at [internal classes]
[err] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[err] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[err] 	at java.base/java.lang.Thread.run(Thread.java:836)
[ERROR   ] An unexpected error occurred while reading patient '1785fb0759b-1452d2e5-f568-442e-9841-3dc3940af5bc'
An unexpected error occurred while reading patient '1785fb0759b-1452d2e5-f568-442e-9841-3dc3940af5bc'
```

**To Reproduce**
1. Create a patient
2. Delete a Patient
3. curl --location --request GET 'https://localhost:9443/fhir-server/api/v4/Patient/1785fb0759b-1452d2e5-f568-442e-9841-3dc3940af5bc/$everything' \
--header 'Content-Type: application/fhir+json' \
--header 'Authorization: Basic ...'

**Expected behavior**
Should not throw an exception finding the patient. 

**Additional context**
Related https://github.com/IBM/FHIR/issues/1044

**Comment by tbieste** [comment]
Tested this locally with latest code from main branch and no exception occurs in this scenario.
