### ISSUE TITLE
GraphTermServiceProvider should be more resilient to missing display names

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#2179]
**Is your feature request related to a problem? Please describe.**
After a botched import, I had term content in the graph with no display name.  This resulted in runtime errors like the following:
```
[2021-03-30T21:33:08.978+0000] 00000020 FHIRResource  E   An error occurred during the CodeSystem lookup operation
                                 com.ibm.fhir.exception.FHIROperationException: An error occurred during the CodeSystem lookup operation  [probeId=7f-0-0-1-a6a2c6c3-d13f-4937-9ea7-79c93c9f4a5c]
	at com.ibm.fhir.operation.term.LookupOperation.doInvoke(LookupOperation.java:52)
	at com.ibm.fhir.server.operation.spi.AbstractOperation.invoke(AbstractOperation.java:56)
	at com.ibm.fhir.server.util.FHIRRestHelper.doInvoke(FHIRRestHelper.java:1119)
	at com.ibm.fhir.server.resources.Operation.invoke(Operation.java:212)
	...
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: ele-1: All FHIR elements must have a @value or children
	at com.ibm.fhir.model.util.ValidationSupport.requireValueOrChildren(ValidationSupport.java:378)
	at com.ibm.fhir.model.type.String.<init>(String.java:30)
	at com.ibm.fhir.model.type.String$Builder.build(String.java:197)
	at com.ibm.fhir.model.type.String.string(String.java:58)
	at com.ibm.fhir.term.graph.provider.GraphTermServiceProvider.createConcept(GraphTermServiceProvider.java:558)
	at com.ibm.fhir.term.graph.provider.GraphTermServiceProvider.createConcept(GraphTermServiceProvider.java:546)
	at com.ibm.fhir.term.graph.provider.GraphTermServiceProvider.getConcept(GraphTermServiceProvider.java:601)
	at com.ibm.fhir.term.graph.provider.GraphTermServiceProvider.getConcept(GraphTermServiceProvider.java:122)
	at com.ibm.fhir.term.service.FHIRTermService.lookup(FHIRTermService.java:289)
	at com.ibm.fhir.operation.term.LookupOperation.doInvoke(LookupOperation.java:48)
	... 59 more
```

**Describe the solution you'd like**
Be more resilient to missing display codes.

**Describe alternatives you've considered**

**Acceptance Criteria**

**Additional context**
John mentioned that the lookup operation is already resilient to missing display values:
```
                    return LookupOutcome.builder()
                            .name((codeSystem.getName() != null) ? codeSystem.getName() : STRING_DATA_ABSENT_REASON_UNKNOWN)
                            .version(codeSystem.getVersion())
                            .display((concept.getDisplay() != null) ? concept.getDisplay() : STRING_DATA_ABSENT_REASON_UNKNOWN)
                            .property(concept.getProperty().stream()
                                .map(property -> Property.builder()
                                    .code(property.getCode())
                                    .value(property.getValue())
                                    .build())
                                .collect(Collectors.toList()))
                            .designation(concept.getDesignation().stream()
                                .map(designation -> Designation.builder()
                                    .language(designation.getLanguage())
                                    .use(designation.getUse())
                                    .value(designation.getValue())
                                    .build())
                                .collect(Collectors.toList()))
                            .build();
```

so I think we should just be more resilient in the GraphTermServiceProvider

**Comment by JohnTimm** [comment]
`GraphTermServiceProvider` is making some assumptions about what's in the graph. We can put in some logic to ensure that we don't attempt to set a display value if it isn't in the elementMap.
