### ISSUE TITLE
Failed to create MedicinalProductUndesirableEffect resource if using DB2

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#221]
When running REST performance test, if DB2 is configured for the test tenant, then server always return 500 server error when creating MedicinalProductUndesirableEffect resource. and the exception in message.log is as following:

   [ERROR   ] SQLException encountered while inserting Resource.  [probeId=c0-a8-1-be-c3fed89f-e2d6-4cab-9f7b-70efaa0d1e4a]
com.ibm.db2.jcc.am.SqlDataException: DB2 SQL Error: SQLCODE=-302, SQLSTATE=22001, SQLERRMC=null, DRIVER=4.25.1301
	at com.ibm.db2.jcc.am.b6.a(b6.java:802)
	at com.ibm.db2.jcc.am.b6.a(b6.java:66)
	at com.ibm.db2.jcc.am.b6.a(b6.java:140)
	at com.ibm.db2.jcc.am.k3.b(k3.java:2471)
	at com.ibm.db2.jcc.am.k3.c(k3.java:2452)
	at com.ibm.db2.jcc.t4.ab.n(ab.java:914)
	at com.ibm.db2.jcc.t4.ab.f(ab.java:156)
	at com.ibm.db2.jcc.t4.p.e(p.java:81)
	at com.ibm.db2.jcc.t4.av.k(av.java:175)
	at com.ibm.db2.jcc.am.k3.ao(k3.java:2413)
	at com.ibm.db2.jcc.am.k4.a(k4.java:4686)
	at com.ibm.db2.jcc.am.k4.b(k4.java:4182)
	at com.ibm.db2.jcc.am.k4.a(k4.java:4827)
	at com.ibm.db2.jcc.am.CallableStatement.b(CallableStatement.java:134)
	at com.ibm.db2.jcc.am.CallableStatement.a(CallableStatement.java:103)
	at com.ibm.db2.jcc.am.CallableStatement.execute(CallableStatement.java:93)
	at com.ibm.ws.rsadapter.jdbc.WSJdbcPreparedStatement.execute(WSJdbcPreparedStatement.java:391)
	at com.ibm.fhir.persistence.jdbc.dao.impl.ResourceDAONormalizedImpl.insertToDb2(ResourceDAONormalizedImpl.java:724)
	at com.ibm.fhir.persistence.jdbc.dao.impl.ResourceDAONormalizedImpl.insert(ResourceDAONormalizedImpl.java:638)
	at com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCNormalizedImpl.create(FHIRPersistenceJDBCNormalizedImpl.java:224)
	at com.ibm.fhir.server.resources.FHIRResource.doCreate(FHIRResource.java:1141)
	at com.ibm.fhir.server.resources.FHIRResource.create(FHIRResource.java:258)

**Comment by prb112** [comment]
is it one of these resources? 

```
./fhir-examples/src/main/resources/xml/spec/medicinalproductundesirableeffect-example.xml
./fhir-examples/src/main/resources/xml/spec/medicinalproductundesirableeffect.profile.xml
./fhir-examples/src/main/resources/xml/ibm/complete-absent/MedicinalProductUndesirableEffect-1.xml
./fhir-examples/src/main/resources/xml/ibm/complete-mock/MedicinalProductUndesirableEffect-1.xml
./fhir-examples/src/main/resources/xml/ibm/minimal/MedicinalProductUndesirableEffect-1.xml
./fhir-examples/src/main/resources/json/spec/medicinalproductundesirableeffect-questionnaire.json
./fhir-examples/src/main/resources/json/spec/medicinalproductundesirableeffect-example.json
./fhir-examples/src/main/resources/json/spec/medicinalproductundesirableeffect.profile.json
./fhir-examples/src/main/resources/json/ibm/complete-absent/MedicinalProductUndesirableEffect-1.json
./fhir-examples/src/main/resources/json/ibm/complete-mock/MedicinalProductUndesirableEffect-1.json
./fhir-examples/src/main/resources/json/ibm/minimal/MedicinalProductUndesirableEffect-1.json
```

**Comment by albertwang-ibm** [comment]
The root cause:
    (1) the length of resourcetype parameter of the add_any_resource store procedure is 32, but the resourcetype name for MedicinalProductUndesirableEffect is 33 instead. 
    (2) the exception that the codes throw is not appropriate and very misleading, we should use the more generic FHIRPersistenceDataAccessException instead of SQLIntegrityConstraintViolationException which has already been caught previously in above codes.
