### ISSUE TITLE
fhir-bucket: Drive Reindex Operation thread should exit after error

### ISSUE THREAD

**Issue by cpschult** [IBM/FHIR#2219]
**Describe the bug**
The tool to drive reindex operations may become 'hung' and not exit when client threads don't handle an exception when attempting to access FHIR server.  This creates a situation where the application will not exit. This presents a difficult situation for long running reindex jobs because there is no indication there was an error accessing the FHIR server. 

**Environment**
release-4.6.1 running in kubernetes cluster

**To Reproduce**
1. Install release 4.6.1
2. Start `kubectl port forward` to allow access to FHIR server in Kubernetes cluster.
3. Start reindex job to update schema indexes.
3. Wait for `kubectl port forward` to fail.
4. The reindex job will print exception information but will not exit.

**Expected behavior**
DriveReindexOperation should exit if a connection exception occurs to notify the caller of the connection problem so it can be fixed and the reindex process can be restarted.

**Proposed Solution**
I created a PR here #2225 .
~Catch `DataAccessException` in `callReindexOperation` and invoke `signalStop` to allow `monitorLoop` thread to exit. If one thread receives `DataAccessException` I expect all will and all pool threads will exit.~

**Additional context**

**Comment by cpschult** [comment]
Solution proposed in PR #2225 .

**Comment by prb112** [comment]
> Solution proposed in PR #2225 .

assigned the review to @punktilious

**Comment by cpschult** [comment]
Tested with 4.7.0-SNAPSHOT jar built from main this morning.  Log below shows new behavior when network connectivity is cut during reindex processing.

```
➜  FHIR git:(main) ✗ echo $JAR
fhir-bucket/target/fhir-bucket-4.7.0-SNAPSHOT-cli.jar
➜  FHIR git:(main) ✗ java -jar "${JAR}" --tenant-name $MY_TENANT  --max-concurrent-fhir-requests 100 --no-scan --reindex-tstamp 2021-03-30T00:00:00Z --reindex-resource-count 100 --reindex-concurrent-requests 3 --fhir-properties $FHIR_SERVER_PROPERTIES
Apr 12, 2021 1:10:47 PM com.ibm.fhir.bucket.reindex.DriveReindexOperation init
INFO: Starting monitor thread
Apr 12, 2021 1:10:47 PM com.ibm.fhir.bucket.reindex.DriveReindexOperation monitorLoop
INFO: monitor probe - checking reindex operation
Apr 12, 2021 1:10:59 PM com.ibm.fhir.bucket.reindex.DriveReindexOperation callOnce
INFO: called $reindex: 200 OK [took 12.318 s]
Apr 12, 2021 1:10:59 PM com.ibm.fhir.bucket.reindex.DriveReindexOperation monitorLoop
INFO: Test probe successful - filling worker pool
Apr 12, 2021 1:11:14 PM com.ibm.fhir.bucket.reindex.DriveReindexOperation callOnce
INFO: called $reindex: 200 OK [took 13.555 s]
Apr 12, 2021 1:11:14 PM com.ibm.fhir.bucket.reindex.DriveReindexOperation callOnce
INFO: called $reindex: 200 OK [took 14.732 s]
Apr 12, 2021 1:11:17 PM com.ibm.fhir.bucket.reindex.DriveReindexOperation callOnce
INFO: called $reindex: 200 OK [took 15.279 s]
Apr 12, 2021 1:11:22 PM com.ibm.fhir.bucket.reindex.DriveReindexOperation callOnce
INFO: called $reindex: 200 OK [took 8.309 s]

ACTION: manually stop kubectl port forward process

Apr 12, 2021 1:11:23 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://localhost:9442: The target server failed to respond
Apr 12, 2021 1:11:23 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://localhost:9442: The target server failed to respond
Apr 12, 2021 1:11:23 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {s}->https://localhost:9442: The target server failed to respond
Apr 12, 2021 1:11:23 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://localhost:9442
Apr 12, 2021 1:11:23 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://localhost:9442
Apr 12, 2021 1:11:23 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://localhost:9442
Apr 12, 2021 1:11:24 PM com.ibm.fhir.bucket.client.FHIRBucketClient post
SEVERE: Error while executing the POST request. org.apache.http.conn.HttpHostConnectException: Connect to localhost:9442 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
Apr 12, 2021 1:11:24 PM com.ibm.fhir.bucket.client.FHIRBucketClient post
SEVERE: Error while executing the POST request. org.apache.http.conn.HttpHostConnectException: Connect to localhost:9442 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
Apr 12, 2021 1:11:24 PM com.ibm.fhir.bucket.client.FHIRBucketClient post
WARNING: POST URL: https://localhost:9442/fhir-server/api/v4/$reindex
Request Body: {"resourceType":"Parameters","parameter":[{"name":"tstamp","valueString":"2021-03-30T00:00:00Z"},{"name":"resourceCount","valueInteger":100}]}
Apr 12, 2021 1:11:24 PM com.ibm.fhir.bucket.client.FHIRBucketClient post
SEVERE: Error while executing the POST request. org.apache.http.conn.HttpHostConnectException: Connect to localhost:9442 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
Apr 12, 2021 1:11:24 PM com.ibm.fhir.bucket.client.FHIRBucketClient post
WARNING: POST URL: https://localhost:9442/fhir-server/api/v4/$reindex
Request Body: {"resourceType":"Parameters","parameter":[{"name":"tstamp","valueString":"2021-03-30T00:00:00Z"},{"name":"resourceCount","valueInteger":100}]}
Apr 12, 2021 1:11:24 PM com.ibm.fhir.bucket.reindex.DriveReindexOperation callReindexOperation
SEVERE: DataAccessException caught when contacting FHIR server. FHIR client thread will exit.com.ibm.fhir.database.utils.api.DataAccessException: FHIR server connection failed
Apr 12, 2021 1:11:24 PM com.ibm.fhir.bucket.client.FHIRBucketClient post
WARNING: POST URL: https://localhost:9442/fhir-server/api/v4/$reindex
Request Body: {"resourceType":"Parameters","parameter":[{"name":"tstamp","valueString":"2021-03-30T00:00:00Z"},{"name":"resourceCount","valueInteger":100}]}
Apr 12, 2021 1:11:24 PM com.ibm.fhir.bucket.reindex.DriveReindexOperation callReindexOperation
SEVERE: DataAccessException caught when contacting FHIR server. FHIR client thread will exit.com.ibm.fhir.database.utils.api.DataAccessException: FHIR server connection failed
Apr 12, 2021 1:11:24 PM com.ibm.fhir.bucket.reindex.DriveReindexOperation callReindexOperation
SEVERE: DataAccessException caught when contacting FHIR server. FHIR client thread will exit.com.ibm.fhir.database.utils.api.DataAccessException: FHIR server connection failed
Apr 12, 2021 1:11:27 PM com.ibm.fhir.bucket.reindex.DriveReindexOperation monitorLoop
INFO: monitor probe - checking reindex operation

NOTE: monitorLoop now recognizes thread pool is empty and running=False. It will now attempt a trial request, fail, and exit.

Apr 12, 2021 1:11:28 PM com.ibm.fhir.bucket.client.FHIRBucketClient post
SEVERE: Error while executing the POST request. org.apache.http.conn.HttpHostConnectException: Connect to localhost:9442 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
Apr 12, 2021 1:11:28 PM com.ibm.fhir.bucket.client.FHIRBucketClient post
WARNING: POST URL: https://localhost:9442/fhir-server/api/v4/$reindex
Request Body: {"resourceType":"Parameters","parameter":[{"name":"tstamp","valueString":"2021-03-30T00:00:00Z"},{"name":"resourceCount","valueInteger":100}]}
Exception in thread "Thread-1" com.ibm.fhir.database.utils.api.DataAccessException: FHIR server connection failed
        at com.ibm.fhir.bucket.client.FHIRBucketClient.post(FHIRBucketClient.java:314)
        at com.ibm.fhir.bucket.reindex.DriveReindexOperation.callOnce(DriveReindexOperation.java:235)
        at com.ibm.fhir.bucket.reindex.DriveReindexOperation.monitorLoop(DriveReindexOperation.java:122)
        at com.ibm.fhir.bucket.reindex.DriveReindexOperation.lambda$init$0(DriveReindexOperation.java:106)
        at java.base/java.lang.Thread.run(Thread.java:834)

NOTE:  I don't know why there is a one minute delay before the program exits.  But it does eventually exit.

Apr 12, 2021 1:12:24 PM com.ibm.fhir.bucket.app.Main shutdown
INFO: Stopping all services
```
