### ISSUE TITLE
Unexpected IllegalArgumentException --schema-name 'TEST1' argument does not match tenant schema: 'TEST1   '

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#2352]
**Describe the bug**

**Environment**
Which version of IBM FHIR Server?
off of the main branch 4.8.0-SNAPSHOT

**To Reproduce**
1. Create a [Db2 instance](https://hub.docker.com/r/ibmcom/db2)

``` sh
mkdir -p db
docker run -itd --name mydb2_1631 --rm --privileged=true -p 50000:50000 -e LICENSE=accept -e DB2INST1_PASSWORD=change-password -e DBNAME=fhirdb -v $(pwd)/db:/database ibmcom/db2:11.5.4.0
```

2. Configure the Db2 instance. 

``` sh
docker exec -it mydb2_1631 /bin/bash
su - db2inst1
/opt/ibm/db2/V11.5/bin/db2 CREATE DB FHIRDB using codeset UTF-8 territory us PAGESIZE 32768
```

Optionally, you may need to drop the db `/opt/ibm/db2/V11.5/bin/db2 drop db fhirdb`.

3. Build Main `mvn clean install -f fhir-parent -DskipTests`

4. Create Schemas

``` sh 
java -jar ~/.m2/repository/com/ibm/fhir/fhir-persistence-schema/4.8.0-SNAPSHOT/fhir-persistence-schema-4.8.0-SNAPSHOT-cli.jar \
    --prop db.host=localhost --prop db.port=50000 --prop db.database=fhirdb --prop user=db2inst1 --prop password=change-password \
    --db-type db2 --schema-name 'TEST1' --create-schemas
```

5. Update Schema

``` sh 
java -jar ~/.m2/repository/com/ibm/fhir/fhir-persistence-schema/4.8.0-SNAPSHOT/fhir-persistence-schema-4.8.0-SNAPSHOT-cli.jar \
    --prop db.host=localhost --prop db.port=50000 --prop db.database=fhirdb --prop user=db2inst1 --prop password=change-password \
    --db-type db2 --schema-name 'TEST1' --update-schema
```

6. Allocate Tenant1 with TEST1

``` sh 
java -jar ~/.m2/repository/com/ibm/fhir/fhir-persistence-schema/4.8.0-SNAPSHOT/fhir-persistence-schema-4.8.0-SNAPSHOT-cli.jar \
    --prop db.host=localhost --prop db.port=50000 --prop db.database=fhirdb --prop user=db2inst1 --prop password=change-password \
    --db-type db2 --schema-name 'TEST1' --allocate-tenant test1c
```

7. Allocate Tenant2 with TEST1

``` sh 
java -jar ~/.m2/repository/com/ibm/fhir/fhir-persistence-schema/4.8.0-SNAPSHOT/fhir-persistence-schema-4.8.0-SNAPSHOT-cli.jar \
    --prop db.host=localhost --prop db.port=50000 --prop db.database=fhirdb --prop user=db2inst1 --prop password=change-password \
    --db-type db2 --schema-name 'TEST1' --allocate-tenant test1d
```

8. Drop the second tenant test1d

``` sh 
java -jar ~/.m2/repository/com/ibm/fhir/fhir-persistence-schema/4.8.0-SNAPSHOT/fhir-persistence-schema-4.8.0-SNAPSHOT-cli.jar \
    --prop db.host=localhost --prop db.port=50000 --prop db.database=fhirdb --prop user=db2inst1 --prop password=change-password \
    --db-type db2 --schema-name 'TEST1' --drop-tenant test1d
```

Results in 
```
2021-05-12 11:30:33.965 00000001  SEVERE   com.ibm.fhir.schema.app.Main bad argument
--schema-name 'TEST1' argument does not match tenant schema: 'TEST1   '
java.lang.IllegalArgumentException: --schema-name 'TEST1' argument does not match tenant schema: 'TEST1   '
        at com.ibm.fhir.schema.app.Main.getTenantInfo(Main.java:1011)
        at com.ibm.fhir.schema.app.Main.freezeTenant(Main.java:1030)
        at com.ibm.fhir.schema.app.Main.dropTenant(Main.java:1094)
        at com.ibm.fhir.schema.app.Main.process(Main.java:1803)
        at com.ibm.fhir.schema.app.Main.main(Main.java:1860)
```

**Expected behavior**
The value should be usable to get the tenant, howeve rit comes back padded with extra spaces.

**Additional context**
Confirming #1631 on db2

**Comment by prb112** [comment]
One additional note, I did start with a lower case test1 that was unquoted.

**Comment by prb112** [comment]
Confirmed.
