### ISSUE TITLE
Empty Schema and Missing version Table results in Exception for list-tenants

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#2353]
**Describe the bug**
Empty Schema and Tenants Table results in Exception for list-tenants

**Environment**
Which version of IBM FHIR Server?
`main` and `4.8.0-SNAPSHOT`

**To Reproduce**
1. Create a [Db2 instance](https://hub.docker.com/r/ibmcom/db2)

``` sh
mkdir -p db
docker run -itd --name mydb2_1631 --rm --privileged=true -p 50000:50000 -e LICENSE=accept -e DB2INST1_PASSWORD=change-password -e DBNAME=fhirdb -v $(pwd)/db:/database ibmcom/db2:11.5.4.0
```

2. Configure the Db2 instance. 

``` sh
docker exec -it mydb2_1631 /bin/bash
su - db2inst1
/opt/ibm/db2/V11.5/bin/db2 CREATE DB FHIRDB using codeset UTF-8 territory us PAGESIZE 32768
```

Optionally, you may need to drop the db `/opt/ibm/db2/V11.5/bin/db2 drop db fhirdb`.

3. Build Main `mvn clean install -f fhir-parent -DskipTests`

4. Create Schemas

``` sh 
java -jar ~/.m2/repository/com/ibm/fhir/fhir-persistence-schema/4.8.0-SNAPSHOT/fhir-persistence-schema-4.8.0-SNAPSHOT-cli.jar \
    --prop db.host=localhost --prop db.port=50000 --prop db.database=fhirdb --prop user=db2inst1 --prop password=change-password \
    --db-type db2 --schema-name test1 --create-schemas
```

5. list Tenants

```
java -jar ~/.m2/repository/com/ibm/fhir/fhir-persistence-schema/4.8.0-SNAPSHOT/fhir-persistence-schema-4.8.0-SNAPSHOT-cli.jar     --prop db.host=localhost --prop db.port=50000 --prop db.database=fhirdb --prop user=db2inst1 --prop password=change-password     --db-type db2 --schema-name test1 --list-tenants
2021-05-12 11:54:14.833 00000001    INFO .common.JdbcConnectionProvider Opening connection to database: jdbc:db2://localhost:50000/fhirdb
2021-05-12 11:54:16.064 00000001 WARNING ls.pool.PoolConnectionProvider Get connection took 1.230 seconds
2021-05-12 11:54:16.124 00000001 WARNING ls.pool.PoolConnectionProvider Rolling back transaction
2021-05-12 11:54:16.130 00000001  SEVERE   com.ibm.fhir.schema.app.Main schema tool failed

com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=FHIR_ADMIN.TENANTS, DRIVER=4.28.11
com.ibm.fhir.database.utils.api.UndefinedNameException: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=FHIR_ADMIN.TENANTS, DRIVER=4.28.11
        at com.ibm.fhir.database.utils.db2.Db2Translator.translate(Db2Translator.java:111)
        at com.ibm.fhir.schema.control.GetTenantList.run(GetTenantList.java:64)
        at com.ibm.fhir.schema.control.GetTenantList.run(GetTenantList.java:23)
        at com.ibm.fhir.database.utils.common.CommonDatabaseAdapter.runStatement(CommonDatabaseAdapter.java:475)
        at com.ibm.fhir.schema.app.Main.listTenants(Main.java:901)
        at com.ibm.fhir.schema.app.Main.process(Main.java:1789)
        at com.ibm.fhir.schema.app.Main.main(Main.java:1860)
Caused by: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704, SQLERRMC=FHIR_ADMIN.TENANTS, DRIVER=4.28.11
        at com.ibm.db2.jcc.am.b7.a(b7.java:810)
        at com.ibm.db2.jcc.am.b7.a(b7.java:66)
        at com.ibm.db2.jcc.am.b7.a(b7.java:140)
        at com.ibm.db2.jcc.am.k6.c(k6.java:2825)
        at com.ibm.db2.jcc.am.k6.d(k6.java:2809)
        at com.ibm.db2.jcc.am.k6.a(k6.java:2235)
        at com.ibm.db2.jcc.t4.ab.i(ab.java:204)
        at com.ibm.db2.jcc.t4.ab.b(ab.java:94)
        at com.ibm.db2.jcc.t4.p.a(p.java:32)
        at com.ibm.db2.jcc.t4.av.i(av.java:150)
        at com.ibm.db2.jcc.am.k6.al(k6.java:2204)
        at com.ibm.db2.jcc.am.k6.a(k6.java:3331)
        at com.ibm.db2.jcc.am.k6.a(k6.java:738)
        at com.ibm.db2.jcc.am.k6.executeQuery(k6.java:717)
        at com.ibm.fhir.schema.control.GetTenantList.run(GetTenantList.java:54)
        ... 5 more
2021-05-12 11:54:16.133 00000001  SEVERE   com.ibm.fhir.schema.app.Main SCHEMA CHANGE: RUNTIME ERROR
```

**Expected behavior**
n/a

**Additional context**
n/a

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/2358 
FIxes the Exception above (on top of the issue fixed by troy)

**Comment by prb112** [comment]
```
