### ISSUE TITLE
FetchResourcePayloadsDAO hits an error condition under debug without _since parameter

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#2391]
**Describe the bug**
FetchResourcePayloadsDAO hits an error condition under debug without _since parameter

```
[5/19/21, 19:43:47:460 UTC] 0000005e com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl   E Unexpected error while processing token value records.
java.lang.NullPointerException
    at java.sql.Timestamp.from(Timestamp.java:545)
    at com.ibm.fhir.persistence.jdbc.dao.impl.FetchResourcePayloadsDAO.count(FetchResourcePayloadsDAO.java:184)
    at com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl.fetchResourcePayloads(FHIRPersistenceJDBCImpl.java:2652)
    at com.ibm.fhir.bulkdata.jbatch.export.fast.ResourcePayloadReader.readItem(ResourcePayloadReader.java:307)
    at com.ibm.jbatch.container.artifact.proxy.ItemReaderProxy.readItem(ItemReaderProxy.java:77)
    at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.readItem(ChunkStepControllerImpl.java:329)
    at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.readAndProcess(ChunkStepControllerImpl.java:245)
    at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.invokeChunk(ChunkStepControllerImpl.java:626)
    at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.invokeCoreStep(ChunkStepControllerImpl.java:795)
    at com.ibm.jbatch.container.controller.impl.BaseStepControllerImpl.execute(BaseStepControllerImpl.java:295)
    at com.ibm.jbatch.container.controller.impl.ExecutionTransitioner.doExecutionLoop(ExecutionTransitioner.java:118)
    at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeCoreTransitionLoop(WorkUnitThreadControllerImpl.java:96)
    at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeWorkUnit(WorkUnitThreadControllerImpl.java:178)
    at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl$AbstractControllerHelper.runExecutionOnThread(WorkUnitThreadControllerImpl.java:503)
    at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.runExecutionOnThread(WorkUnitThreadControllerImpl.java:92)
    at com.ibm.jbatch.container.util.BatchWorkUnit.run(BatchWorkUnit.java:113)
    at com.ibm.ws.context.service.serializable.ContextualRunnable.run(ContextualRunnable.java:79)
    at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:836)
```

**Environment**
Which version of IBM FHIR Server?
4.8.0

**To Reproduce**
Create export using FAST implementation. 

**Expected behavior**

**Additional context**

**Comment by d0roppe** [comment]
Ran several tests with "finest" for logging, and did not see any issue with the bulk data commands.
