### ISSUE TITLE
$import  Exit Status on Matrixed Resources results in NPE

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#2479]
**Describe the bug**
$import Exit Status on Matrixed Resources results in NPE

[6/7/21, 16:50:20:919 UTC] com.ibm.ws.batch.JobLogger                                     CWWKY0034I: An exception occurred while running the final portion of the job.
com.ibm.jbatch.container.exception.BatchContainerRuntimeException: java.lang.NullPointerException
	at com.ibm.jbatch.container.artifact.proxy.JobListenerProxy.afterJob(JobListenerProxy.java:35)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.jobListenersAfterJob(WorkUnitThreadControllerImpl.java:450)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.endOfWorkUnit(WorkUnitThreadControllerImpl.java:259)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeWorkUnit(WorkUnitThreadControllerImpl.java:210)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl$AbstractControllerHelper.runExecutionOnThread(WorkUnitThreadControllerImpl.java:503)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.runExecutionOnThread(WorkUnitThreadControllerImpl.java:92)
	at com.ibm.jbatch.container.util.BatchWorkUnit.run(BatchWorkUnit.java:113)
	at com.ibm.ws.context.service.serializable.ContextualRunnable.run(ContextualRunnable.java:79)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
Caused by: java.lang.NullPointerException
	at com.ibm.fhir.bulkdata.jbatch.load.listener.ExitStatus.generateResultExitStatus(ExitStatus.java:65)
	at com.ibm.fhir.bulkdata.jbatch.load.ImportJobListener.afterJob(ImportJobListener.java:88)
	at com.ibm.jbatch.container.artifact.proxy.JobListenerProxy.afterJob(JobListenerProxy.java:33)
	... 13 more

**Environment**
Which version of IBM FHIR Server?

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by d0roppe** [comment]
Verified the issue with the _seg0, 1, and 2 on a file in the main bucket and also in a folder. works fine.
