### ISSUE TITLE
Support for search queries that do not include timezone

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#258]
**Stretch Goal** 

We need to refactor the Parameter model in fhir-search such that it can handle partial date/time values with AND without timezones. Java 8 time library should be able to handle this:

- Year
- YearMondh
- LocalDate
- LocalDateTime
- ZonedDateTime
- LocalTime
- OffsetTime

They are all Temporal instances.

**Steps** 
- Use DATE_TIMEFORMATTER in the Model to parse
- ParameterValue should use TemporalAccessor and not our fhir-model DateTime.
- uncomment the corresponding test in AbstractSearchDateTest.testSearchDate_date

Stack Trace: 
```
com.ibm.fhir.search.exception.FHIRSearchException: An error occurred while parsing search parameter 'date'.  [probeId=9-1b-78-d-bd10c40d-ea46-4c7d-b806-fca27fbd91d4]
	at com.ibm.fhir.search.exception.SearchExceptionUtil.buildNewParseParameterException(SearchExceptionUtil.java:67)
	at com.ibm.fhir.search.util.SearchUtil.parseQueryParameters(SearchUtil.java:617)
	at com.ibm.fhir.search.util.SearchUtil.parseQueryParameters(SearchUtil.java:523)
	at com.ibm.fhir.persistence.test.common.AbstractPersistenceTest.runQueryTest(AbstractPersistenceTest.java:126)
	at com.ibm.fhir.persistence.test.common.AbstractPersistenceTest.runQueryTest(AbstractPersistenceTest.java:114)
	at com.ibm.fhir.persistence.search.test.AbstractPLSearchTest.searchReturnsResource(AbstractPLSearchTest.java:134)
	at com.ibm.fhir.persistence.search.test.AbstractPLSearchTest.assertSearchReturnsSavedResource(AbstractPLSearchTest.java:117)
	at com.ibm.fhir.persistence.search.test.AbstractSearchDateTest.testSearchDate_date(AbstractSearchDateTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.time.format.DateTimeParseException: Text '2018-10-29T17:12:00' could not be parsed, unparsed text found at index 10
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1952)
	at java.time.format.DateTimeFormatter.parseBest(DateTimeFormatter.java:1897)
	at com.ibm.fhir.model.type.DateTime$Builder.value(DateTime.java:213)
	at com.ibm.fhir.search.util.SearchUtil.parseQueryParameterValuesString(SearchUtil.java:646)
	at com.ibm.fhir.search.util.SearchUtil.parseQueryParameters(SearchUtil.java:609)
	... 30 more
```

**Original Issue** 
- Support for search queries that do not include timezone #502

**Comment by prb112** [comment]
```public static final DateTimeFormatter PARSER_FORMATTER = new DateTimeFormatterBuilder()
	.appendPattern("yyyy")
	.optionalStart()
		.appendPattern("-MM")
		.optionalStart()
			.appendPattern("-dd")
			.optionalStart()
				.appendPattern("'T'HH:mm:ss")
				.optionalStart()
					.appendFraction(ChronoField.MICRO_OF_SECOND, 0, 6, true)
				.optionalEnd()
				.appendPattern("XXX")
			.optionalEnd()
		.optionalEnd()
	.optionalEnd()
	.toFormatter();
```

**Comment by prb112** [comment]
From John, we could use the approach. 
```
public static final DateTimeFormatter PARSER_FORMATTER = new DateTimeFormatterBuilder()
	.appendPattern("yyyy")
	.optionalStart()
		.appendPattern("-MM")
		.optionalStart()
			.appendPattern("-dd")
			.optionalStart()
				.appendPattern("'T'HH:mm:ss")
				.optionalStart()
					.appendFraction(ChronoField.MICRO_OF_SECOND, 0, 6, true)
				.optionalEnd()
				.optionalStart()
					.appendPattern("XXX")
				.optionalEnd()
			.optionalEnd()
		.optionalEnd()
	.optionalEnd()
	.toFormatter();
```

Year
YearMonth
LocalDate
LocalDateTime
DateTime

we also need to support:

LocalTime

and

OffsetTime

**Comment by prb112** [comment]
```
package com.ibm.fhir.model.test;
​
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.OffsetTime;
import java.time.Year;
import java.time.YearMonth;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatterBuilder;
import java.time.temporal.ChronoField;
import java.time.temporal.TemporalAccessor;
import java.util.Arrays;
import java.util.List;
​
public class PartialDateTimeParseTest {
    private static DateTimeFormatter PARSER = new DateTimeFormatterBuilder()
            .optionalStart()
                .appendPattern("yyyy")
                .optionalStart()
                    .appendPattern("-MM")
                    .optionalStart()
                        .appendPattern("-dd")
                    .optionalEnd()
                .optionalEnd()
            .optionalEnd()
            
            .optionalStart()
                .appendPattern("'T'HH:mm:ss")
                .optionalStart()
                    .appendFraction(ChronoField.MICRO_OF_SECOND, 0, 6, true)
                .optionalEnd()
                .optionalStart()
                    .appendPattern("XXX")
                .optionalEnd()
            .optionalEnd()
                    
            .toFormatter();
​
    private static List<String> DATE_TIME_EXAMPLES = Arrays.asList(
        "2019-01-01T12:00:00.000+04:00", 
        "2019-01-01T12:00:00.000", 
        "2019-01-01", 
        "2019-01", 
        "2019",
        "T12:00:00+04:00",
        "T12:00:00");
    
    public static void main(String[] args) {
        for (String value : DATE_TIME_EXAMPLES) {
            TemporalAccessor temporalAccessor = PARSER.parseBest(value, 
                ZonedDateTime::from, 
                LocalDateTime::from, 
                LocalDate::from, 
                YearMonth::from, 
                Year::from, 
                OffsetTime::from, 
                LocalTime::from);
            System.out.println(temporalAccessor.getClass());
        }
    }
}
```

**Comment by prb112** [comment]
public static final DateTimeFormatter DATE_TIME_PARSER_FORMATTER = new DateTimeFormatterBuilder()
    .appendPattern("yyyy")
    .optionalStart()
        .appendPattern("-MM")
        .optionalStart()
            .appendPattern("-dd")
            .optionalStart()
                .appendPattern("'T'HH:mm:ss")
                .optionalStart()
                    .appendFraction(ChronoField.MICRO_OF_SECOND, 0, 6, true)
                .optionalEnd()
                .optionalStart()
                    .appendPattern("XXX")
                .optionalEnd()
            .optionalEnd()
        .optionalEnd()
    .optionalEnd()
    .toFormatter();

TemporalAccessor temporalAccessor = DATE_TIME_PARSER_FORMATTER.parseBest(value, ZonedDateTime::from, LocalDateTime::from, LocalDate::from, YearMonth::from, Year::from);

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/506
