### ISSUE TITLE
Derby bootstrap does not complete successfully

### ISSUE THREAD

**Issue by JohnTimm** [IBM/FHIR#2588]
I recently encountered the following exceptions when attempting to migrate my local derby databases (`fhirDB`, `profile`, `reference`, `study1`)  using `derby-bootstrap.sh`:

```
java.sql.SQLSyntaxErrorException: Column 'LR.RESOURCE_TYPE_ID' is either not in any table in the FROM list or appears within a join specification and is outside the scope of the join specification or appears in a HAVING clause and is not in the GROUP BY list. If this is a CREATE or ALTER TABLE  statement then 'LR.RESOURCE_TYPE_ID' is not a column in the target table.
com.ibm.fhir.database.utils.api.DataAccessException: java.sql.SQLSyntaxErrorException: Column 'LR.RESOURCE_TYPE_ID' is either not in any table in the FROM list or appears within a join specification and is outside the scope of the join specification or appears in a HAVING clause and is not in the GROUP BY list. If this is a CREATE or ALTER TABLE  statement then 'LR.RESOURCE_TYPE_ID' is not a column in the target table.
	at com.ibm.fhir.database.utils.derby.DerbyTranslator.translate(DerbyTranslator.java:100)
	at com.ibm.fhir.schema.control.MigrateV0014LogicalResourceIsDeletedLastUpdated.runForDerby(MigrateV0014LogicalResourceIsDeletedLastUpdated.java:144)
	at com.ibm.fhir.schema.control.MigrateV0014LogicalResourceIsDeletedLastUpdated.run(MigrateV0014LogicalResourceIsDeletedLastUpdated.java:58)
	at com.ibm.fhir.database.utils.common.CommonDatabaseAdapter.runStatement(CommonDatabaseAdapter.java:460)
	at com.ibm.fhir.database.utils.derby.DerbyAdapter.runStatement(DerbyAdapter.java:302)
	at com.ibm.fhir.schema.app.Main.dataMigrationForV0014(Main.java:1857)
	at com.ibm.fhir.schema.app.Main.dataMigrationForV0014(Main.java:1832)
	at com.ibm.fhir.schema.app.Main.applyDataMigrationForV0014(Main.java:1683)
	at com.ibm.fhir.schema.app.Main.updateSchema(Main.java:410)
	at com.ibm.fhir.schema.app.Main.process(Main.java:1984)
	at com.ibm.fhir.schema.app.Main.main(Main.java:2082)
Caused by: java.sql.SQLSyntaxErrorException: Column 'LR.RESOURCE_TYPE_ID' is either not in any table in the FROM list or appears within a join specification and is outside the scope of the join specification or appears in a HAVING clause and is not in the GROUP BY list. If this is a CREATE or ALTER TABLE  statement then 'LR.RESOURCE_TYPE_ID' is not a column in the target table.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeQuery(Unknown Source)
	at com.ibm.fhir.schema.control.MigrateV0014LogicalResourceIsDeletedLastUpdated.runForDerby(MigrateV0014LogicalResourceIsDeletedLastUpdated.java:113)
	... 9 more
Caused by: ERROR 42X04: Column 'LR.RESOURCE_TYPE_ID' is either not in any table in the FROM list or appears within a join specification and is outside the scope of the join specification or appears in a HAVING clause and is not in the GROUP BY list. If this is a CREATE or ALTER TABLE  statement then 'LR.RESOURCE_TYPE_ID' is not a column in the target table.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.ColumnReference.bindExpression(Unknown Source)
	at org.apache.derby.impl.sql.compile.ColumnReference.bindExpression(Unknown Source)
	at org.apache.derby.impl.sql.compile.BinaryOperatorNode.bindExpression(Unknown Source)
	at org.apache.derby.impl.sql.compile.BinaryComparisonOperatorNode.bindExpression(Unknown Source)
	at org.apache.derby.impl.sql.compile.SelectNode.bindExpressions(Unknown Source)
	at org.apache.derby.impl.sql.compile.DMLStatementNode.bindExpressions(Unknown Source)
	at org.apache.derby.impl.sql.compile.DMLStatementNode.bind(Unknown Source)
	at org.apache.derby.impl.sql.compile.CursorNode.bindStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	... 12 more
```
This same error occurred for 3 of 4 databses (`fhirDB`, `profile`, and `study1`). After a discussion with @lmsurpre it appears that the tables for resource types `Practitioner`, `CodeSystem`, and `PractitionerRole` do not have the `RESOURCE_TYPE_ID` column and that it should be removed from the `SELECT` statement for resource type specific tables in the migration code.

**Comment by JohnTimm** [comment]
I re-ran the `derby-bootstrap.sh` script after rebuilding CLI from main and it successfully updated all 4 local databases.
