### ISSUE TITLE
Fail to process _typeFilter

### ISSUE THREAD

**Issue by mkmurali** [IBM/FHIR#2645]
**Describe the bug**
Fail to process _typeFilter parameter

"java.lang.NoClassDefFoundError: com.ibm.fhir.server.util.FHIRUrlParser"

**Environment**
Which version of IBM FHIR Server?
4.8.3 (Docker version)

**To Reproduce**
curl --location --request GET 'https://localhost:9443/fhir-server/api/v4/$export?_type=Coverage&_typeFilter=Coverage%3Fstatus%3Dactive' \
--header 'Authorization: Basic <VALUE>'

**Expected behavior**
Should have processed bulk export successfully

**Additional context**

Error Log:
[7/27/21, 4:16:05:418 UTC] 00000043 FHIRRestServl I   Received request: tenantId:[default] dsId:[default] user:[fhiruser] method:[GET] uri:[https://localhost:9443/fhir-server/api/v4/$export?_type=Coverage&amp;_typeFilter=Coverage%3Fstatus%3Dactive]
[7/27/21, 4:16:05:770 UTC] 00000043 FHIRRestServl I   Completed request[0.356 secs]: tenantId:[default] dsId:[default] user:[fhiruser] method:[GET] uri:[https://localhost:9443/fhir-server/api/v4/$export?_type=Coverage&amp;_typeFilter=Coverage%3Fstatus%3Dactive] status:[202]
[7/27/21, 4:16:06:229 UTC] 0000002a IncidentImpl  I   FFDC1015I: An FFDC Incident has been created: "java.lang.NoClassDefFoundError: com.ibm.fhir.server.util.FHIRUrlParser com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl 681" at ffdc_21.07.27_04.16.06.0.log
[7/27/21, 4:16:06:240 UTC] 0000002a IncidentImpl  I   FFDC1015I: An FFDC Incident has been created: "java.lang.NullPointerException com.ibm.jbatch.container.artifact.proxy.ItemWriterProxy 53" at ffdc_21.07.27_04.16.06.1.log
[7/27/21, 4:16:06:275 UTC] 0000002a IncidentImpl  I   FFDC1015I: An FFDC Incident has been created: "com.ibm.jbatch.container.exception.BatchContainerRuntimeException: java.lang.NullPointerException com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl 775" at ffdc_21.07.27_04.16.06.2.log
[7/27/21, 4:16:06:310 UTC] 0000002a IncidentImpl  I   FFDC1015I: An FFDC Incident has been created: "com.ibm.jbatch.container.exception.BatchContainerRuntimeException: Failure in Read-Process-Write Loop com.ibm.jbatch.container.controller.impl.BaseStepControllerImpl 296" at ffdc_21.07.27_04.16.06.3.log
[7/27/21, 4:16:06:353 UTC] 00000031 IncidentImpl  I   FFDC1015I: An FFDC Incident has been created: "com.ibm.jbatch.container.exception.BatchContainerRuntimeException: One or more partitions failed: [For partitioned step: step1, the partition # 0 ended with status 'FAILED] com.ibm.jbatch.container.controller.impl.BaseStepControllerImpl 296" at ffdc_21.07.27_04.16.06.4.log
[7/27/21, 4:16:06:356 UTC] 00000031 WorkUnitThrea W   CWWKY0011W: Job bulkexportchunkjob failed with batch status FAILED and exit status FAILED for job instance 3 and job execution 3.

**Comment by prb112** [comment]
Thank you @mkmurali - we've added a test to cover this scenario, and when a change like the one we made is executed, it'll be caught next time.  This should be in the next release - 4.9.0

**Comment by lmsurpre** [comment]
This doesn't seem right to me.

When I try a typeFilter like `Patient?_elements=id&_has:Condition:patient:code=http://snomed.info/sct%7C44054006'` it honors the `_elements=id` part but ignores the `_has:Condition:patient:code=http://snomed.info/sct%7C44054006`.

Further, when I try `Patient?_has:Condition:patient:code=http://snomed.info/sct%7C44054006'` it throws the following exception:

```
2021-08-05 16:11:46.805 wh-cmsiop-cthon-fhir-internal-6cbff6bdb8-ggwxh fhir-internal SEVERE StepChunkListener: job[bulkexportchunkjob/288/796] --- java.net.URISyntaxException: Illegal character in query at index 58: Patient?_has:Condition:patient:code=http://snomed.info/sct|44054006
com.ibm.jbatch.container.exception.BatchContainerRuntimeException: java.net.URISyntaxException: Illegal character in query at index 58: Patient?_has:Condition:patient:code=http://snomed.info/sct|44054006
	at com.ibm.jbatch.container.artifact.proxy.ItemReaderProxy.open(ItemReaderProxy.java:65)
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.openReaderAndWriter(ChunkStepControllerImpl.java:953)
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.invokeChunk(ChunkStepControllerImpl.java:599)
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.invokeCoreStep(ChunkStepControllerImpl.java:795)
	at com.ibm.jbatch.container.controller.impl.BaseStepControllerImpl.execute(BaseStepControllerImpl.java:295)
	at com.ibm.jbatch.container.controller.impl.ExecutionTransitioner.doExecutionLoop(ExecutionTransitioner.java:118)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeCoreTransitionLoop(WorkUnitThreadControllerImpl.java:96)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeWorkUnit(WorkUnitThreadControllerImpl.java:178)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl$AbstractControllerHelper.runExecutionOnThread(WorkUnitThreadControllerImpl.java:503)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.runExecutionOnThread(WorkUnitThreadControllerImpl.java:92)
	at com.ibm.jbatch.container.util.BatchWorkUnit.run(BatchWorkUnit.java:113)
	at com.ibm.ws.context.service.serializable.ContextualRunnable.run(ContextualRunnable.java:79)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
Caused by: java.net.URISyntaxException: Illegal character in query at index 58: Patient?_has:Condition:patient:code=http://snomed.info/sct|44054006
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3172)
	at java.base/java.net.URI$Parser.parse(URI.java:3125)
	at java.base/java.net.URI.<init>(URI.java:600)
	at com.ibm.fhir.bulkdata.common.BulkDataUtils.getSearchParametersFromTypeFilters(BulkDataUtils.java:366)
	at com.ibm.fhir.bulkdata.jbatch.export.system.ChunkReader.open(ChunkReader.java:139)
	at com.ibm.jbatch.container.artifact.proxy.ItemReaderProxy.open(ItemReaderProxy.java:62)
	... 17 more
```

It doesn't seem to matter if I percent-encode the `|` or not.

**Comment by prb112** [comment]
> This doesn't seem right to me.
> 
> When I try a typeFilter like `Patient?_elements=id&_has:Condition:patient:code=http://snomed.info/sct%7C44054006'` it honors the `_elements=id` part but ignores the `_has:Condition:patient:code=http://snomed.info/sct%7C44054006`.
> 
> Further, when I try `Patient?_has:Condition:patient:code=http://snomed.info/sct%7C44054006'` it throws the following exception:
> 
> ```
> 2021-08-05 16:11:46.805 wh-cmsiop-cthon-fhir-internal-6cbff6bdb8-ggwxh fhir-internal SEVERE StepChunkListener: job[bulkexportchunkjob/288/796] --- java.net.URISyntaxException: Illegal character in query at index 58: Patient?_has:Condition:patient:code=http://snomed.info/sct|44054006
> com.ibm.jbatch.container.exception.BatchContainerRuntimeException: java.net.URISyntaxException: Illegal character in query at index 58: Patient?_has:Condition:patient:code=http://snomed.info/sct|44054006
> 	at com.ibm.jbatch.container.artifact.proxy.ItemReaderProxy.open(ItemReaderProxy.java:65)
> 	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.openReaderAndWriter(ChunkStepControllerImpl.java:953)
> 	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.invokeChunk(ChunkStepControllerImpl.java:599)
> 	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.invokeCoreStep(ChunkStepControllerImpl.java:795)
> 	at com.ibm.jbatch.container.controller.impl.BaseStepControllerImpl.execute(BaseStepControllerImpl.java:295)
> 	at com.ibm.jbatch.container.controller.impl.ExecutionTransitioner.doExecutionLoop(ExecutionTransitioner.java:118)
> 	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeCoreTransitionLoop(WorkUnitThreadControllerImpl.java:96)
> 	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeWorkUnit(WorkUnitThreadControllerImpl.java:178)
> 	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl$AbstractControllerHelper.runExecutionOnThread(WorkUnitThreadControllerImpl.java:503)
> 	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.runExecutionOnThread(WorkUnitThreadControllerImpl.java:92)
> 	at com.ibm.jbatch.container.util.BatchWorkUnit.run(BatchWorkUnit.java:113)
> 	at com.ibm.ws.context.service.serializable.ContextualRunnable.run(ContextualRunnable.java:79)
> 	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:836)
> Caused by: java.net.URISyntaxException: Illegal character in query at index 58: Patient?_has:Condition:patient:code=http://snomed.info/sct|44054006
> 	at java.base/java.net.URI$Parser.fail(URI.java:2913)
> 	at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
> 	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3172)
> 	at java.base/java.net.URI$Parser.parse(URI.java:3125)
> 	at java.base/java.net.URI.<init>(URI.java:600)
> 	at com.ibm.fhir.bulkdata.common.BulkDataUtils.getSearchParametersFromTypeFilters(BulkDataUtils.java:366)
> 	at com.ibm.fhir.bulkdata.jbatch.export.system.ChunkReader.open(ChunkReader.java:139)
> 	at com.ibm.jbatch.container.artifact.proxy.ItemReaderProxy.open(ItemReaderProxy.java:62)
> 	... 17 more
> ```
> 
> It doesn't seem to matter if I percent-encode the `|` or not.

I can add a test for this one above....

**Comment by prb112** [comment]
Special condition with PIPE needed to be re-enncoded

**Comment by lmsurpre** [comment]
> Further, when I try Patient?_has:Condition:patient:code=http://snomed.info/sct%7C44054006' it throws the following exception:

With the latest change, this is now working for me.

> When I try a typeFilter like Patient?_elements=id&_has:Condition:patient:code=http://snomed.info/sct%7C44054006' it honors the _elements=id part but ignores the _has:Condition:patient:code=http://snomed.info/sct%7C44054006

This one turned out to be pretty interesting.  The `&` in the URL is getting encoded as `&amp;` for some reason.  I opened https://stackoverflow.com/questions/68687087/character-entity-references-in-parameter-values so that I don't forget to investigate the "why", but I think this particular odd behavior is a client-side issue and that the server api is now working as expected.
