### ISSUE TITLE
Reindex of latest code produced a deadlock in some tables. 

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#2654]
**Describe the bug**
During a reindex a deadlock was hit

**Environment**
Latest code in main on 7/28/2021

**To Reproduce**

**Expected behavior**

**Additional context**
Here are some log entries from the reindex. 
```
Jul 29 01:55:55 wh-cmsiop-cthon-fhir-internal-7dd96bc9f8-wpmfq fhir-internal WARNING Skipping search parameter with id='us-core-patient-identifier'. Found multiple search parameters, 'http://hl7.org/fhir/SearchParameter/Patient-identifier' and 'http://hl7.org/fhir/us/core/SearchParameter/us-core-patient-identifier', for code 'identifier' on resource type 'Patient'; use search parameter filtering to disambiguate.
Jul 29 01:55:55 wh-cmsiop-cthon-fhir-internal-7dd96bc9f8-wpmfq fhir-internal WARNING Skipping search parameter with id='us-core-patient-gender'. Found multiple search parameters, 'http://hl7.org/fhir/SearchParameter/individual-gender' and 'http://hl7.org/fhir/us/core/SearchParameter/us-core-patient-gender', for code 'gender' on resource type 'Patient'; use search parameter filtering to disambiguate.
Jul 29 01:55:55 wh-cmsiop-cthon-fhir-internal-7dd96bc9f8-wpmfq fhir-internal WARNING Code '_id' is defined for Resource and Patient with differing expressions; using Patient
Jul 29 01:55:55 wh-cmsiop-cthon-fhir-internal-7dd96bc9f8-9wqxl fhir-internal SEVERE INSERT INTO common_canonical_values (canonical_id, url)      SELECT nextval('fhirdata.fhir_ref_sequence'), v.name        FROM     (VALUES (CAST(? AS VARCHAR(1024))) ) AS v(name)  ON CONFLICT DO NOTHING 
org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 148774 waits for ShareLock on transaction 33290864; blocked by process 172608.
Process 172608 waits for ShareLock on transaction 33290869; blocked by process 148774.
  Hint: See server log for query details.
  Where: while inserting index tuple (0,13) in relation "common_canonical_values"
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
    at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
    at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130)
    at jdk.internal.reflect.GeneratedMethodAccessor75.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.postgresql.ds.PGPooledConnection$StatementHandler.invoke(PGPooledConnection.java:441)
    at com.sun.proxy.$Proxy91.executeUpdate(Unknown Source)
    at com.ibm.ws.rsadapter.jdbc.WSJdbcPreparedStatement.executeUpdate(WSJdbcPreparedStatement.java:520)
    at com.ibm.fhir.persistence.jdbc.postgres.PostgresResourceReferenceDAO.doCanonicalValuesUpsert(PostgresResourceReferenceDAO.java:106)
    at com.ibm.fhir.persistence.jdbc.dao.impl.ResourceReferenceDAO.upsertCanonicalValues(ResourceReferenceDAO.java:388)
    at com.ibm.fhir.persistence.jdbc.dao.impl.ResourceReferenceDAO.persist(ResourceReferenceDAO.java:791)
    at com.ibm.fhir.persistence.jdbc.dao.impl.ResourceReferenceDAO.addNormalizedValues(ResourceReferenceDAO.java:182)
    at com.ibm.fhir.persistence.jdbc.dao.impl.ParameterVisitorBatchDAO.close(ParameterVisitorBatchDAO.java:629)
    at com.ibm.fhir.persistence.jdbc.dao.ReindexResourceDAO.updateParameters(ReindexResourceDAO.java:354)
    at com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl.updateParameters(FHIRPersistenceJDBCImpl.java:2643)
    at com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl.reindex(FHIRPersistenceJDBCImpl.java:2572)
    at com.ibm.fhir.server.util.FHIRRestHelper.doReindex(FHIRRestHelper.java:3101)
    at com.ibm.fhir.operation.reindex.ReindexOperation.doInvoke(ReindexOperation.java:169)
    at com.ibm.fhir.server.operation.spi.AbstractOperation.invoke(AbstractOperation.java:66)
    at com.ibm.fhir.server.util.FHIRRestHelper.doInvoke(FHIRRestHelper.java:1165)
    at com.ibm.fhir.server.resources.Operation.invoke(Operation.java:126)
    at com.ibm.fhir.server.resources.Operation$Proxy$_$$_WeldClientProxy.invoke(Unknown Source)
    at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.ibm.ws.jaxrs20.cdi.component.JaxRsFactoryImplicitBeanCDICustomizer.serviceInvoke(JaxRsFactoryImplicitBeanCDICustomizer.java:342)
    at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:641)
    at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.performInvocation(LibertyJaxRsInvoker.java:160)
    at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:101)
    at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.invoke(LibertyJaxRsInvoker.java:273)
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:213)
    at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.invoke(LibertyJaxRsInvoker.java:444)
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:112)
    at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
    at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
    at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
    at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:123)
    at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:274)
    at com.ibm.ws.jaxrs20.endpoint.AbstractJaxRsWebEndpoint.invoke(AbstractJaxRsWebEndpoint.java:137)
    at com.ibm.websphere.jaxrs.server.IBMRestServlet.handleRequest(IBMRestServlet.java:146)
    at com.ibm.websphere.jaxrs.server.IBMRestServlet.doPost(IBMRestServlet.java:104)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:706)
    at com.ibm.websphere.jaxrs.server.IBMRestServlet.service(IBMRestServlet.java:96)
    at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)
    at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:746)
    at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:443)
    at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:183)
    at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:94)
    at com.ibm.fhir.server.filter.rest.FHIRRestServletFilter.doFilter(FHIRRestServletFilter.java:155)
    at javax.servlet.http.HttpFilter.doFilter(HttpFilter.java:127)
    at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
    at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
    at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:56)
    at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
    at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
    at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1002)
    at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1140)
    at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1011)
    at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)
    at com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40.handleRequest(CacheServletWrapper40.java:85)
    at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:938)
    at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
    at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1159)
    at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:428)
    at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:387)
    at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566)
    at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500)
    at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360)
    at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete(HttpICLReadCallback.java:70)
    at com.ibm.ws.channel.ssl.internal.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1824)
    at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
    at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
    at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
    at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
    at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:836)
Jul 29 01:55:55 wh-cmsiop-cthon-fhir-internal-7dd96bc9f8-9wqxl fhir-internal WARNING Retryable error while performing reindex of FHIR Resource 'Organization/plannet-organization-7638c1c4baf73b8cc2a47c2b3'
com.ibm.fhir.database.utils.api.LockException: org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 148774 waits for ShareLock on transaction 33290864; blocked by process 172608.
Process 172608 waits for ShareLock on transaction 33290869; blocked by process 148774.
  Hint: See server log for query details.
  Where: while inserting index tuple (0,13) in relation "common_canonical_values"
    at com.ibm.fhir.database.utils.postgres.PostgresTranslator.translate(PostgresTranslator.java:92)
    at com.ibm.fhir.persistence.jdbc.postgres.PostgresResourceReferenceDAO.doCanonicalValuesUpsert(PostgresResourceReferenceDAO.java:109)
    at com.ibm.fhir.persistence.jdbc.dao.impl.ResourceReferenceDAO.upsertCanonicalValues(ResourceReferenceDAO.java:388)
    at com.ibm.fhir.persistence.jdbc.dao.impl.ResourceReferenceDAO.persist(ResourceReferenceDAO.java:791)
    at com.ibm.fhir.persistence.jdbc.dao.impl.ResourceReferenceDAO.addNormalizedValues(ResourceReferenceDAO.java:182)
    at com.ibm.fhir.persistence.jdbc.dao.impl.ParameterVisitorBatchDAO.close(ParameterVisitorBatchDAO.java:629)
    at com.ibm.fhir.persistence.jdbc.dao.ReindexResourceDAO.updateParameters(ReindexResourceDAO.java:354)
    at com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl.updateParameters(FHIRPersistenceJDBCImpl.java:2643)
    at com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl.reindex(FHIRPersistenceJDBCImpl.java:2572)
    at com.ibm.fhir.server.util.FHIRRestHelper.doReindex(FHIRRestHelper.java:3101)
    at com.ibm.fhir.operation.reindex.ReindexOperation.doInvoke(ReindexOperation.java:169)
    at com.ibm.fhir.server.operation.spi.AbstractOperation.invoke(AbstractOperation.java:66)
    at com.ibm.fhir.server.util.FHIRRestHelper.doInvoke(FHIRRestHelper.java:1165)
    at com.ibm.fhir.server.resources.Operation.invoke(Operation.java:126)
    at com.ibm.fhir.server.resources.Operation$Proxy$_$$_WeldClientProxy.invoke(Unknown Source)
    at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at com.ibm.ws.jaxrs20.cdi.component.JaxRsFactoryImplicitBeanCDICustomizer.serviceInvoke(JaxRsFactoryImplicitBeanCDICustomizer.java:342)
    at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:641)
    at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.performInvocation(LibertyJaxRsInvoker.java:160)
```

**Comment by lmsurpre** [comment]
We successfully ran a reindex on our postgres db with about 15.4M resources.
