### ISSUE TITLE
CICD: BulkData - Bucket is missing ObjectLockConfiguration

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#2783]
**Describe the bug**
CICD: BulkData - Bucket is missing ObjectLockConfiguration

This is a CICD

**Environment**
Which version of IBM FHIR Server?
4.9.1

**To Reproduce**
1. Setup Bulk Data with Minio and the latest docker
2. Execute System Export with `fast`

You'll see the job fail: 

```
[9/20/21, 12:23:33:607 UTC] [step1 partition0] com.ibm.ws.batch.JobLogger                                     CWWKY0030I: An exception occurred while running the step step1.
com.ibm.jbatch.container.exception.BatchContainerRuntimeException: Failure in Read-Process-Write Loop
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.invokeChunk(ChunkStepControllerImpl.java:704)
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.invokeCoreStep(ChunkStepControllerImpl.java:795)
	at com.ibm.jbatch.container.controller.impl.BaseStepControllerImpl.execute(BaseStepControllerImpl.java:295)
	at com.ibm.jbatch.container.controller.impl.ExecutionTransitioner.doExecutionLoop(ExecutionTransitioner.java:118)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeCoreTransitionLoop(WorkUnitThreadControllerImpl.java:96)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeWorkUnit(WorkUnitThreadControllerImpl.java:178)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl$AbstractControllerHelper.runExecutionOnThread(WorkUnitThreadControllerImpl.java:503)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.runExecutionOnThread(WorkUnitThreadControllerImpl.java:92)
	at com.ibm.jbatch.container.util.BatchWorkUnit.run(BatchWorkUnit.java:113)
	at com.ibm.ws.context.service.serializable.ContextualRunnable.run(ContextualRunnable.java:79)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:866)
Caused by: com.ibm.jbatch.container.exception.BatchContainerRuntimeException: com.ibm.cloud.objectstorage.services.s3.model.AmazonS3Exception: Bucket is missing ObjectLockConfiguration (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; Request ID: 16A6873D8C6C7768), S3 Extended Request ID: 79d311f6-9d0e-4b57-921d-1d06e92d0ec5
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.readItem(ChunkStepControllerImpl.java:360)
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.readAndProcess(ChunkStepControllerImpl.java:245)
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.invokeChunk(ChunkStepControllerImpl.java:626)
	... 15 more
Caused by: com.ibm.cloud.objectstorage.services.s3.model.AmazonS3Exception: Bucket is missing ObjectLockConfiguration (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; Request ID: 16A6873D8C6C7768), S3 Extended Request ID: 79d311f6-9d0e-4b57-921d-1d06e92d0ec5
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4214)
	at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4161)
	at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.initiateMultipartUpload(AmazonS3Client.java:2962)
	at com.ibm.fhir.bulkdata.common.BulkDataUtils.startPartUpload(BulkDataUtils.java:84)
	at com.ibm.fhir.bulkdata.jbatch.export.fast.ResourcePayloadReader.uploadWhenReady(ResourcePayloadReader.java:462)
	at com.ibm.fhir.bulkdata.jbatch.export.fast.ResourcePayloadReader.processPayload(ResourcePayloadReader.java:422)
	at com.ibm.fhir.bulkdata.jbatch.export.fast.ResourcePayloadReader.lambda$readItem$0(ResourcePayloadReader.java:316)
	at com.ibm.fhir.bulkdata.jbatch.export.fast.ResourcePayloadReader$$Lambda$776/0x00000000bd295c90.apply(Unknown Source)
	at com.ibm.fhir.persistence.jdbc.dao.impl.FetchResourcePayloadsDAO.run(FetchResourcePayloadsDAO.java:136)
	at com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl.fetchResourcePayloads(FHIRPersistenceJDBCImpl.java:2827)
	at com.ibm.fhir.bulkdata.jbatch.export.fast.ResourcePayloadReader.readItem(ResourcePayloadReader.java:316)
	at com.ibm.jbatch.container.artifact.proxy.ItemReaderProxy.readItem(ItemReaderProxy.java:77)
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.readItem(ChunkStepControllerImpl.java:329)
```

**Expected behavior**
Work around is in place with minio specified to a previous passing version.

**Additional context**
see https://github.com/minio/minio/releases/tag/RELEASE.2021-09-18T18-09-59Z

**Comment by prb112** [comment]
I think this is a one pointer

**Comment by prb112** [comment]
Refer to https://github.com/minio/minio/issues/13252

```FS mode: Starting minio server /data with existing folders fails on RELEASE.2021-09-18T18-09-59Z #13252 ```

**Comment by prb112** [comment]
Awaiting new release of minio/minio

**Comment by prb112** [comment]
See  cicd: Update Dockerfile with note and revert to latest #2796
