### ISSUE TITLE
incompatibility between 3.9.x and 4.1.3 in the FHIR Term Graph. 

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#2930]
There is an incompatibility between 3.9.x and 4.13.0 in the FHIR Term Graph. (Pretty much any 4.x release)

Stack Trace
```
21:05:01.671 [main] INFO  c.d.o.d.i.c.DefaultMavenCoordinates - DataStax Java driver for Apache Cassandra(R) (com.datastax.oss:java-driver-core) version 4.10.0
21:05:02.273 [JanusGraph Session-admin-0] INFO  c.d.o.d.internal.core.time.Clock - Using native clock for microsecond precision
21:05:02.832 [JanusGraph Session-admin-4] WARN  c.d.o.d.i.c.l.h.OptionalLocalDcHelper - [JanusGraph Session|default] You specified datacenter1 as the local DC,

Exception in thread "main" java.lang.Error: com.datastax.oss.driver.api.core.NoNodeAvailableException: No node was available to execute the query
	at com.ibm.fhir.term.graph.impl.FHIRTermGraphImpl.<init>(FHIRTermGraphImpl.java:43)
	at com.ibm.fhir.term.graph.factory.FHIRTermGraphFactory.open(FHIRTermGraphFactory.java:51)
	at com.ibm.fhir.term.graph.loader.impl.AbstractTermGraphLoader.<init>(AbstractTermGraphLoader.java:46)
	at com.ibm.fhir.term.graph.loader.impl.UMLSTermGraphLoader.<init>(UMLSTermGraphLoader.java:84)
	at com.ibm.fhir.term.graph.loader.impl.UMLSTermGraphLoader.main(UMLSTermGraphLoader.java:346)
Caused by: com.datastax.oss.driver.api.core.NoNodeAvailableException: No node was available to execute the query
	at com.datastax.oss.driver.api.core.NoNodeAvailableException.copy(NoNodeAvailableException.java:40)
	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
	at com.datastax.oss.driver.internal.core.cql.CqlPrepareSyncProcessor.process(CqlPrepareSyncProcessor.java:59)
	at com.datastax.oss.driver.internal.core.cql.CqlPrepareSyncProcessor.process(CqlPrepareSyncProcessor.java:31)
	at com.datastax.oss.driver.internal.core.session.DefaultSession.execute(DefaultSession.java:230)
	at com.datastax.oss.driver.api.core.cql.SyncCqlSession.prepare(SyncCqlSession.java:206)
	at org.janusgraph.diskstorage.cql.CQLKeyColumnValueStore.<init>(CQLKeyColumnValueStore.java:168)
	at org.janusgraph.diskstorage.cql.CQLStoreManager.lambda$openDatabase$7(CQLStoreManager.java:267)
	at org.janusgraph.diskstorage.cql.CQLStoreManager$$Lambda$340/0x00000000fc9547c0.apply(Unknown Source)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at org.janusgraph.diskstorage.cql.CQLStoreManager.openDatabase(CQLStoreManager.java:267)
	at org.janusgraph.diskstorage.keycolumnvalue.KeyColumnValueStoreManager.openDatabase(KeyColumnValueStoreManager.java:43)
	at org.janusgraph.diskstorage.configuration.backend.builder.KCVSConfigurationBuilder.buildStandaloneGlobalConfiguration(KCVSConfigurationBuilder.java:51)
	at org.janusgraph.diskstorage.configuration.builder.ReadConfigurationBuilder.buildGlobalConfiguration(ReadConfigurationBuilder.java:71)
	at org.janusgraph.graphdb.configuration.builder.GraphDatabaseConfigurationBuilder.build(GraphDatabaseConfigurationBuilder.java:67)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:176)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:147)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:127)
	at com.ibm.fhir.term.graph.impl.FHIRTermGraphImpl.open(FHIRTermGraphImpl.java:53)
	at com.ibm.fhir.term.graph.impl.FHIRTermGraphImpl.<init>(FHIRTermGraphImpl.java:40)
	... 4 more
```

```
storage.cql.local-datacenter is mandatory now and defaults to datacenter1.
```

https://github.com/JanusGraph/janusgraph/blob/master/docs/changelog.md#datastax-cassandra-driver-upgrade-from-390-to-4130

**Comment by prb112** [comment]
QA: Adam was able to load data into Cassandra.
