### ISSUE TITLE
Infinite loop accessing the FHIR registry from a registry resource provider

### ISSUE THREAD

**Issue by sfc42** [IBM/FHIR#2969]
**Describe the bug**
Able to get into an infinite loop accessing the FHIR registry from a registry resource provider.  

**Environment**
Which version of IBM FHIR Server?
4.9.2-5

**To Reproduce**
1. Write an extension to AbstractRegistryResourceProvider.  
2. Call FHIRRegistry.getInstance().getResource() from the getRegistryResources method.  

**Expected behavior**
Expected to not receive an infinite loop.  

**Additional context**
The loop is:
	at com.ibm.watson.health.interop.EndpointAddonRegistryResourceProvider.getRegistryResources(EndpointAddonRegistryResourceProvider.java:62)
	at com.ibm.fhir.registry.spi.AbstractRegistryResourceProvider.getRegistryResource(AbstractRegistryResourceProvider.java:25)
	at com.ibm.fhir.registry.FHIRRegistry.findRegistryResource(FHIRRegistry.java:279)
	at com.ibm.fhir.registry.FHIRRegistry.getResource(FHIRRegistry.java:162)
	at com.ibm.watson.health.interop.EndpointAddonRegistryResourceProvider.getRegistryResources(EndpointAddonRegistryResourceProvider.java:62)
	at com.ibm.fhir.registry.spi.AbstractRegistryResourceProvider.getRegistryResource(AbstractRegistryResourceProvider.java:25)
	at com.ibm.fhir.registry.FHIRRegistry.findRegistryResource(FHIRRegistry.java:279)
	at com.ibm.fhir.registry.FHIRRegistry.getResource(FHIRRegistry.java:162)

**Comment by lmsurpre** [comment]
In https://github.com/IBM/FHIR/pull/2970 Paul added two things to help users avoid this pitfall:
1. a method on FHIRRegistry that you can call which will prevent the (preventing the loop)
2. an `init()` method to the FHIRRegistryResourceProvider interface, so that you have a good spot to use that from (since construction happens before all the resource providers are hooked up)

In both cases, the behavior is opt-in.  I opened #2975 for a method that I'd consider slightly cleaner, but we think Paul's change adequately addresses the issue for now.  
@sfc42 If you agree, please close the issue.  If we don't hear back soon, we'll close it ourselves.  Thanks!

**Comment by sfc42** [comment]
This fix fully addressed my issue. Closing issue accordingly.
