### ISSUE TITLE
Automation has unexpected failures

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#2983]
**Describe the bug**
Automation has unexpected failures

**Environment**
Which version of IBM FHIR Server? main

**To Reproduce**
1. Raise a PR
2. PR should pass reliably (with a good merge)

**Expected behavior**

**Additional context**

**Comment by prb112** [comment]
https://github.com/IBM/FHIR/blob/main/.github/workflows/windows.yml 
- run on push to main 

Conditional Run Audit and Notification

**Comment by prb112** [comment]
```
$ grep -iRn pool *
docker/updateSchema.sh:14:# to avoid this, serialize the steps using --pool-size 1
docker/updateSchema.sh:17:  --pool-size 1
docker/updateSchema.sh:21:  --prop-file db2.properties --schema-name FHIRDATA --grant-to FHIRSERVER --pool-size 2
docker/updateSchema.sh:29:  --pool-size 20
docker/deploySchemaAndTenant.sh:57:  --prop-file db2.properties --schema-name FHIRDATA --update-schema --pool-size 2
docker/deploySchemaAndTenant.sh:60:  --prop-file db2.properties --schema-name FHIRDATA --grant-to FHIRSERVER --pool-size 2
docker/deploySchemaAndTenant.sh:63:  --prop-file db2.properties --schema-name FHIRDATA --allocate-tenant default --pool-size 2
migration/postgres/4_current-migrate.sh:56:    --schema-name FHIRDATA --update-schema --pool-size 1
migration/postgres/4_current-migrate.sh:62:    --schema-name FHIRDATA --grant-to FHIRSERVER --pool-size 1
migration/postgres/5_current-pre-integration-test.sh:90:    # Pool-size is set to 1, because of... org.postgresql.util.PSQLException: ERROR: deadlock detected
migration/postgres/5_current-pre-integration-test.sh:95:        --schema-name FHIRDATA --update-schema --pool-size 1
migration/postgres/5_current-pre-integration-test.sh:101:        --schema-name FHIRDATA --grant-to FHIRSERVER --pool-size 1
migration/postgres/2_compose.sh:116:    # Pool-size is set to 1, because of... org.postgresql.util.PSQLException: ERROR: deadlock detected
migration/postgres/2_compose.sh:121:        --schema-name FHIRDATA --create-schemas --pool-size 1
migration/postgres/2_compose.sh:127:        --schema-name FHIRDATA --update-schema --pool-size 1
migration/postgres/2_compose.sh:133:        --schema-name FHIRDATA --grant-to FHIRSERVER --pool-size 1
persistence/postgres/pre-integration-test.sh:124:    # Pool-size is set to 1, because of... org.postgresql.util.PSQLException: ERROR: deadlock detected
persistence/postgres/pre-integration-test.sh:127:        --prop-file workarea/postgres.properties --schema-name FHIRDATA --create-schemas --pool-size 1
persistence/postgres/pre-integration-test.sh:131:        --prop-file workarea/postgres.properties --schema-name FHIRDATA --update-schema --pool-size 1
persistence/postgres/pre-integration-test.sh:135:       --prop-file workarea/postgres.properties --schema-name FHIRDATA --grant-to FHIRSERVER --pool-size 1
```

**Comment by prb112** [comment]
```
java.lang.NoClassDefFoundError: javax/xml/ws/WebServiceFeature
	at com.ibm.fhir.client.impl.FHIRClientImpl.<init>(FHIRClientImpl.java:149)
	at com.ibm.fhir.client.FHIRClientFactory.getClient(FHIRClientFactory.java:22)
	at com.ibm.fhir.server.test.FHIRServerTestBase.setUp(FHIRServerTestBase.java:296)
	at com.ibm.fhir.server.test.FHIRServerTestBase.setUp(FHIRServerTestBase.java:283)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
```

Shouldn't have gotten into https://github.com/IBM/FHIR/actions/runs/1476662316 (seems to be related to a recent PR merge and only possibly on logging turned on)

PR that changed feature https://github.com/IBM/FHIR/pull/2827

**Comment by lmsurpre** [comment]
The build seems to have stabilized with the following changes:
1. now a single pr will only have one set of actions running (existing actions will be usurped by new commit)
2. removal of multithreaded maven builds

Additional build / automation tasks should get their own issues.
