### ISSUE TITLE
Usability Enhancement for Scenario where the schema does not match or does not exist

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#3031]
**Is your feature request related to a problem? Please describe.**

Usability Enhancement for Scenario where the schema does not match or does not exist

```
[11/22/21, 18:42:21:697 UTC] [step1 partition0] com.ibm.fhir.persistence.jdbc.dao.impl.FHIRDbDAOImpl           Failure retrieving FHIR objects. SQL=SELECT R.RESOURCE_ID, R.LOGICAL_RESOURCE_ID, R.VERSION_ID, R.LAST_UPDATED, R.IS_DELETED, R.DATA, LR.LOGICAL_ID FROM Patient_RESOURCES R, Patient_LOGICAL_RESOURCES LR WHERE LR.LOGICAL_ID = ? AND R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID  searchArgs=[8151065df37a457cac767e3cf63c7978] [probeId=c0-a8-1-82-b5668a18-f6e6-46f7-9899-f32b170905fa]
                                 org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
	at jdk.internal.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.postgresql.ds.PGPooledConnection$StatementHandler.invoke(PGPooledConnection.java:441)
	at com.sun.proxy.$Proxy142.executeQuery(Unknown Source)
	at com.ibm.ws.rsadapter.jdbc.WSJdbcPreparedStatement.executeQuery(WSJdbcPreparedStatement.java:475)
	at com.ibm.fhir.persistence.jdbc.dao.impl.FHIRDbDAOImpl.runQuery(FHIRDbDAOImpl.java:210)
	at com.ibm.fhir.persistence.jdbc.dao.impl.ResourceDAOImpl.read(ResourceDAOImpl.java:211)
	at com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl.read(FHIRPersistenceJDBCImpl.java:1172)
	at com.ibm.fhir.bulkdata.jbatch.load.ChunkWriter.conditionalFingerprintUpdate(ChunkWriter.java:305)
	at com.ibm.fhir.bulkdata.jbatch.load.ChunkWriter.writeItems(ChunkWriter.java:224)
	at com.ibm.jbatch.container.artifact.proxy.ItemWriterProxy.writeItems(ItemWriterProxy.java:80)
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.writeChunk(ChunkStepControllerImpl.java:481)
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.invokeChunk(ChunkStepControllerImpl.java:636)
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.invokeCoreStep(ChunkStepControllerImpl.java:795)
	at com.ibm.jbatch.container.controller.impl.BaseStepControllerImpl.execute(BaseStepControllerImpl.java:295)
	at com.ibm.jbatch.container.controller.impl.ExecutionTransitioner.doExecutionLoop(ExecutionTransitioner.java:118)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeCoreTransitionLoop(WorkUnitThreadControllerImpl.java:96)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeWorkUnit(WorkUnitThreadControllerImpl.java:178)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl$AbstractControllerHelper.runExecutionOnThread(WorkUnitThreadControllerImpl.java:503)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.runExecutionOnThread(WorkUnitThreadControllerImpl.java:92)
	at com.ibm.jbatch.container.util.BatchWorkUnit.run(BatchWorkUnit.java:113)
	at com.ibm.ws.context.service.serializable.ContextualRunnable.run(ContextualRunnable.java:79)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "resource_types" does not exist
  Position: 45
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.postgresql.ds.PGPooledConnection$StatementHandler.invoke(PGPooledConnection.java:441)
	at com.sun.proxy.$Proxy142.executeQuery(Unknown Source)
	at com.ibm.ws.rsadapter.jdbc.WSJdbcPreparedStatement.executeQuery(WSJdbcPreparedStatement.java:475)
	at com.ibm.fhir.persistence.jdbc.dao.impl.ResourceDAOImpl.readAllResourceTypeNames(ResourceDAOImpl.java:357)
	at com.ibm.fhir.persistence.jdbc.cache.FHIRPersistenceJDBCCacheUtil.prefill(FHIRPersistenceJDBCCacheUtil.java:38)
	at com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl.doCachePrefill(FHIRPersistenceJDBCImpl.java:2287)
	at com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl.makeResourceDAO(FHIRPersistenceJDBCImpl.java:517)
	at com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl.read(FHIRPersistenceJDBCImpl.java:1170)
	... 20 more
```

It'd be worth alerting the user to the resource_types issue most likely being related to schema. 
A small hint would be very useful.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Acceptance Criteria**

1.  
   GIVEN ibm-fhir-server
    AND fhirdata schema that does not exist
   WHEN fhirdata is configured in the fhir-server-config.json
    AND fhirdata is configured in the datasources.xml
   THEN start the server (ignore healthcheck)
    AND verify the server after start displays the warning when trying to create the resource

**Additional context**

**Comment by prb112** [comment]
All I am proposing here is a HINT added to the above error message so the user is encouraged to check the configuration.

**Comment by lmsurpre** [comment]
First:  double-check that our healthcheck catches this case and provides a reasonable error.
If not, it should.

Then:  see if we can follow similar path to return more helpful error in non-healthcheck calls.  if it makes more sense, might just be a thing to document instead
