### ISSUE TITLE
Datasource hits an I/IO exception with bulkdata datasource

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#3039]
**Describe the bug**

Datasource hits an I/IO exception with bulkdata datasource

```
   Nov 24 09:25:44 test-ibm-fhir-server-b5765889-gqcqg ibm-fhir-server INFO Received request: tenantId:[default] dsId:[default] user:[fhiruser] method:[POST] uri:[https://uffda.cluster1-blue-250babbbe4c3000e15508cd07c1d282b-0000.us-east.containers.appdomain.cloud/fhir-server/api/v4/$import]
    Nov 24 09:25:44 test-ibm-fhir-server-b5765889-gqcqg ibm-fhir-server AUDIT J2CA0056I: The Connection Manager received a fatal connection error from the Resource Adapter for resource jdbc/fhirbatchDB. The exception is: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.:java.net.SocketException: Connection reset
    Nov 24 09:25:44 test-ibm-fhir-server-b5765889-gqcqg ibm-fhir-server ERROR WTRN0074E: Exception caught from before_completion synchronization operation: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.9.v20210604-2c549e2208): org.eclipse.persistence.exceptions.DatabaseException
    Internal Exception: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
    Error Code: 0
    Call: INSERT INTO FHIR_JBATCH.JOBINSTANCE (AMCNAME, BATCHSTATUS, CREATETIME, EXITSTATUS, INSTANCESTATE, JOBNAME, JOBXMLNAME, JOBXML, UPDATETIME, NUMEXECS, RESTARTON, SUBMITTER) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        bind => [12 parameters bound]
    Query: InsertObjectQuery(For JobInstanceEntity:  instanceId = 0, batchStatus = STARTING, instanceState = SUBMITTED)
        at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl$1.handleException(EntityManagerSetupImpl.java:788)
        at org.eclipse.persistence.transaction.AbstractSynchronizationListener.handleException(AbstractSynchronizationListener.java:277)
        at org.eclipse.persistence.transaction.AbstractSynchronizationListener.beforeCompletion(AbstractSynchronizationListener.java:172)
        at org.eclipse.persistence.transaction.JTASynchronizationListener.beforeCompletion(JTASynchronizationListener.java:70)
        at com.ibm.tx.jta.impl.RegisteredSyncs.coreDistributeBefore(RegisteredSyncs.java:238)
        at com.ibm.tx.jta.impl.RegisteredSyncs.distributeBefore(RegisteredSyncs.java:146)
        at com.ibm.tx.jta.impl.TransactionImpl.prePrepare(TransactionImpl.java:1405)
        at com.ibm.tx.jta.impl.TransactionImpl.stage1CommitProcessing(TransactionImpl.java:796)
        at com.ibm.tx.jta.impl.TransactionImpl.processCommit(TransactionImpl.java:771)
        at com.ibm.tx.jta.impl.TransactionImpl.commit(TransactionImpl.java:714)
        at com.ibm.tx.jta.impl.TranManagerImpl.commit(TranManagerImpl.java:153)
        at com.ibm.tx.jta.impl.TranManagerSet.commit(TranManagerSet.java:110)
        at com.ibm.ws.transaction.services.TransactionManagerService.commit(TransactionManagerService.java:293)
        at com.ibm.jbatch.container.services.impl.JPAPersistenceManagerImpl$TranRequest.commitIfNewTranWasStarted(JPAPersistenceManagerImpl.java:2825)
        at com.ibm.jbatch.container.services.impl.JPAPersistenceManagerImpl$TranRequest.runInNewOrExistingGlobalTran(JPAPersistenceManagerImpl.java:2789)
        at com.ibm.jbatch.container.services.impl.JPAPersistenceManagerImpl.createJobInstance(JPAPersistenceManagerImpl.java:431)
        at <unknown class>.createJobInstance(BatchKernelImpl.java:277)
        at <unknown class>.createJobInstance(WSJobOperatorImpl.java:163)
        at <unknown class>.start(BatchManagerImpl.java:404)
        at <unknown class>.submitJob(JobInstances.java:653)
        at <unknown class>.access$600(JobInstances.java:115)
        at <unknown class>.post(JobInstances.java:286)
        at <unknown class>.routeRequestInternal(RequestRouter.java:87)
        at <unknown class>.routeRequest(RequestRouter.java:70)
        at <unknown class>.handleRequest(JobInstances.java:263)
        at <unknown class>.handleRequest(RESTHandlerContainerImpl.java:463)
        at <unknown class>.handleWithDelegate(RESTProxyServlet.java:119)
        at <unknown class>.service(RESTProxyServlet.java:64)
        at <unknown class>.service(HttpServlet.java:791)
        at <unknown class>.service(ServletWrapper.java:1258)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:746)
        at <unknown class>.handleRequest(ServletWrapper.java:443)
        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:193)
        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:98)
        at <unknown class>.doFilter(OsgiDirectoryProtectionFilter.java:90)
        at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
        at com.ibm.ws.security.jaspi.JaspiServletFilter.doFilter(JaspiServletFilter.java:56)
        at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
        at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91)
        at <unknown class>.doFilter(WebAppFilterManager.java:1002)
        at <unknown class>.invokeFilters(WebAppFilterManager.java:1140)
        at <unknown class>.invokeFilters(WebAppFilterManager.java:1011)
        at <unknown class>.handleRequest(CacheServletWrapper.java:75)
        at <unknown class>.handleRequest(CacheServletWrapper40.java:85)
        at <unknown class>.handleRequest(WebContainer.java:938)
        at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1159)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:428)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:387)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:566)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:500)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:360)
        at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete(HttpICLReadCallback.java:70)
        at com.ibm.ws.channel.ssl.internal.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1824)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
        at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:866)
    Caused by: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.9.v20210604-2c549e2208): org.eclipse.persistence.exceptions.DatabaseException
    Internal Exception: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
    Error Code: 0
    Call: INSERT INTO FHIR_JBATCH.JOBINSTANCE (AMCNAME, BATCHSTATUS, CREATETIME, EXITSTATUS, INSTANCESTATE, JOBNAME, JOBXMLNAME, JOBXML, UPDATETIME, NUMEXECS, RESTARTON, SUBMITTER) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        bind => [12 parameters bound]
    Query: InsertObjectQuery(For JobInstanceEntity:  instanceId = 0, batchStatus = STARTING, instanceState = SUBMITTED)
        at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:342)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.processExceptionForCommError(DatabaseAccessor.java:1655)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeDirectNoSelect(DatabaseAccessor.java:906)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeNoSelect(DatabaseAccessor.java:970)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:640)
        at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:567)
        at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2105)
        at org.eclipse.persistence.sessions.server.ClientSession.executeCall(ClientSession.java:313)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:277)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.executeCall(DatasourceCallQueryMechanism.java:263)
        at org.eclipse.persistence.internal.queries.DatasourceCallQueryMechanism.insertObject(DatasourceCallQueryMechanism.java:413)
        at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:167)
        at org.eclipse.persistence.internal.queries.StatementQueryMechanism.insertObject(StatementQueryMechanism.java:182)
        at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.insertObjectForWrite(DatabaseQueryMechanism.java:504)
        at org.eclipse.persistence.queries.InsertObjectQuery.executeCommit(InsertObjectQuery.java:82)
        at org.eclipse.persistence.queries.InsertObjectQuery.executeCommitWithChangeSet(InsertObjectQuery.java:92)
        at org.eclipse.persistence.internal.queries.DatabaseQueryMechanism.executeWriteWithChangeSet(DatabaseQueryMechanism.java:316)
        at org.eclipse.persistence.queries.WriteObjectQuery.executeDatabaseQuery(WriteObjectQuery.java:60)
        at org.eclipse.persistence.queries.DatabaseQuery.execute(DatabaseQuery.java:911)
        at org.eclipse.persistence.queries.DatabaseQuery.executeInUnitOfWork(DatabaseQuery.java:810)
        at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWorkObjectLevelModifyQuery(ObjectLevelModifyQuery.java:110)
        at org.eclipse.persistence.queries.ObjectLevelModifyQuery.executeInUnitOfWork(ObjectLevelModifyQuery.java:87)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.internalExecuteQuery(UnitOfWorkImpl.java:3004)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1898)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1880)
        at org.eclipse.persistence.internal.sessions.AbstractSession.executeQuery(AbstractSession.java:1830)
        at org.eclipse.persistence.internal.sessions.CommitManager.commitNewObjectsForClassWithChangeSet(CommitManager.java:229)
        at org.eclipse.persistence.internal.sessions.CommitManager.commitAllObjectsWithChangeSet(CommitManager.java:128)
        at org.eclipse.persistence.internal.sessions.AbstractSession.writeAllObjectsWithChangeSet(AbstractSession.java:4409)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabase(UnitOfWorkImpl.java:1503)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.commitToDatabaseWithChangeSet(UnitOfWorkImpl.java:1593)
        at org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.issueSQLbeforeCompletion(UnitOfWorkImpl.java:3281)
        at org.eclipse.persistence.internal.sessions.RepeatableWriteUnitOfWork.issueSQLbeforeCompletion(RepeatableWriteUnitOfWork.java:357)
        at org.eclipse.persistence.transaction.AbstractSynchronizationListener.beforeCompletion(AbstractSynchronizationListener.java:160)
        ... 60 more
    Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:349)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130)
        at jdk.internal.reflect.GeneratedMethodAccessor59.invoke(Unknown Sou...
```

**Environment**
Which version of IBM FHIR Server? main

**To Reproduce**
1. Setup the bulkdata datasource
2. Export an Import
3. Restart the postgres db
4. Execute an Import 
5. It should fail

**Expected behavior**

**Additional context**

**Comment by d0roppe** [comment]
Verified that after a database disconnect while the fhir server stays running, the next $export works just fine.  Closing issue
