### ISSUE TITLE
invalid sort parameter value leads to 500 server error

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#3274]
**Describe the bug**
invalid sort parameter value leads to 500 Sever Error but should be 400 Bad Request
```
Caused by: java.lang.IllegalArgumentException: Invalid sortValue: -lastUpdated
	at com.ibm.fhir.persistence.HistorySortOrder.of(HistorySortOrder.java:61)
	at com.ibm.fhir.persistence.util.FHIRPersistenceUtil.parseSystemHistoryParameters(FHIRPersistenceUtil.java:186)
	... 65 more
```

**Environment**
main

**To Reproduce**
invoke whole-system history with a bogus sort value; for example
`{{base}}/_history?_sort=bogus`

**Expected behavior**
it should be a 400 Bad Request, not a 500.  

**Additional context**
missed this in the description and QA for #2026

**Comment by d0roppe** [comment]
verified that this error is now a code  400, also verified other errors with _history are also code 400
