### ISSUE TITLE
400 error code issued when it should be 500

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#3534]
**Describe the bug**
In running bulk data export I had the wrong port configured in my fhir-server-config.json for but the port I did have was for a local web page.
```
         "core":{
            "api":{
               "url":"https://localhost:9444/ibm/api/batch",
```

error
```
{
	"resourceType": "OperationOutcome",
	"id": "c0-a8-1-d7-153e4a0f-fd61-445e-a4f4-80c599521ff1",
	"issue": [
		{
			"severity": "error",
			"code": "invalid",
			"diagnostics": "Unable to create the $export job"
		}
	]
}
```

Here is the stack trace from the log:
```
[3/30/22, 17:59:11:409 UTC] 00000060 FHIRResource  1   Unable to create the $export job
                                 com.ibm.fhir.exception.FHIROperationException: Unable to create the $export job  [probeId=c0-a8-1-d7-5cb4c1ae-707c-460b-b2d5-43b026b7b4cd]
	at com.ibm.fhir.operation.bulkdata.util.BulkDataExportUtil.buildOperationException(BulkDataExportUtil.java:123)
	at com.ibm.fhir.operation.bulkdata.util.BulkDataExportUtil.buildOperationException(BulkDataExportUtil.java:119)
	at com.ibm.fhir.operation.bulkdata.client.BulkDataClient.submitExport(BulkDataClient.java:242)
	at com.ibm.fhir.operation.bulkdata.processor.impl.ExportImportImpl.export(ExportImportImpl.java:86)
	at com.ibm.fhir.operation.bulkdata.ExportOperation.doInvoke(ExportOperation.java:83)
	at com.ibm.fhir.server.spi.operation.AbstractOperation.invoke(AbstractOperation.java:57)
	at com.ibm.fhir.server.util.FHIRRestHelper.doInvoke(FHIRRestHelper.java:1441)
	at com.ibm.fhir.server.resources.Operation.invoke(Operation.java:215)
	at com.ibm.fhir.server.resources.Operation$Proxy$_$$_WeldClientProxy.invoke(Unknown Source)
```
**Environment**
FHIR-latest

**Comment by d0roppe** [comment]
This now reports the same error but with a 500 error code
```
{
	"resourceType": "OperationOutcome",
	"id": "c0-a8-1-d7-abc1935a-7e74-4e92-bdc3-ce8b03f6473c",
	"issue": [
		{
			"severity": "error",
			"code": "exception",
			"diagnostics": "Unable to create the $export job"
		}
	]
}
```
