### ISSUE TITLE
using fhirserver id for bulk data it needs more authority than given by schema tool

### ISSUE THREAD

**Issue by d0roppe** [IBM/FHIR#3538]
**Describe the bug**
Setting up Bulk data to use fhirserver ID for use with fhir-jbatch schema.  And using the `--grant-to fhirserver` on the `fhir-persistence-schema-*-cli.jar`
When trying to issue the $export command the following error is given with a 500 return code
```
{
	"resourceType": "OperationOutcome",
	"id": "c0-a8-1-d7-67745e16-9d63-4280-a594-167af1607470",
	"issue": [
		{
			"severity": "error",
			"code": "exception",
			"diagnostics": "Server Side Error for Batch Framework"
		}
	]
}
```

Here is info from the stack trace
```
[3/30/22, 19:35:56:934 UTC] 0000003e RegisteredSyn E   WTRN0074E: Exception caught from before_completion synchronization operation: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.10.v20211216-fe64cd39c3): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: permission denied for sequence jobinstance_jobinstanceid_seq
Error Code: 0
Call: select lastval()
Query: ValueReadQuery(name="SEQ_GEN_IDENTITY" sql="select lastval()")
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl$1.handleException(EntityManagerSetupImpl.java:788)
	at org.eclipse.persistence.transaction.AbstractSynchronizationListener.handleException(AbstractSynchronizationListener.java:277)
	at org.eclipse.persistence.transaction.AbstractSynchronizationListener.beforeCompletion(AbstractSynchronizationListener.java:172)
	at org.eclipse.persistence.transaction.JTASynchronizationListener.beforeCompletion(JTASynchronizationListener.java:70)
	at com.ibm.tx.jta.impl.RegisteredSyncs.coreDistributeBefore(RegisteredSyncs.java:238)
	at com.ibm.tx.jta.impl.RegisteredSyncs.distributeBefore(RegisteredSyncs.java:146)
	at com.ibm.tx.jta.impl.TransactionImpl.prePrepare(TransactionImpl.java:1403)
	at com.ibm.tx.jta.impl.TransactionImpl.stage1CommitProcessing(TransactionImpl.java:813)
	at com.ibm.tx.jta.impl.TransactionImpl.processCommit(TransactionImpl.java:769)
	at com.ibm.tx.jta.impl.TransactionImpl.commit(TransactionImpl.java:712)
	at com.ibm.tx.jta.impl.TranManagerImpl.commit(TranManagerImpl.java:153)
	at com.ibm.tx.jta.impl.TranManagerSet.commit(TranManagerSet.java:110)
	at com.ibm.ws.transaction.services.TransactionManagerService.commit(TransactionManagerService.java:296)
	at com.ibm.jbatch.container.services.impl.JPAPersistenceManagerImpl$TranRequest.commitIfNewTranWasStarted(JPAPersistenceManagerImpl.java:2825)
	at com.ibm.jbatch.container.services.impl.JPAPersistenceManagerImpl$TranRequest.runInNewOrExistingGlobalTran(JPAPersistenceManagerImpl.java:2789)
	at com.ibm.jbatch.container.services.impl.JPAPersistenceManagerImpl.createJobInstance(JPAPersistenceManagerImpl.java:431)
	at com.ibm.jbatch.container.impl.BatchKernelImpl.createJobInstance(BatchKernelImpl.java:277)
	at com.ibm.jbatch.container.ws.impl.WSJobOperatorImpl.createJobInstance(WSJobOperatorImpl.java:163)
	at com.ibm.ws.jbatch.rest.internal.BatchManagerImpl.start(BatchManagerImpl.java:404)
	at com.ibm.ws.jbatch.rest.internal.resources.JobInstances.submitJob(JobInstances.java:653)
	at com.ibm.ws.jbatch.rest.internal.resources.JobInstances.access$600(JobInstances.java:115)
	at com.ibm.ws.jbatch.rest.internal.resources.JobInstances$JobInstancesHandler.post(JobInstances.java:286)
	at com.ibm.ws.jbatch.rest.internal.resources.RequestRouter.routeRequestInternal(RequestRouter.java:87)
	at com.ibm.ws.jbatch.rest.internal.resources.RequestRouter.routeRequest(RequestRouter.java:70)
	at com.ibm.ws.jbatch.rest.internal.resources.JobInstances.handleRequest(JobInstances.java:263)
	at com.ibm.ws.rest.handler.internal.service.RESTHandlerContainerImpl.handleRequest(RESTHandlerContainerImpl.java:463)
	at com.ibm.ws.rest.handler.internal.servlet.RESTProxyServlet.handleWithDelegate(RESTProxyServlet.java:119)
	at com.ibm.ws.rest.handler.internal.servlet.RESTProxyServlet.service(RESTProxyServlet.java:64)
	...
Caused by: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.10.v20211216-fe64cd39c3): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: permission denied for sequence jobinstance_jobinstanceid_seq
Error Code: 0
Call: select lastval()
Query: ValueReadQuery(name="SEQ_GEN_IDENTITY" sql="select lastval()")
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:342)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.processExceptionForCommError(DatabaseAccessor.java:1655)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.basicExecuteCall(DatabaseAccessor.java:683)
	at org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor.executeCall(DatabaseAccessor.java:567)
	at org.eclipse.persistence.internal.sessions.AbstractSession.basicExecuteCall(AbstractSession.java:2105)
	... 
Caused by: org.postgresql.util.PSQLException: ERROR: permission denied for sequence jobinstance_jobinstanceid_seq
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
        ...
```

**Environment**
FHIR-main

**To Reproduce**
For the bulk data datasource use the fhirserver profile for access to fhir-jbatch schema

**Expected behavior**
The  `--grant-to fhirserver` on the `fhir-persistence-schema-*-cli.jar` should give all the authority needed to use the profile for the bulk data setup.

**Comment by d0roppe** [comment]
Verified the fix does now give proper authority when executing the `fhir-persistence-schema-4.11.0-SNAPSHOT-cli.jar` command with `--grant-to fhirserver` option
```
2022-03-31 11:56:44.318 00000001    INFO s.common.CommonDatabaseAdapter Applying: GRANT INSERT,UPDATE,SELECT,DELETE ON FHIR_JBATCH.JOBINSTANCE TO FHIRSERVER
2022-03-31 11:56:44.324 00000001    INFO s.common.CommonDatabaseAdapter Applying: GRANT INSERT,UPDATE,SELECT,DELETE ON FHIR_JBATCH.JOBEXECUTION TO FHIRSERVER
2022-03-31 11:56:44.328 00000001    INFO s.common.CommonDatabaseAdapter Applying: GRANT INSERT,UPDATE,SELECT,DELETE ON FHIR_JBATCH.STEPTHREADEXECUTION TO FHIRSERVER
2022-03-31 11:56:44.332 00000001    INFO s.common.CommonDatabaseAdapter Applying: GRANT INSERT,UPDATE,SELECT,DELETE ON FHIR_JBATCH.STEPTHREADINSTANCE TO FHIRSERVER
2022-03-31 11:56:44.337 00000001    INFO s.common.CommonDatabaseAdapter Applying: GRANT INSERT,UPDATE,SELECT,DELETE ON FHIR_JBATCH.REMOTABLEPARTITION TO FHIRSERVER
2022-03-31 11:56:44.341 00000001    INFO s.common.CommonDatabaseAdapter Applying: GRANT INSERT,UPDATE,SELECT,DELETE ON FHIR_JBATCH.GROUPASSOCIATION TO FHIRSERVER
2022-03-31 11:56:44.345 00000001    INFO s.common.CommonDatabaseAdapter Applying: GRANT INSERT,UPDATE,SELECT,DELETE ON FHIR_JBATCH.JOBPARAMETER TO FHIRSERVER
2022-03-31 11:56:44.349 00000001    INFO utils.postgres.PostgresAdapter Applying: GRANT USAGE ON ALL SEQUENCES IN SCHEMA FHIR_JBATCH TO FHIRSERVER
```
Closing issue
