### ISSUE TITLE
FHIRPathEvaluator throws NullPointerException for certain expressions

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#389]
**Describe the bug**
```
com.ibm.fhir.model.path.exception.FHIRPathException: java.lang.NullPointerException  [probeId=7f-0-0-1-5eba9c55-c4d5-4fb4-a889-78ba981f15ca]
	at com.ibm.fhir.model.path.evaluator.FHIRPathEvaluator.evaluate(FHIRPathEvaluator.java:109)
	at com.ibm.fhir.model.path.evaluator.FHIRPathEvaluator.evaluate(FHIRPathEvaluator.java:99)
	at com.ibm.fhir.model.path.evaluator.FHIRPathEvaluator.evaluate(FHIRPathEvaluator.java:95)
	at com.ibm.fhir.model.path.test.FHIRPathSpecTest.executeTest(FHIRPathSpecTest.java:79)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException
	at com.ibm.fhir.model.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitMembershipExpression(FHIRPathEvaluator.java:730)
	at com.ibm.fhir.model.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitMembershipExpression(FHIRPathEvaluator.java:1)
	at com.ibm.fhir.model.path.FHIRPathParser$MembershipExpressionContext.accept(FHIRPathParser.java:299)
	at com.ibm.fhir.model.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.evaluate(FHIRPathEvaluator.java:148)
	at com.ibm.fhir.model.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.access$42(FHIRPathEvaluator.java:144)
	at com.ibm.fhir.model.path.evaluator.FHIRPathEvaluator.evaluate(FHIRPathEvaluator.java:107)
	... 26 more
```

**To Reproduce**
Execute the FHIRPathSpecTest and look through the results for cases from:
* testContainsString

**Expected behavior**
Not a NPE

**Comment by lmsurpre** [comment]
I confirm that the NullPointer-related errors seem to be addressed.
