### ISSUE TITLE
derby deaklock if read/create fhir resources in multiple thread simultaneously

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#396]
This issue happened during jdbc performance test for Derby Network Server, and because the performance test for embedded Derby server only use a single shared connection and each thread never commit the changes, so it works fine there. and there is no such issue for DB2.

The root cause of this issue is the missing indexes(for CURRENT_RESOURCE_ID and LOGICAL_ID) in all the XXX_LOGICAL_RESOURCES tables, and these 2 columns are widely used in the where clause of the select sql for search of all fhir resources. If there is any column used in where clause and not indexed, derby will lock the whole table instead of the required row(s) only, this has caused the dead lock issue we saw in the test.

The fix is to add the missing indexes for the tables.

```
Nov 11, 2019 1:40:30 PM com.ibm.fhir.model.spec.test.R4ExamplesDriver processIndex
INFO: Processing index file 'json/performance.txt' with format 'JSON'
..Nov 11, 2019 1:40:32 PM com.ibm.fhir.database.utils.common.JdbcConnectionProvider getConnection
INFO: Opening connection to database: jdbc:derby://localhost:1527/fhirdb
Nov 11, 2019 1:40:32 PM com.ibm.fhir.database.utils.common.JdbcConnectionProvider getConnection
INFO: Opening connection to database: jdbc:derby://localhost:1527/fhirdb
Nov 11, 2019 1:40:53 PM com.ibm.fhir.persistence.jdbc.dao.impl.FHIRDbDAOImpl severe
SEVERE: Failure retrieving FHIR objects. SQL=SELECT R.RESOURCE_ID, R.LOGICAL_RESOURCE_ID, R.VERSION_ID, R.LAST_UPDATED, R.IS_DELETED, R.DATA, LR.LOGICAL_ID FROM Account_RESOURCES R, Account_LOGICAL_RESOURCES LR WHERE LR.LOGICAL_ID = ? AND R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID  searchArgs=[2159fec5-8b38-4908-ba0f-6b79c22258f5] [probeId=c0-a8-1-be-cb9f757a-81d0-40aa-b5bd-02f8caf7fc81]
java.sql.SQLTransactionRollbackException: A lock could not be obtained due to a deadlock, cycle of locks and waiters is:
Lock : ROW, ACCOUNT_LOGICAL_RESOURCES, (1,25)
  Waiting XID : {130492, S} , APP, SELECT R.RESOURCE_ID, R.LOGICAL_RESOURCE_ID, R.VERSION_ID, R.LAST_UPDATED, R.IS_DELETED, R.DATA, LR.LOGICAL_ID FROM Account_RESOURCES R, Account_LOGICAL_RESOURCES LR WHERE LR.LOGICAL_ID = ? AND R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID
  Granted XID : {130493, X} 
Lock : ROW, ACCOUNT_LOGICAL_RESOURCES, (1,26)
  Waiting XID : {130493, S} , APP, SELECT R.RESOURCE_ID, R.LOGICAL_RESOURCE_ID, R.VERSION_ID, R.LAST_UPDATED, R.IS_DELETED, R.DATA, LR.LOGICAL_ID FROM Account_RESOURCES R, Account_LOGICAL_RESOURCES LR WHERE LR.LOGICAL_ID = ? AND R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID
  Granted XID : {130492, X} 
. The selected victim is XID : 130492.
    at org.apache.derby.client.am.SQLExceptionFactory.getSQLException(Unknown Source)
    at org.apache.derby.client.am.SqlException.getSQLException(Unknown Source)
    at org.apache.derby.client.am.ClientPreparedStatement.executeQuery(Unknown Source)
    at com.ibm.fhir.persistence.jdbc.dao.impl.FHIRDbDAOImpl.runQuery(FHIRDbDAOImpl.java:368)
    at com.ibm.fhir.persistence.jdbc.dao.impl.ResourceDAOImpl.read(ResourceDAOImpl.java:135)
    at com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl.read(FHIRPersistenceJDBCImpl.java:652)
    at com.ibm.fhir.persistence.jdbc.test.spec.ReadOperation.process(ReadOperation.java:63)
    at com.ibm.fhir.persistence.jdbc.test.spec.R4JDBCExamplesProcessor.process(R4JDBCExamplesProcessor.java:161)
    at com.ibm.fhir.model.spec.test.R4ExamplesDriver.processExample(R4ExamplesDriver.java:462)
    at com.ibm.fhir.model.spec.test.R4ExamplesDriver.processExample(R4ExamplesDriver.java:361)
    at com.ibm.fhir.model.spec.test.R4ExamplesDriver$1.run(R4ExamplesDriver.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: ERROR 40001: A lock could not be obtained due to a deadlock, cycle of locks and waiters is:
Lock : ROW, ACCOUNT_LOGICAL_RESOURCES, (1,25)
  Waiting XID : {130492, S} , APP, SELECT R.RESOURCE_ID, R.LOGICAL_RESOURCE_ID, R.VERSION_ID, R.LAST_UPDATED, R.IS_DELETED, R.DATA, LR.LOGICAL_ID FROM Account_RESOURCES R, Account_LOGICAL_RESOURCES LR WHERE LR.LOGICAL_ID = ? AND R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID
  Granted XID : {130493, X} 
Lock : ROW, ACCOUNT_LOGICAL_RESOURCES, (1,26)
  Waiting XID : {130493, S} , APP, SELECT R.RESOURCE_ID, R.LOGICAL_RESOURCE_ID, R.VERSION_ID, R.LAST_UPDATED, R.IS_DELETED, R.DATA, LR.LOGICAL_ID FROM Account_RESOURCES R, Account_LOGICAL_RESOURCES LR WHERE LR.LOGICAL_ID = ? AND R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID
  Granted XID : {130492, X} 
. The selected victim is XID : 130492.
    at org.apache.derby.client.am.ClientStatement.completeSqlca(Unknown Source)
    at org.apache.derby.client.am.ClientStatement.completeOpenQuery(Unknown Source)
    at org.apache.derby.client.net.NetStatementReply.parseOpenQueryFailure(Unknown Source)
    at org.apache.derby.client.net.NetStatementReply.parseOPNQRYreply(Unknown Source)
    at org.apache.derby.client.net.NetStatementReply.readOpenQuery(Unknown Source)
    at org.apache.derby.client.net.StatementReply.readOpenQuery(Unknown Source)
    at org.apache.derby.client.net.NetStatement.readOpenQuery_(Unknown Source)
    at org.apache.derby.client.am.ClientStatement.readOpenQuery(Unknown Source)
    at org.apache.derby.client.am.ClientPreparedStatement.flowExecute(Unknown Source)
    at org.apache.derby.client.am.ClientPreparedStatement.executeQueryX(Unknown Source)
    ... 12 more
Nov 11, 2019 1:40:53 PM com.ibm.fhir.database.utils.pool.PoolConnectionProvider commitTransaction
INFO: Committing transaction
Nov 11, 2019 1:40:53 PM com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl read
SEVERE: Unexpected error while performing a read operation.
```

**Comment by prb112** [comment]
a reference worth reviewing... http://db.apache.org/derby/docs/10.15/devguide/cdevconcepts16400.html#cdevconcepts16400

**Comment by prb112** [comment]
Moved to Review/QA
