### ISSUE TITLE
need to update index files - all.txt and performance.txt

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#427]
There are errors when running R4ExamplesDriver using the all.txt and performance.txt index files, the actually result is OK but the index files expect VALIDATION.

json/ibm/minimal/AllergyIntolerance-2.json: wanted: VALIDATION got:         OK
    at com.ibm.fhir.model.spec.test.R4ExamplesDriver.processExample(R4ExamplesDriver.java:421)
    at com.ibm.fhir.model.spec.test.R4ExamplesDriver.processExample(R4ExamplesDriver.java:361)
    at com.ibm.fhir.model.spec.test.R4ExamplesDriver$1.run(R4ExamplesDriver.java:293)

**Comment by prb112** [comment]
Discussed with Team - this is closed and merged
