### ISSUE TITLE
Unexpected MetadataResource support in JSON/XML parsers

### ISSUE THREAD

**Issue by prb112** [IBM/FHIR#623]
**Unexpected MetadataResource support in JSON/XML parsers**

**To Reproduce**
1. Create a Test in FHIR Model with the following code
``` java
        MetadataResource.Builder builder = MetadataResource.builder();//(ConceptMap.Builder) TestUtil.readExampleResource("json/ibm/minimal/ConceptMap-1.json").toBuilder();
        builder.url(Uri.uri("https://my-fhir-server"));
        builder.version(string("1"));
        builder.name(string("1-2-3-4"));
        builder.title(string("patient"));
        builder.status(PublicationStatus.ACTIVE);
        builder.experimental(com.ibm.fhir.model.type.Boolean.of("1"));
        builder.publisher(string("IBM-FHIR-Server-Tests"));
        
        Resource patient1 = builder.build();
        
        try (StringWriter writer = new StringWriter()) {
            FHIRGenerator.generator(Format.XML).generate(patient1, writer);

            String out = writer.toString();
            assertNotNull(out);
            assertFalse(out.isEmpty());
            System.out.println(out);

            try (ByteArrayInputStream in = new ByteArrayInputStream(out.getBytes())) {
                Resource parametersParsedJson = FHIRParser.parser(Format.XML).parse(in).as(Resource.class);

            }
        }
```

2.See the error
```
[RemoteTestNG] detected TestNG version 6.14.3
<MetadataResource xmlns="http://hl7.org/fhir"><url value="https://my-fhir-server"/><version value="1"/><name value="1-2-3-4"/><title value="patient"/><status value="active"/><experimental value="false"/><publisher value="IBM-FHIR-Server-Tests"/></MetadataResource>
FAILED: testContributor
com.ibm.fhir.model.parser.exception.FHIRParserException: Invalid resource type: 'MetadataResource'  [probeId=7f-0-0-1-ce6793f7-32a4-43ca-879a-fe7560e92290]
	at com.ibm.fhir.model.parser.FHIRXMLParser.parse(FHIRXMLParser.java:64)
	at com.ibm.fhir.model.test.ContributorModelTest.testContributor(ContributorModelTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.IllegalArgumentException: Invalid resource type: 'MetadataResource'
	at com.ibm.fhir.model.parser.FHIRXMLParser.getResourceType(FHIRXMLParser.java:51329)
	at com.ibm.fhir.model.parser.FHIRXMLParser.parse(FHIRXMLParser.java:59)
	... 26 more
```

**Expected behavior**
The MetadataResource should not be parseable or available in ModelSupport.getResourceTypes.  

There is also no schema table generated, so the 'invalid' resource is never stored in the jdbc layer. 

**Additional context**
From the `profiles-resource.json`

``` json
"type" : "ConceptMap",
      "baseDefinition" : "http://hl7.org/fhir/StructureDefinition/DomainResource",
      "_baseDefinition" : {
        "extension" : [{
          "url" : "http://hl7.org/fhir/StructureDefinition/structuredefinition-codegen-super",
          "valueString" : "MetadataResource"
        }]
      },
```

Also reference to https://www.hl7.org/fhir/clinicalreasoning-knowledge-artifact-representation.html#metadata

I think, as Lee mentioned to me, that this class should be Abstract, and used in a hierarchy with ConceptMap and the other 28 (29 in total) referenced resources.

**Comment by lmsurpre** [comment]
There's really two options:
A. keep it and make it an abstract superclass of the 29 "knowledge artifact" resources
B. throw it out and keep the rest of the model as it is now (duplicate but independent fields in each of the "knowledge artifact" types)

Option A has the benefit of reducing redundancy in the model and giving us a handle for working with "any knowledge artifact".  However, it also comes with a price.
Other abstract supertypes like Resource and DomainResource are still returned from `ModelSupport.getResourceTypes` and we even generate resource tables for those ones I think.
We'd need to decide whether to do something similar for this one or not.  I'm guessing we'll need to code around the new Abstract supertype in other places too (e.g. swagger generator).

**Comment by prb112** [comment]
[A] makes sense to me.  I'd suggest cleaning up getResourceTypes usage.

**Comment by JohnTimm** [comment]
I'm not opposed to supporting the serialization / deserialization  and validation of "logical" resource types. I do agree that we should not create database tables for "logical" or "abstract" resource types.

**Comment by lmsurpre** [comment]
#688 implements option 1.  John found that the model does not consistently follow the pattern laid out in MetadataResource, and so this was the only reasonable option.
However, I don't think we should close this issue until we either complete or open a separate task for the following items:
1. Open HL7 JIRA issues for all the ways in which MetadaResource is broken (differing return types, different cardinalities, etc); and
2. Figure out our story on the Resource and DomainResource tables

John found that we are adding "cross-resource" search params to the Resource_X_VALUES tables, but I don't think our queries are actually using those.  Should they be?

What about `Resource_LOGICAL_RESOURCES`, `DomainResource_LOGICAL_RESOURCES`, `Resource_RESOURCES`, and `DomainResource_RESOURCES tables`...are we generating those tables?  Do we need them?

**Comment by JohnTimm** [comment]
I suggest we close this issue (after Review/QA) and create separate a separate issue to create tracker items and address superfluous tables in JDBC persistence layer. My initial take on the JDBC persistence layer task is that it will require some surgery to only create the parameter tables and leave out the logical resources table, etc. and I don't think it's a very high priority to do so.

**Comment by lmsurpre** [comment]
remaining work is in https://github.com/IBM/FHIR/issues/713
