### ISSUE TITLE
Error running https://<host>:<port>/fhir-server/api/v4/ right after install

### ISSUE THREAD

**Issue by festewart** [IBM/FHIR#656]
**Describe the bug**
After installing and before writing anything to FHIR, curl -k -u fhiruser https://localhost:9447/fhir-server/api/v4/  returns error outcome and errors logged to messages.log

**To Reproduce**
1. Install R4.0.1 using defaults (no data loaded)
2. curl -k -u fhiruser https://localhost:9447/fhir-server/api/v4/
Enter host password for user 'fhiruser'
Output is:
{"resourceType":"OperationOutcome","id":"c0-a8-30-21-58f8457b-3823-48ae-9916-859993ce8f33","issue":[{"severity":"fatal","code":"processing","details":{"text":"FHIRPersistenceDataAccessException: Server error: failure retrieving count"}}]}
3. Error in messages.log is:
[1/30/20 6:57:38:595 CST] 00000079 com.ibm.fhir.server.resources.FHIRResource                   W Caught exception while processing 'search' request.
com.ibm.fhir.persistence.jdbc.exception.FHIRPersistenceDataAccessException: Server error: failure retrieving count  [probeId=c0-a8-30-21-58f8457b-3823-48ae-9916-859993ce8f33]
    at com.ibm.fhir.persistence.jdbc.dao.impl.FHIRDbDAOImpl.runCountQuery(FHIRDbDAOImpl.java:454)
    at com.ibm.fhir.persistence.jdbc.dao.impl.ResourceDAOImpl.searchCount(ResourceDAOImpl.java:291)
    at com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl.search(FHIRPersistenceJDBCImpl.java:429)
    at com.ibm.fhir.server.resources.FHIRResource.doSearch(FHIRResource.java:2146)
    at com.ibm.fhir.server.resources.FHIRResource.doSearchAll(FHIRResource.java:855)
    at com.ibm.fhir.server.resources.FHIRResource.searchAllGet(FHIRResource.java:871)

**Expected behavior**
No error - maybe something saying nothing was found

**Comment by prb112** [comment]
PR https://github.com/IBM/FHIR/pull/658

**Comment by prb112** [comment]
Fix is merged
