### ISSUE TITLE
FHIROperationException: An error occurred during validation

### ISSUE THREAD

**Issue by tbieste** [IBM/FHIR#662]
**Describe the bug**
Get back "FHIROperationException: An error occurred during validation" when attempting to validate a Patient against the us-core-patient profile.

**To Reproduce**
1. Use FHIR server version 4.0.1 or checkout tag 4.0.1
2. Deploy the code to the environment
3. Add fhir-ig-us-core to your userlib folder
4. Call the $validate REST API with a Patient that includes "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient" in the metadata.profile field.
```
curl -H "Content-Type: application/fhir+json" -k 'https://localhost:9443/fhir-server/api/v4/metadata' -u "fhiruser:REMOVED" -X POST -d @a.json 
```
```
{
    "resourceType": "Parameters",
    "parameter": [
        {
            "name": "profile",
            "valueUri": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"
        },
        {
            "name": "resource",
            "resource": {
                "resourceType": "Patient",
                "text": {
                    "status": "empty",
                    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">empty</div>"
                },
                "meta": {
                    "profile": [
                        "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"
                    ]
                },
                "identifier": [
                    {
                        "type": {
                            "coding": [
                                {
                                    "system": "http://hl7.org/fhir/v2/0203",
                                    "version": "2.5",
                                    "code": "MR",
                                    "display": "Medical record number"
                                }
                            ]
                        },
                        "system": "http://example.com/medical-record-number",
                        "value": "1",
                        "assigner": {
                            "display": "EXAMPLE"
                        }
                    },
                    {
                        "system": "http://example.com/patient-identifier",
                        "value": "1-2-3-4",
                        "assigner": {
                            "display": "EXAMPLE"
                        }
                    }
                ],
                "gender": "male",
                "birthDate": "2000-01-01",
                "deceasedBoolean": true
            }
        }
    ]
}
```
5. Error is returned from $validate REST API in response.
```
[err] com.ibm.fhir.validation.exception.FHIRValidationException: An error occurred during validation
[err] 	at com.ibm.fhir.validation.FHIRValidator.validate(FHIRValidator.java:138)
[err] 	at com.ibm.fhir.validation.FHIRValidator.validate(FHIRValidator.java:84)
[err] 	at com.ibm.fhir.validation.FHIRValidator.validate(FHIRValidator.java:62)
[err] 	at com.ibm.fhir.operation.validate.ValidateOperation.doInvoke(ValidateOperation.java:61)
[err] 	at com.ibm.fhir.operation.AbstractOperation.invoke(AbstractOperation.java:52)
[err] 	at com.ibm.fhir.server.resources.FHIRResource.doInvoke(FHIRResource.java:2269)
[err] 	at com.ibm.fhir.server.resources.FHIRResource.invoke(FHIRResource.java:972)
[err] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[err] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[err] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[err] 	at java.lang.reflect.Method.invoke(Method.java:498)
[err] 	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:656)
[err] 	at [internal classes]
[err] 	at com.ibm.fhir.server.filter.rest.FHIRRestServletFilter.doFilter(FHIRRestServletFilter.java:151)
[err] 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
[err] 	at [internal classes]
[err] 	at com.ibm.fhir.server.filter.rest.FHIRRestAuthorizationServletFilter.doFilter(FHIRRestAuthorizationServletFilter.java:86)
[err] 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
[err] 	at [internal classes]
[err] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[err] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[err] 	at java.lang.Thread.run(Thread.java:748)
[err] Caused by: java.lang.IllegalStateException: An error occurred while validating constraint: generated-us-core-patient-1 with location: (base) and expression: extension('http://hl7.org/fhir/us/core/StructureDefinition/us-core-race').count() <= 1 and (extension('http://hl7.org/fhir/us/core/StructureDefinition/us-core-race').exists() implies (extension('http://hl7.org/fhir/us/core/StructureDefinition/us-core-race').conformsTo('http://hl7.org/fhir/us/core/StructureDefinition/us-core-race'))) at path: Patient
[err] 	at com.ibm.fhir.validation.FHIRValidator$ValidatingNodeVisitor.validate(FHIRValidator.java:260)
[err] 	at com.ibm.fhir.validation.FHIRValidator$ValidatingNodeVisitor.validate(FHIRValidator.java:213)
[err] 	at com.ibm.fhir.validation.FHIRValidator$ValidatingNodeVisitor.validate(FHIRValidator.java:193)
[err] 	at com.ibm.fhir.validation.FHIRValidator$ValidatingNodeVisitor.doVisit(FHIRValidator.java:175)
[err] 	at com.ibm.fhir.path.visitor.FHIRPathDefaultNodeVisitor.visit(FHIRPathDefaultNodeVisitor.java:81)
[err] 	at com.ibm.fhir.path.FHIRPathResourceNode.accept(FHIRPathResourceNode.java:115)
[err] 	at com.ibm.fhir.validation.FHIRValidator$ValidatingNodeVisitor.validate(FHIRValidator.java:160)
[err] 	at com.ibm.fhir.validation.FHIRValidator$ValidatingNodeVisitor.access$1(FHIRValidator.java:155)
[err] 	at com.ibm.fhir.validation.FHIRValidator.validate(FHIRValidator.java:136)
[err] 	... 62 more
[err] Caused by: com.ibm.fhir.path.exception.FHIRPathException: java.lang.IllegalArgumentException: The 'conformsTo' function can only be invoked on a Resource or Element node  [probeId=c0-a8-56-22-2ede2c3f-e8dc-47dd-b5da-ca893ec6b65f]
[err] 	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator.evaluate(FHIRPathEvaluator.java:123)
[err] 	at com.ibm.fhir.validation.FHIRValidator$ValidatingNodeVisitor.validate(FHIRValidator.java:239)
[err] 	... 70 more
[err] Caused by: java.lang.IllegalArgumentException: The 'conformsTo' function can only be invoked on a Resource or Element node
[err] 	at com.ibm.fhir.path.function.ConformsToFunction.apply(ConformsToFunction.java:54)
[err] 	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitFunction(FHIRPathEvaluator.java:1096)
[err] 	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitFunction(FHIRPathEvaluator.java:1)
[err] 	at com.ibm.fhir.path.FHIRPathParser$FunctionContext.accept(FHIRPathParser.java:1122)
[err] 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
[err] 	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitFunctionInvocation(FHIRPathEvaluator.java:1014)
[err] 	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitFunctionInvocation(FHIRPathEvaluator.java:1)
[err] 	at com.ibm.fhir.path.FHIRPathParser$FunctionInvocationContext.accept(FHIRPathParser.java:1033)
[err] 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
[err] 	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitInvocationExpression(FHIRPathEvaluator.java:732)
[err] 	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitInvocationExpression(FHIRPathEvaluator.java:1)
[err] 	at com.ibm.fhir.path.FHIRPathParser$InvocationExpressionContext.accept(FHIRPathParser.java:261)
[err] 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
[err] 	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitParenthesizedTerm(FHIRPathEvaluator.java:913)
[err] 	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitParenthesizedTerm(FHIRPathEvaluator.java:1)
[err] 	at com.ibm.fhir.path.FHIRPathParser$ParenthesizedTermContext.accept(FHIRPathParser.java:663)
[err] 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
[err] 	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitTermExpression(FHIRPathEvaluator.java:831)
[err] 	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitTermExpression(FHIRPathEvaluator.java:1)
[err] 	at com.ibm.fhir.path.FHIRPathParser$TermExpressionContext.accept(FHIRPathParser.java:300)
[err] 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
[err] 	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitImpliesExpression(FHIRPathEvaluator.java:794)
[err] 	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitImpliesExpression(FHIRPathEvaluator.java:1)
[err] 	at com.ibm.fhir.path.FHIRPathParser$ImpliesExpressionContext.accept(FHIRPathParser.java:289)
[err] 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
[err] 	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitParenthesizedTerm(FHIRPathEvaluator.java:913)
[err] 	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitParenthesizedTerm(FHIRPathEvaluator.java:1)
[err] 	at com.ibm.fhir.path.FHIRPathParser$ParenthesizedTermContext.accept(FHIRPathParser.java:663)
[err] 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
[err] 	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitTermExpression(FHIRPathEvaluator.java:831)
[err] 	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitTermExpression(FHIRPathEvaluator.java:1)
[err] 	at com.ibm.fhir.path.FHIRPathParser$TermExpressionContext.accept(FHIRPathParser.java:300)
[err] 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
[err] 	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitAndExpression(FHIRPathEvaluator.java:628)
[err] 	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.visitAndExpression(FHIRPathEvaluator.java:1)
[err] 	at com.ibm.fhir.path.FHIRPathParser$AndExpressionContext.accept(FHIRPathParser.java:219)
[err] 	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.evaluate(FHIRPathEvaluator.java:162)
[err] 	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator$EvaluatingVisitor.access$43(FHIRPathEvaluator.java:158)
[err] 	at com.ibm.fhir.path.evaluator.FHIRPathEvaluator.evaluate(FHIRPathEvaluator.java:121)
[err] 	... 71 more
```

**Expected behavior**
Validation results that explain how Patient validates against the us-core-patient profile.

**Comment by prb112** [comment]
Root cause is related to the treatment of the ig's conformsTo 
```
Caused by: java.lang.IllegalStateException: An error occurred while validating constraint: generated-us-core-patient-1 with location: (base) and expression: extension('http://hl7.org/fhir/us/core/StructureDefinition/us-core-race').count() <= 1 and (extension('http://hl7.org/fhir/us/core/StructureDefinition/us-core-race').exists() implies (extension('http://hl7.org/fhir/us/core/StructureDefinition/us-core-race').conformsTo('http://hl7.org/fhir/us/core/StructureDefinition/us-core-race'))) at path: Patient
```

**Comment by JohnTimm** [comment]
I was able to reproduce this issue locally with a unit test.
