### ISSUE TITLE
Avoid creating unnecessary tables for Resource and DomainResource resource types

### ISSUE THREAD

**Issue by lmsurpre** [IBM/FHIR#713]
**Describe the bug**
Follow-on from #623 

What about Resource_LOGICAL_RESOURCES, DomainResource_LOGICAL_RESOURCES, Resource_RESOURCES, and DomainResource_RESOURCES tables...are we generating those tables? Do we need them?

John tried to remove these, but something must be trying to use it because he saw a ForeignKeyException that he traced back to these missing tables.

**To Reproduce**
1. deploy the schema
2. look at the tables

**Expected behavior**
Abstract resources shouldn't have resource tables.

**Additional context**
The way its designed, we'd need to special case these somehow.  Is there a cleaner way?

**Comment by lmsurpre** [comment]
Somewhat related to #819

**Comment by lmsurpre** [comment]
snippet showing what john found previously:
```[2021-02-26T04:06:20.661+0000] 00000039 com.ibm.fhir.server.filter.rest.FHIRRestServletFilter        I Received request: tenantId:[tenant1] dsId:[profile] user:[fhiruser] method:[POST] uri:[https://localhost:9443/fhir-server/api/v4/Patient]
[2021-02-26T04:06:21.925+0000] 00000039 com.ibm.ws.rsadapter.impl.DatabaseHelper                     I DSRA8203I: Database product name : Apache Derby
[2021-02-26T04:06:21.925+0000] 00000039 com.ibm.ws.rsadapter.impl.DatabaseHelper                     I DSRA8204I: Database product version : 10.14.2.0 - (1828579)
[2021-02-26T04:06:21.925+0000] 00000039 com.ibm.ws.rsadapter.impl.DatabaseHelper                     I DSRA8205I: JDBC driver name  : Apache Derby Embedded JDBC Driver
[2021-02-26T04:06:21.925+0000] 00000039 com.ibm.ws.rsadapter.impl.DatabaseHelper                     I DSRA8206I: JDBC driver version  : 10.14.2.0 - (1828579)
[2021-02-26T04:06:21.946+0000] 00000039 com.ibm.fhir.search.util.SearchUtil                          W Skipping search parameter with id='us-core-patient-birthdate'. Found multiple search parameters for code 'birthdate' on resource type 'Patient'; use search parameter filtering to disambiguate.
[2021-02-26T04:06:21.946+0000] 00000039 com.ibm.fhir.search.util.SearchUtil                          W Skipping search parameter with id='us-core-patient-family'. Found multiple search parameters for code 'family' on resource type 'Patient'; use search parameter filtering to disambiguate.
[2021-02-26T04:06:21.946+0000] 00000039 com.ibm.fhir.search.util.SearchUtil                          W Skipping search parameter with id='us-core-patient-name'. Found multiple search parameters for code 'name' on resource type 'Patient'; use search parameter filtering to disambiguate.
[2021-02-26T04:06:21.946+0000] 00000039 com.ibm.fhir.search.util.SearchUtil                          W Skipping search parameter with id='us-core-patient-given'. Found multiple search parameters for code 'given' on resource type 'Patient'; use search parameter filtering to disambiguate.
[2021-02-26T04:06:21.946+0000] 00000039 com.ibm.fhir.search.util.SearchUtil                          W Skipping search parameter with id='us-core-patient-identifier'. Found multiple search parameters for code 'identifier' on resource type 'Patient'; use search parameter filtering to disambiguate.
[2021-02-26T04:06:21.946+0000] 00000039 com.ibm.fhir.search.util.SearchUtil                          W Skipping search parameter with id='us-core-patient-gender'. Found multiple search parameters for code 'gender' on resource type 'Patient'; use search parameter filtering to disambiguate.
[2021-02-26T04:06:21.946+0000] 00000039 com.ibm.fhir.search.util.SearchUtil                          W Code '_id' is defined for Resource and Patient with differing expressions; using Patient
[2021-02-26T04:06:21.974+0000] 00000039 com.ibm.fhir.persistence.jdbc.derby.DerbyResourceDAO         E SQLException encountered while inserting Resource.
java.sql.SQLSyntaxErrorException: Table/View 'RESOURCE_STR_VALUES' does not exist.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.iapi.jdbc.BrokeredConnection.prepareStatement(Unknown Source)
	at com.ibm.ws.rsadapter.jdbc.WSJdbcConnection.prepareStatement(WSJdbcConnection.java:2234)
	at com.ibm.ws.rsadapter.jdbc.WSJdbcConnection.prepareStatement(WSJdbcConnection.java:2199)
	at com.ibm.fhir.persistence.jdbc.dao.impl.ParameterVisitorBatchDAO.<init>(ParameterVisitorBatchDAO.java:190)
	at com.ibm.fhir.persistence.jdbc.derby.DerbyResourceDAO.storeResource(DerbyResourceDAO.java:436)
	at com.ibm.fhir.persistence.jdbc.derby.DerbyResourceDAO.insert(DerbyResourceDAO.java:122)
	at com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl.create(FHIRPersistenceJDBCImpl.java:394)
	at com.ibm.fhir.server.util.FHIRRestHelper.doCreate(FHIRRestHelper.java:252)
	at com.ibm.fhir.server.operation.spi.FHIRResourceHelpers.doCreate(FHIRResourceHelpers.java:43)
	at com.ibm.fhir.server.resources.Create.create(Create.java:83)
	at com.ibm.fhir.server.resources.Create$Proxy$_$$_WeldClientProxy.create(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.ibm.ws.jaxrs20.cdi.component.JaxRsFactoryImplicitBeanCDICustomizer.serviceInvoke(JaxRsFactoryImplicitBeanCDICustomizer.java:342)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:641)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.performInvocation(LibertyJaxRsInvoker.java:160)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:101)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.invoke(LibertyJaxRsInvoker.java:273)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:205)
	at com.ibm.ws.jaxrs20.server.LibertyJaxRsInvoker.invoke(LibertyJaxRsInvoker.java:444)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:111)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:123)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:275)
	at com.ibm.ws.jaxrs20.endpoint.AbstractJaxRsWebEndpoint.invoke(AbstractJaxRsWebEndpoint.java:137)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.handleRequest(IBMRestServlet.java:146)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.doPost(IBMRestServlet.java:104)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:706)
	at com.ibm.websphere.jaxrs.server.IBMRestServlet.service(IBMRestServlet.java:96)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1257)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:745)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:442)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:182)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)
	at com.ibm.fhir.server.filter.rest.FHIRRestServletFilter.doFilter(FHIRRestServletFilter.java:142)
	at javax.servlet.http.HttpFilter.doFilter(HttpFilter.java:127)
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1001)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1139)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1010)
	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)
	at com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40.handleRequest(CacheServletWrapper40.java:83)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:936)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1141)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:422)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:381)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:565)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:499)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:359)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:326)
	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink.determineNextChannel(SSLConnectionLink.java:1100)
	at com.ibm.ws.channel.ssl.internal.SSLConnectionLink$MyReadCompletedCallback.complete(SSLConnectionLink.java:675)
	at com.ibm.ws.channel.ssl.internal.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1824)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
Caused by: ERROR 42X05: Table/View 'RESOURCE_STR_VALUES' does not exist.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.DMLModStatementNode.verifyTargetTable(Unknown Source)
	at org.apache.derby.impl.sql.compile.InsertNode.bindStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	... 71 more
```

**Comment by lmsurpre** [comment]
Question:  Should we remove these unneeded tables as part of schema migration?

team decision:  yes.  but we should ensure there is no data in these tables before we delete them.  if there is data in these tables somehow, then fail the upgrade.  (or finish the upgrade and just log as warning?)


Question:  what to do with the corresponding entries in FHIR_ADMIN.VERSION_HISTORY ?

options:
A. add an audit trail to document what has been executed, and remove the corresponding rows for these tables in VERSION_HISTORY
B. just write the new version to this entry in the VERSION_HISTORY table and that version will mean "its deleted" for these particular tables.  The concern here is that we want a freshly installed schema to look the same as a migrated one.

**Comment by d0roppe** [comment]
verified that the targeted tables are not created in a update-schema, and are removed when issuing an update-schema on an older schema definition.
