### ISSUE TITLE
deadlock causes importjob failure if use multiple partitions for Observation or Organization resources

### ISSUE THREAD

**Issue by albertwang-ibm** [IBM/FHIR#787]
**Problem:**
Importing Observation or Organization resources with multiple partitions/threads in parallel doesn't work.
from the log, seems deadlock happens.
But this works well for all the other fhir resources. 

```
Mar 15 19:09:06 fhir-ibmcloud-75c9d8f479-vx4dm fhir-ibmcloud SEVERE SQLException encountered while inserting Resource.
com.ibm.db2.jcc.am.SqlTransactionRollbackException: DB2 SQL Error: SQLCODE=-911, SQLSTATE=40001, SQLERRMC=2, DRIVER=4.26.14
	at com.ibm.db2.jcc.am.b7.a(b7.java:797)
	at com.ibm.db2.jcc.am.b7.a(b7.java:66)
	at com.ibm.db2.jcc.am.b7.a(b7.java:140)
	at com.ibm.db2.jcc.am.k4.c(k4.java:2824)
	at com.ibm.db2.jcc.t4.ab.x(ab.java:1827)
	at com.ibm.db2.jcc.t4.ab.n(ab.java:950)
	at com.ibm.db2.jcc.t4.ab.f(ab.java:156)
	at com.ibm.db2.jcc.t4.p.e(p.java:81)
	at com.ibm.db2.jcc.t4.av.k(av.java:175)
	at com.ibm.db2.jcc.am.k4.ao(k4.java:2413)
	at com.ibm.db2.jcc.am.k5.a(k5.java:4686)
	at com.ibm.db2.jcc.am.CallableStatement.b(CallableStatement.java:134)
	at com.ibm.db2.jcc.am.CallableStatement.a(CallableStatement.java:103)
	at com.ibm.db2.jcc.am.CallableStatement.execute(CallableStatement.java:93)
	at com.ibm.ws.rsadapter.jdbc.WSJdbcPreparedStatement.execute(WSJdbcPreparedStatement.java:390)
	at com.ibm.fhir.persistence.jdbc.dao.impl.ResourceDAOImpl.insertToDb2(ResourceDAOImpl.java:539)
	at com.ibm.fhir.persistence.jdbc.dao.impl.ResourceDAOImpl.insert(ResourceDAOImpl.java:469)
	at com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl.update(FHIRPersistenceJDBCImpl.java:372)
	at com.ibm.fhir.bulkimport.ChunkWriter.writeItems(ChunkWriter.java:146)
	at com.ibm.jbatch.container.artifact.proxy.ItemWriterProxy.writeItems(ItemWriterProxy.java:80)
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.writeChunk(ChunkStepControllerImpl.java:481)
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.invokeChunk(ChunkStepControllerImpl.java:636)
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.invokeCoreStep(ChunkStepControllerImpl.java:795)
	at com.ibm.jbatch.container.controller.impl.BaseStepControllerImpl.execute(BaseStepControllerImpl.java:295)
	at com.ibm.jbatch.container.controller.impl.ExecutionTransitioner.doExecutionLoop(ExecutionTransitioner.java:118)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeCoreTransitionLoop(WorkUnitThreadControllerImpl.java:96)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeWorkUnit(WorkUnitThreadControllerImpl.java:178)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl$AbstractControllerHelper.runExecutionOnThread(WorkUnitThreadControllerImpl.java:503)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.runExecutionOnThread(WorkUnitThreadControllerImpl.java:92)
	at com.ibm.jbatch.container.util.BatchWorkUnit.run(BatchWorkUnit.java:113)
	at com.ibm.ws.context.service.serializable.ContextualRunnable.run(ContextualRunnable.java:79)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:820)
Mar 15 19:09:06 fhir-ibmcloud-75c9d8f479-vx4dm fhir-ibmcloud WARNING Failed to import 'd7a7b598-4f26-43a6-b82a-c9728a871be9' due to error: SQLException encountered while inserting Resource.
Mar 15 19:09:06 fhir-ibmcloud-75c9d8f479-vx4dm fhir-ibmcloud SEVERE An unexpected error occurred while connecting to the database.
com.ibm.fhir.database.utils.api.DataAccessException: com.ibm.db2.jcc.am.SqlException: [jcc][t4][10342][11669][4.26.14] Application must execute a rollback. The unit of work has already been rolled back in the database but other resource managers involved in this unit of work might not. To ensure integrity of this application, all SQL requests will be rejected until the application issues a rollback.  ERRORCODE=-4497, SQLSTATE=null
	at com.ibm.fhir.database.utils.db2.Db2Translator.translate(Db2Translator.java:107)
	at com.ibm.fhir.database.utils.db2.Db2SetTenantVariable.run(Db2SetTenantVariable.java:50)
	at com.ibm.fhir.database.utils.common.JdbcTarget.runStatement(JdbcTarget.java:58)
	at com.ibm.fhir.database.utils.common.CommonDatabaseAdapter.runStatement(CommonDatabaseAdapter.java:393)
	at com.ibm.fhir.persistence.jdbc.dao.impl.FHIRDbDAOImpl.getConnection(FHIRDbDAOImpl.java:206)
	at com.ibm.fhir.persistence.jdbc.dao.impl.FHIRDbDAOImpl.runQuery(FHIRDbDAOImpl.java:363)
	at com.ibm.fhir.persistence.jdbc.dao.impl.ResourceDAOImpl.read(ResourceDAOImpl.java:140)
	at com.ibm.fhir.persistence.jdbc.impl.FHIRPersistenceJDBCImpl.update(FHIRPersistenceJDBCImpl.java:318)
	at com.ibm.fhir.bulkimport.ChunkWriter.writeItems(ChunkWriter.java:146)
	at com.ibm.jbatch.container.artifact.proxy.ItemWriterProxy.writeItems(ItemWriterProxy.java:80)
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.writeChunk(ChunkStepControllerImpl.java:481)
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.invokeChunk(ChunkStepControllerImpl.java:636)
	at com.ibm.jbatch.container.controller.impl.ChunkStepControllerImpl.invokeCoreStep(ChunkStepControllerImpl.java:795)
	at com.ibm.jbatch.container.controller.impl.BaseStepControllerImpl.execute(BaseStepControllerImpl.java:295)
	at com.ibm.jbatch.container.controller.impl.ExecutionTransitioner.doExecutionLoop(ExecutionTransitioner.java:118)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeCoreTransitionLoop(WorkUnitThreadControllerImpl.java:96)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.executeWorkUnit(WorkUnitThreadControllerImpl.java:178)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl$AbstractControllerHelper.runExecutionOnThread(WorkUnitThreadControllerImpl.java:503)
	at com.ibm.jbatch.container.controller.impl.WorkUnitThreadControllerImpl.runExecutionOnThread(WorkUnitThreadControllerImpl.java:92)
	at com.ibm.jbatch.container.util.BatchWorkUnit.run(BatchWorkUnit.java:113)
	at com.ibm.ws.context.service.serializable.ContextualRunnable.run(ContextualRunnable.java:79)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:820)
Caused by: com.ibm.db2.jcc.am.SqlException: [jcc][t4][10342][11669][4.26.14] Application must execute a rollback. The unit of work has already been rolled back in the database but other resource managers involved in this unit of work might not. To ensure integrity of this application, all SQL requests will be rejected until the application issues a rollback.  ERRORCODE=-4497, SQLSTATE=null
	at com.ibm.db2.jcc.am.b7.a(b7.java:794)
	at com.ibm.db2.jcc.am.b7.a(b7.java:66)
	at com.ibm.db2.jcc.am.b7.a(b7.java:133)
	at com.ibm.db2.jcc.t4.T4XAConnection.writeTransactionStart(T4XAConnection.java:133)
	at com.ibm.db2.jcc.am.Agent.beginWriteChain(Agent.java:368)
	at com.ibm.db2.jcc.t4.a.beginWriteChain(a.java:741)
	at com.ibm.db2.jcc.am.k5.a(k5.java:4282)
	at com.ibm.db2.jcc.am.k5.b(k5.java:4182)
	at com.ibm.db2.jcc.am.CallableStatement.be(CallableStatement.java:217)
	at com.ibm.db2.jcc.am.CallableStatement.executeUpdate(CallableStatement.java:192)
	at com.ibm.ws.rsadapter.jdbc.WSJdbcPreparedStatement.executeUpdate(WSJdbcPreparedStatement.java:520)
	at com.ibm.fhir.database.utils.db2.Db2SetTenantVariable.run(Db2SetTenantVariable.java:47)
```

**Comment by prb112** [comment]
Db2SetTenantVariable is the stored procedure at the very beginning of a call.  Is the transaction size too large?
